/**
 * Assignment Timeline Types
 * 
 * Type definitions for resource timeline and scheduling.
 * 
 * Generated by CC - Claude Code
 */

export interface AssignmentTimeline {
  phases: AssignmentPhase[];
  milestones: AssignmentMilestone[];
  dependencies: AssignmentDependency[];
  constraints: AssignmentConstraint[];
  buffers: AssignmentBuffer[];
  optimization: TimelineOptimization;
}

export interface AssignmentPhase {
  phase: string;
  startDate: string;
  endDate: string;
  allocation: number;
  activities: string[];
  deliverables: string[];
  milestones: string[];
  risks: string[];
}

export interface AssignmentMilestone {
  milestone: string;
  date: string;
  type: 'start' | 'delivery' | 'review' | 'decision' | 'completion';
  criteria: string[];
  dependencies: string[];
  stakeholders: string[];
}

export interface AssignmentDependency {
  dependency: string;
  type: 'predecessor' | 'successor' | 'parallel' | 'resource' | 'approval';
  description: string;
  impact: string;
  mitigation: string;
  status: 'pending' | 'active' | 'satisfied' | 'blocked';
}

export interface AssignmentConstraint {
  constraint: string;
  category: 'temporal' | 'resource' | 'skill' | 'location' | 'regulatory';
  description: string;
  impact: string;
  workaround: string;
  escalation: string;
}

export interface AssignmentBuffer {
  type: 'time' | 'resource' | 'skill' | 'cost';
  amount: number;
  rationale: string;
  triggers: string[];
  governance: string;
}

export interface TimelineOptimization {
  acceleration: AccelerationOption[];
  parallelization: ParallelizationOption[];
  resource_leveling: ResourceLevelingOption[];
  critical_path: CriticalPathOptimization;
}

export interface AccelerationOption {
  option: string;
  method: string;
  impact: string;
  cost: string;
  risk: string;
  feasibility: string;
}

export interface ParallelizationOption {
  activities: string[];
  dependencies: string[];
  resource_impact: string;
  coordination: string;
  risk: string;
}

export interface ResourceLevelingOption {
  scenario: string;
  smoothing: string;
  impact: string;
  trade_offs: string[];
  benefits: string[];
}

export interface CriticalPathOptimization {
  current_path: string[];
  alternatives: string[];
  bottlenecks: string[];
  acceleration: string[];
  risks: string[];
}