/**
 * Report Types Index
 * 
 * Centralized exports for all report type definitions including
 * generation, customization, structure, styling, and distribution.
 * 
 * Generated by CC - Claude Code
 */

// Export all types from generation module
export type {
  GeneratePlanningReportRequest,
  GeneratePlanningReportResponse,
  PlanningReport,
  ReportMetadata,
  ReportGeneration,
  GenerationQuality,
  GenerationValidation,
  GenerationOptimization,
  ValidationCheck,
  GenerationError,
  GenerationWarning,
  PerformanceOptimization,
  QualityOptimization,
  SizeOptimization,
  AccessibilityOptimization,
  CompressionSettings,
  CachingSettings
} from './generation';

// Export all types from customization module
export type {
  ReportCustomization,
  ReportSectionCustomization,
  ReportStylingCustomization,
  ReportBranding,
  ReportFilter,
  ReportParameter,
  SectionCustomization,
  CustomColorScheme,
  CustomFontScheme,
  CustomLayoutScheme,
  BrandColors,
  BrandFonts,
  BrandHeader,
  BrandFooter,
  ColorMapping,
  ColorAccessibility,
  FontFamily,
  FontSize,
  FontWeight,
  LayoutGrid,
  GridGap,
  GridArea,
  HeaderLogo,
  HeaderText,
  HeaderLayout,
  FooterText,
  FooterLink,
  FooterLayout
} from './customization';

// Export all types from structure module
export type {
  ReportStructure,
  ReportSection,
  ReportSubsection,
  ReportAppendix,
  AppendixContent,
  AppendixSection,
  ReportGlossary,
  GlossaryTerm,
  GlossaryReference,
  ReportReference,
  TableOfContents,
  TOCSection,
  TOCSubsection,
  TOCFigure,
  TOCTable,
  TOCAppendix,
  ReportContent,
  ContentBlock,
  BlockMetadata,
  BlockRelationship,
  ContentFormatting,
  FormattingSpacing,
  FormattingBorder,
  FormattingBackground,
  ContentMetadata
} from './structure';

// Export all types from styling module
export type {
  ReportStyling,
  ColorScheme,
  FontScheme,
  FontDefinition,
  LayoutScheme,
  LayoutMargins,
  LayoutColumns,
  LayoutSpacing,
  LayoutAlignment,
  SpacingScheme,
  ChartStyling,
  ChartColors,
  ChartFonts,
  ChartLayout,
  ChartLegend,
  LegendStyle,
  ChartAxes,
  AxisStyle,
  GridStyle,
  TickStyle
} from './styling';

// Export all types from distribution module
export type {
  ReportDistribution,
  DistributionChannel,
  ChannelConfiguration,
  ChannelSetting,
  ChannelAuth,
  ChannelFormat,
  ChannelLimit,
  ChannelRecipient,
  ChannelSecurity,
  ReportRecipient,
  RecipientPermission,
  RecipientPreference,
  DistributionSchedule,
  ScheduleTiming,
  ScheduleCondition,
  ScheduleAutomation,
  AutomationTrigger,
  AutomationAction,
  ActionParameter,
  ActionRetry,
  DistributionTracking,
  DeliveryTracking,
  AccessTracking,
  EngagementTracking,
  FeedbackTracking,
  InteractionEvent,
  FeedbackEvent,
  SharingEvent,
  RatingEvent,
  CommentEvent,
  SuggestionEvent,
  EventDetail,
  DistributionSecurity,
  SecurityEncryption,
  SecurityAccessControl,
  SecurityAudit,
  SecurityRetention,
  AuthMethod,
  AuthzMethod,
  PermissionModel,
  RetentionPolicy,
  DisposalMethod,
  AuthCredential
} from './distribution';