/**
 * Report Structure & Content Types
 *
 * Type definitions for report structure, sections, content blocks,
 * appendices, table of contents, and content management.
 *
 * Generated by CC - Claude Code
 */

import type { ConfigurationValue } from '../../../../shared/config-types';

// Report Structure Types
export interface ReportStructure {
  sections: ReportSection[];
  appendices: ReportAppendix[];
  glossary: ReportGlossary;
  references: ReportReference[];
  tableOfContents: TableOfContents;
}

export interface ReportSection {
  id: string;
  name: string;
  type: 'summary' | 'analysis' | 'details' | 'appendix';
  order: number;
  required: boolean;
  subsections: ReportSubsection[];
}

export interface ReportSubsection {
  id: string;
  name: string;
  content_type: string;
  required: boolean;
  order: number;
}

export interface ReportAppendix {
  id: string;
  name: string;
  type: 'data' | 'methodology' | 'references' | 'glossary';
  content: AppendixContent;
}

export interface AppendixContent {
  sections: AppendixSection[];
  references: string[];
  data_tables: string[];
}

export interface AppendixSection {
  name: string;
  content: string;
  type: string;
}

// Glossary and References
export interface ReportGlossary {
  terms: GlossaryTerm[];
  categories: string[];
  references: GlossaryReference[];
}

export interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
  synonyms: string[];
  references: string[];
}

export interface GlossaryReference {
  term: string;
  source: string;
  page: number;
  context: string;
}

export interface ReportReference {
  id: string;
  type: 'document' | 'website' | 'standard' | 'framework';
  citation: string;
  url?: string;
  accessed?: string;
}

// Table of Contents
export interface TableOfContents {
  sections: TOCSection[];
  figures: TOCFigure[];
  tables: TOCTable[];
  appendices: TOCAppendix[];
}

export interface TOCSection {
  name: string;
  page: number;
  level: number;
  subsections: TOCSubsection[];
}

export interface TOCSubsection {
  name: string;
  page: number;
  level: number;
}

export interface TOCFigure {
  name: string;
  page: number;
  section: string;
}

export interface TOCTable {
  name: string;
  page: number;
  section: string;
}

export interface TOCAppendix {
  name: string;
  page: number;
  type: string;
}

// Content Management Types
export interface ReportContent {
  sectionId: string;
  type: 'text' | 'table' | 'chart' | 'image' | 'list' | 'summary';
  content: ContentBlock;
  formatting: ContentFormatting;
  metadata: ContentMetadata;
}

export interface ContentBlock {
  type: string;
  data: Record<string, ConfigurationValue>;
  metadata: BlockMetadata;
  relationships: BlockRelationship[];
}

export interface BlockMetadata {
  id: string;
  type: string;
  source: string;
  generated: string;
  dependencies: string[];
}

export interface BlockRelationship {
  type: 'reference' | 'dependency' | 'sequence' | 'grouping';
  target: string;
  description: string;
}

export interface ContentFormatting {
  style: string;
  alignment: 'left' | 'center' | 'right' | 'justify';
  spacing: FormattingSpacing;
  borders: FormattingBorder[];
  background: FormattingBackground;
}

export interface FormattingSpacing {
  before: number;
  after: number;
  line_height: number;
  indent: number;
}

export interface FormattingBorder {
  side: 'top' | 'bottom' | 'left' | 'right' | 'all';
  style: 'solid' | 'dashed' | 'dotted';
  width: number;
  color: string;
}

export interface FormattingBackground {
  color: string;
  pattern: string;
  opacity: number;
}

export interface ContentMetadata {
  source: string;
  generated: string;
  updated: string;
  version: string;
  accuracy: number;
  completeness: number;
}
