/**
 * Plan Reporting Types
 * 
 * Type definitions for planning report generation, customization,
 * content management, styling, and distribution. Covers comprehensive
 * report structures, metadata, and generation workflows.
 * 
 * This module has been modularized into focused sub-modules for better
 * maintainability and organization.
 * 
 * Generated by CC - Claude Code
 */

// Re-export all types from the modular structure
export * from './reporting/index';