#!/bin/bash
# Script to check Railway logs for CORS-related messages

echo "Checking Railway logs for CORS configuration..."
echo ""
echo "If you have Railway CLI installed, run:"
echo "  railway logs | grep -i cors"
echo ""
echo "Or check the Railway dashboard:"
echo "  1. Go to https://railway.app"
echo "  2. Select your project"
echo "  3. Click on the latest deployment"
echo "  4. Click 'View Logs'"
echo "  5. Search for 'CORS'"
echo ""
echo "Look for these messages:"
echo "  - 'CORS origins collected: X unique origins'"
echo "  - 'CORS origins validated: X valid origins'"
echo "  - '✅ ai-stock-assess.vercel.app is in validated origins'"
echo "  - 'CORS origin allowed: https://ai-stock-assess.vercel.app'"
echo "  - '✅ CORS middleware added'"
echo ""
echo "If you see warnings like:"
echo "  - '⚠️ ai-stock-assess.vercel.app is NOT in validated origins'"
echo "Then there's an issue with the origin validation."
