/**
 * 6R Strategy Flow Integration Types
 * 
 * Integration configuration, custom rules, and endpoint types
 * for strategy flow management.
 * 
 * Generated by CC (Claude Code) - Modularized from flow-management.ts
 */

// Integration Configuration Types
export interface IntegrationConfig {
  type: 'ci_cd' | 'monitoring' | 'ticketing' | 'approval' | 'reporting';
  name: string;
  configuration: Record<string, any>;
  enabled: boolean;
  endpoints: IntegrationEndpoint[];
}

export interface IntegrationEndpoint {
  name: string;
  url: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  authentication: EndpointAuth;
  headers?: Record<string, string>;
}

export interface EndpointAuth {
  type: 'none' | 'basic' | 'bearer' | 'api_key' | 'oauth';
  credentials: Record<string, any>;
}

// Custom Rules and Validation
export interface CustomRule {
  id: string;
  name: string;
  type: 'validation' | 'approval' | 'routing' | 'escalation';
  condition: string;
  action: string;
  parameters: Record<string, any>;
  enabled: boolean;
}
