/**
 * Simple Discovery Flow Test
 * Focused test to verify the blocking flow handling works
 *
 * Generated by CC
 */

import { test, expect } from '@playwright/test';
import {
  login,
  ensureCleanUploadState,
  takeScreenshot,
  TEST_USERS,
  generateTestCSV
} from './helpers/test-helpers';
import * as path from 'path';
import * as fs from 'fs';

test.describe('Simple Discovery Flow Test', () => {
  let testDataFile: string;

  test.beforeAll(async () => {
    // Create test data file
    const testDir = path.join(process.cwd(), 'tests', 'e2e', 'test-data');
    if (!fs.existsSync(testDir)) {
      fs.mkdirSync(testDir, { recursive: true });
    }

    testDataFile = path.join(testDir, `simple-test-${Date.now()}.csv`);
    const csvData = generateTestCSV(5);
    fs.writeFileSync(testDataFile, csvData);
    console.log(`Created test data file: ${testDataFile}`);
  });

  test.afterAll(async () => {
    // Cleanup test data file
    if (fs.existsSync(testDataFile)) {
      fs.unlinkSync(testDataFile);
      console.log(`Cleaned up test data file: ${testDataFile}`);
    }
  });

  test('Can navigate to discovery and handle upload state', async ({ page }) => {
    console.log('\n=== SIMPLE DISCOVERY FLOW TEST ===');

    // Login
    await login(page, TEST_USERS.demo);
    await takeScreenshot(page, 'simple-login');
    console.log('✓ Logged in successfully');

    // Ensure clean upload state
    await ensureCleanUploadState(page);
    await takeScreenshot(page, 'simple-clean-upload-state');
    console.log('✓ Clean upload state ensured');

    // Verify upload area is accessible
    const fileInput = page.locator('input[type="file"]');
    const uploadArea = page.locator('.upload-area, .border-dashed');

    const hasFileInput = await fileInput.isVisible();
    const hasUploadArea = await uploadArea.isVisible();

    console.log(`File input visible: ${hasFileInput}`);
    console.log(`Upload area visible: ${hasUploadArea}`);

    expect(hasFileInput || hasUploadArea).toBeTruthy();
    console.log('✓ Upload functionality is accessible');

    // Check no blocking message exists
    const blockingMessage = page.locator('text="Upload Blocked"');
    const isBlocked = await blockingMessage.isVisible({ timeout: 2000 });

    console.log(`Upload blocked: ${isBlocked}`);
    expect(isBlocked).toBeFalsy();
    console.log('✓ No upload blocking detected');

    console.log('\n=== SIMPLE DISCOVERY FLOW TEST COMPLETED SUCCESSFULLY ===');
  });
});
