"""
Adaptive Form Service Configuration
"""

from .enums import FieldType

# Critical Attributes Framework (22 attributes as defined in specifications)
CRITICAL_ATTRIBUTES_CONFIG = {
    # Infrastructure Attributes (6)
    "os_version": {
        "category": "infrastructure",
        "weight": 0.05,
        "label": "Operating System & Version",
        "description": "Operating system type and version information",
        "field_type": FieldType.SELECT,
        "business_impact": "Required for compatibility assessment and migration strategy",
    },
    "specifications": {
        "category": "infrastructure",
        "weight": 0.05,
        "label": "CPU/Memory/Storage Specifications",
        "description": "Hardware specifications and resource requirements",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Required for rightsizing and cost optimization",
    },
    "network_config": {
        "category": "infrastructure",
        "weight": 0.04,
        "label": "Network Configuration",
        "description": "Network topology, ports, protocols, and connectivity requirements",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Required for connectivity planning and security assessment",
    },
    "virtualization": {
        "category": "infrastructure",
        "weight": 0.04,
        "label": "Virtualization Platform",
        "description": "Current virtualization technology and configuration",
        "field_type": FieldType.SELECT,
        "business_impact": "Required for migration strategy selection",
    },
    "performance_baseline": {
        "category": "infrastructure",
        "weight": 0.04,
        "label": "Performance Baseline",
        "description": "Current performance metrics and benchmarks",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Required for performance validation post-migration",
    },
    "availability_requirements": {
        "category": "infrastructure",
        "weight": 0.03,
        "label": "Availability/Uptime Requirements",
        "description": "SLA requirements and uptime expectations",
        "field_type": FieldType.SELECT,
        "business_impact": "Required for SLA planning and architecture decisions",
    },
    # Application Attributes (8)
    "technology_stack": {
        "category": "application",
        "weight": 0.08,
        "label": "Technology Stack",
        "description": "Programming languages, frameworks, runtime versions",
        "field_type": FieldType.MULTISELECT,
        "business_impact": "Critical for modernization path selection",
    },
    "architecture_pattern": {
        "category": "application",
        "weight": 0.07,
        "label": "Architecture Pattern",
        "description": "Application architecture classification",
        "field_type": FieldType.RADIO,
        "business_impact": "Determines refactoring vs replatforming approach",
    },
    "integration_dependencies": {
        "category": "application",
        "weight": 0.06,
        "label": "Integration Dependencies",
        "description": "External APIs, databases, message queues, and service dependencies",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Critical for dependency mapping and migration ordering",
    },
    "data_characteristics": {
        "category": "application",
        "weight": 0.06,
        "label": "Data Volume and Characteristics",
        "description": "Database size, file storage, data types, and growth patterns",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Required for storage planning and data migration strategy",
    },
    "user_load_patterns": {
        "category": "application",
        "weight": 0.05,
        "label": "User Load Patterns",
        "description": "Concurrent users, peak usage times, seasonal patterns",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Required for capacity planning and scaling strategy",
    },
    "business_logic_complexity": {
        "category": "application",
        "weight": 0.05,
        "label": "Custom Business Logic Complexity",
        "description": "Proprietary algorithms, complex business rules, custom workflows",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Determines refactoring effort and cloud-native potential",
    },
    "configuration_complexity": {
        "category": "application",
        "weight": 0.04,
        "label": "Configuration Complexity",
        "description": "Environment-specific settings, feature flags, deployment configurations",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Impacts containerization and automation potential",
    },
    "security_requirements": {
        "category": "application",
        "weight": 0.04,
        "label": "Security and Compliance Requirements",
        "description": "Security protocols, regulatory constraints, data protection requirements",
        "field_type": FieldType.MULTISELECT,
        "business_impact": "Determines cloud security posture and compliance validation",
    },
    # Business Context Attributes (4)
    "business_criticality": {
        "category": "business",
        "weight": 0.08,
        "label": "Business Criticality Score",
        "description": "Revenue impact, operational importance, and business dependency",
        "field_type": FieldType.SELECT,
        "business_impact": "Determines migration priority and risk tolerance",
    },
    "change_tolerance": {
        "category": "business",
        "weight": 0.05,
        "label": "Change Tolerance",
        "description": "User adaptability, training requirements, change management needs",
        "field_type": FieldType.SELECT,
        "business_impact": "Influences modernization approach and timeline",
    },
    "compliance_constraints": {
        "category": "business",
        "weight": 0.04,
        "label": "Compliance and Regulatory Constraints",
        "description": "Industry-specific requirements, regulatory compliance needs",
        "field_type": FieldType.MULTISELECT,
        "business_impact": "Determines cloud region and compliance validation requirements",
    },
    "stakeholder_impact": {
        "category": "business",
        "weight": 0.03,
        "label": "Stakeholder Impact Analysis",
        "description": "User base size, organizational dependencies, communication needs",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Influences change management and communication strategy",
    },
    # Technical Debt Attributes (4)
    "code_quality": {
        "category": "technical_debt",
        "weight": 0.03,
        "label": "Code Quality Metrics",
        "description": "Maintainability index, technical debt ratio, code coverage",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Determines refactoring effort and modernization feasibility",
    },
    "security_vulnerabilities": {
        "category": "technical_debt",
        "weight": 0.03,
        "label": "Security Vulnerability Assessment",
        "description": "CVE count, severity classification, security scan results",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Critical for security posture and remediation planning",
    },
    "eol_technology": {
        "category": "technical_debt",
        "weight": 0.02,
        "label": "End-of-Life Technology Assessment",
        "description": "Unsupported versions, deprecated features, legacy components",
        "field_type": FieldType.TEXTAREA,
        "business_impact": "Determines modernization urgency and approach",
    },
    "documentation_quality": {
        "category": "technical_debt",
        "weight": 0.02,
        "label": "Documentation Quality",
        "description": "Availability, accuracy, completeness of technical documentation",
        "field_type": FieldType.SELECT,
        "business_impact": "Impacts migration complexity and knowledge transfer needs",
    },
}

# Field options for common select/radio fields
FIELD_OPTIONS = {
    "os_version": [
        {"value": "windows_server_2019", "label": "Windows Server 2019"},
        {"value": "windows_server_2016", "label": "Windows Server 2016"},
        {"value": "windows_server_2012", "label": "Windows Server 2012"},
        {"value": "ubuntu_20.04", "label": "Ubuntu 20.04 LTS"},
        {"value": "ubuntu_18.04", "label": "Ubuntu 18.04 LTS"},
        {"value": "rhel_8", "label": "Red Hat Enterprise Linux 8"},
        {"value": "rhel_7", "label": "Red Hat Enterprise Linux 7"},
        {"value": "centos_8", "label": "CentOS 8"},
        {"value": "centos_7", "label": "CentOS 7"},
        {"value": "other", "label": "Other (specify in description)"},
    ],
    "virtualization": [
        {"value": "vmware_vsphere", "label": "VMware vSphere"},
        {"value": "hyper_v", "label": "Microsoft Hyper-V"},
        {"value": "kvm", "label": "KVM"},
        {"value": "xen", "label": "Citrix Xen"},
        {"value": "physical", "label": "Physical Server"},
        {"value": "cloud_vm", "label": "Cloud Virtual Machine"},
        {"value": "container", "label": "Containerized"},
        {"value": "other", "label": "Other"},
    ],
    "availability_requirements": [
        {"value": "99.99", "label": "99.99% (4 minutes downtime/month)"},
        {"value": "99.9", "label": "99.9% (43 minutes downtime/month)"},
        {"value": "99.5", "label": "99.5% (3.6 hours downtime/month)"},
        {"value": "99.0", "label": "99.0% (7.2 hours downtime/month)"},
        {"value": "95.0", "label": "95.0% (36 hours downtime/month)"},
        {"value": "best_effort", "label": "Best Effort (No SLA)"},
    ],
    "technology_stack": [
        {"value": "java", "label": "Java"},
        {"value": "dotnet", "label": ".NET Framework"},
        {"value": "dotnet_core", "label": ".NET Core"},
        {"value": "python", "label": "Python"},
        {"value": "nodejs", "label": "Node.js"},
        {"value": "php", "label": "PHP"},
        {"value": "ruby", "label": "Ruby"},
        {"value": "go", "label": "Go"},
        {"value": "rust", "label": "Rust"},
        {"value": "cpp", "label": "C++"},
        {"value": "oracle", "label": "Oracle Database"},
        {"value": "sql_server", "label": "SQL Server"},
        {"value": "mysql", "label": "MySQL"},
        {"value": "postgresql", "label": "PostgreSQL"},
        {"value": "mongodb", "label": "MongoDB"},
        {"value": "redis", "label": "Redis"},
        {"value": "elasticsearch", "label": "Elasticsearch"},
    ],
    "architecture_pattern": [
        {"value": "monolith", "label": "Monolithic Application"},
        {"value": "microservices", "label": "Microservices Architecture"},
        {"value": "soa", "label": "Service-Oriented Architecture (SOA)"},
        {"value": "layered", "label": "Layered/N-Tier Architecture"},
        {"value": "event_driven", "label": "Event-Driven Architecture"},
        {"value": "serverless", "label": "Serverless/Function-based"},
        {"value": "hybrid", "label": "Hybrid Architecture"},
    ],
    "business_criticality": [
        {
            "value": "mission_critical",
            "label": "Mission Critical (Revenue Generating)",
        },
        {
            "value": "business_critical",
            "label": "Business Critical (Operations Dependent)",
        },
        {"value": "important", "label": "Important (Business Supporting)"},
        {"value": "standard", "label": "Standard (Operational Support)"},
        {"value": "low", "label": "Low Priority (Development/Testing)"},
    ],
    "change_tolerance": [
        {
            "value": "high",
            "label": "High (Users adapt quickly, minimal training needed)",
        },
        {
            "value": "medium",
            "label": "Medium (Some training required, moderate adaptation)",
        },
        {
            "value": "low",
            "label": "Low (Significant training needed, resistance to change)",
        },
        {
            "value": "very_low",
            "label": "Very Low (Change averse, extensive change management)",
        },
    ],
    "security_requirements": [
        {"value": "pci_dss", "label": "PCI DSS"},
        {"value": "hipaa", "label": "HIPAA"},
        {"value": "sox", "label": "SOX"},
        {"value": "gdpr", "label": "GDPR"},
        {"value": "iso_27001", "label": "ISO 27001"},
        {"value": "fedramp", "label": "FedRAMP"},
        {"value": "pii", "label": "PII Data Protection"},
        {"value": "encryption_rest", "label": "Encryption at Rest"},
        {"value": "encryption_transit", "label": "Encryption in Transit"},
        {"value": "multi_factor_auth", "label": "Multi-Factor Authentication"},
    ],
    "compliance_constraints": [
        {"value": "healthcare", "label": "Healthcare (HIPAA, FDA)"},
        {"value": "financial", "label": "Financial Services (PCI DSS, SOX)"},
        {"value": "government", "label": "Government (FedRAMP, FISMA)"},
        {"value": "manufacturing", "label": "Manufacturing (ITAR, EAR)"},
        {"value": "retail", "label": "Retail (PCI DSS)"},
        {"value": "education", "label": "Education (FERPA)"},
        {"value": "data_residency", "label": "Data Residency Requirements"},
        {
            "value": "cross_border",
            "label": "Cross-Border Data Transfer Restrictions",
        },
    ],
    "documentation_quality": [
        {
            "value": "excellent",
            "label": "Excellent (Comprehensive, up-to-date, detailed)",
        },
        {"value": "good", "label": "Good (Mostly complete, minor gaps)"},
        {"value": "fair", "label": "Fair (Basic documentation, some outdated)"},
        {"value": "poor", "label": "Poor (Minimal documentation, mostly outdated)"},
        {"value": "none", "label": "None (No documentation available)"},
    ],
}
