/**
 * FinOps Report Generation Types
 * 
 * Report creation, formatting, distribution, security,
 * and lifecycle management types.
 * 
 * Generated by CC (Claude Code) - Modularized from analytics-reporting.ts
 */

import {
  BaseApiRequest,
  BaseApiResponse,
  MultiTenantContext
} from '../../shared';
import { CostAmount } from '../shared';
import type { ConfigurationValue } from '../../../shared/config-types';

// Report Generation API
export interface GenerateFinOpsReportRequest extends BaseApiRequest {
  flowId: string;
  reportType: 'cost_analysis' | 'budget_performance' | 'optimization' | 'governance' | 'executive';
  format: 'pdf' | 'html' | 'docx' | 'xlsx' | 'json';
  timeRange?: {
    start: string;
    end: string;
  };
  sections?: string[];
  currency?: string;
  customizations?: ReportCustomization;
  context: MultiTenantContext;
}

export interface GenerateFinOpsReportResponse extends BaseApiResponse<FinOpsReport> {
  data: FinOpsReport;
  reportId: string;
  downloadUrl: string;
  expiresAt: string;
}

// Core Report Structure
export interface FinOpsReport {
  id: string;
  reportId: string;
  flowId: string;
  type: string;
  format: string;
  title: string;
  description: string;
  timeRange: {
    start: string;
    end: string;
  };
  sections: ReportSection[];
  metadata: ReportMetadata;
  distribution: ReportDistribution;
  security: ReportSecurity;
  generatedAt: string;
  expiresAt: string;
}

export interface ReportSection {
  id: string;
  name: string;
  type: 'summary' | 'detailed' | 'chart' | 'table' | 'narrative';
  content: ReportContent;
  visualization: ReportVisualization;
  data: ReportData;
}

export interface ReportContent {
  title: string;
  summary: string;
  insights: string[];
  recommendations: string[];
  appendices: string[];
}

export interface ReportVisualization {
  type: 'chart' | 'table' | 'dashboard' | 'infographic';
  configuration: Record<string, string | number | boolean | null>;
  interactive: boolean;
  exportable: boolean;
}

export interface ReportData {
  source: string;
  freshness: string;
  filters: Record<string, string | number | boolean | null>;
  aggregations: Record<string, string | number | boolean | null>;
  calculations: Record<string, string | number | boolean | null>;
}

// Report Metadata and Management
export interface ReportMetadata {
  author: string;
  version: string;
  template: string;
  customizations: string[];
  tags: string[];
  approvals: ReportApproval[];
}

export interface ReportApproval {
  type: 'content' | 'data' | 'distribution';
  approver: string;
  status: 'pending' | 'approved' | 'rejected';
  timestamp: string;
  comments: string;
}

// Report Distribution and Access
export interface ReportDistribution {
  method: 'download' | 'email' | 'portal' | 'api';
  recipients: ReportRecipient[];
  schedule: ReportSchedule;
  access: ReportAccess;
}

export interface ReportRecipient {
  type: 'user' | 'group' | 'role' | 'external';
  identifier: string;
  format: string[];
  customizations: Record<string, string | number | boolean | null>;
}

export interface ReportSchedule {
  frequency: 'once' | 'daily' | 'weekly' | 'monthly' | 'quarterly';
  time: string;
  timezone: string;
  enabled: boolean;
}

export interface ReportAccess {
  level: 'public' | 'internal' | 'restricted' | 'confidential';
  permissions: string[];
  expiration: string;
  watermark: boolean;
}

// Report Security
export interface ReportSecurity {
  classification: 'public' | 'internal' | 'confidential' | 'restricted';
  encryption: boolean;
  accessLog: boolean;
  downloadTracking: boolean;
  sharing: ReportSharing;
}

export interface ReportSharing {
  allowed: boolean;
  restrictions: string[];
  tracking: boolean;
  expiration: string;
}

// Report Customization
export interface ReportCustomization {
  template: string;
  branding: BrandingCustomization;
  content: ContentCustomization;
  format: FormatCustomization;
  delivery: DeliveryCustomization;
}

export interface BrandingCustomization {
  logo: string;
  colors: Record<string, string>;
  fonts: Record<string, string>;
  watermark: string;
}

export interface ContentCustomization {
  sections: string[];
  metrics: string[];
  filters: Record<string, string | number | boolean | null>;
  aggregations: Record<string, string | number | boolean | null>;
}

export interface FormatCustomization {
  layout: string;
  pageSize: string;
  orientation: 'portrait' | 'landscape';
  charts: ChartCustomization[];
}

export interface ChartCustomization {
  type: string;
  configuration: Record<string, string | number | boolean | null>;
  position: string;
  size: string;
}

export interface DeliveryCustomization {
  method: string[];
  schedule: string;
  recipients: string[];
  notifications: boolean;
}

// Advanced Report Features
export interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  type: string;
  version: string;
  author: string;
  sections: TemplateSectionConfig[];
  styling: TemplateStyleConfig;
  variables: TemplateVariable[];
  validation: TemplateValidation[];
  preview: TemplatePreview;
  usage: TemplateUsage;
  lifecycle: TemplateLifecycle;
}

export interface TemplateSectionConfig {
  id: string;
  name: string;
  type: string;
  required: boolean;
  order: number;
  dependencies: string[];
  configuration: Record<string, string | number | boolean | null>;
  dataBindings: DataBinding[];
}

export interface DataBinding {
  field: string;
  source: string;
  transformation: string[];
  validation: string[];
  fallback: unknown;
}

export interface TemplateStyleConfig {
  theme: string;
  colors: Record<string, string>;
  fonts: FontConfig[];
  spacing: SpacingConfig;
  layout: LayoutConfig;
}

export interface FontConfig {
  family: string;
  sizes: Record<string, string>;
  weights: Record<string, string>;
  styles: string[];
}

export interface SpacingConfig {
  margins: Record<string, string>;
  padding: Record<string, string>;
  gaps: Record<string, string>;
}

export interface LayoutConfig {
  grid: GridConfig;
  breakpoints: Record<string, string>;
  containers: ContainerConfig[];
}

export interface GridConfig {
  columns: number;
  gutters: string;
  responsive: boolean;
}

export interface ContainerConfig {
  name: string;
  maxWidth: string;
  padding: string;
  alignment: 'left' | 'center' | 'right';
}

export interface TemplateVariable {
  name: string;
  type: 'string' | 'number' | 'date' | 'boolean' | 'array' | 'object';
  description: string;
  required: boolean;
  defaultValue: ConfigurationValue;
  validation: VariableValidation;
  options?: VariableOption[];
}

export interface VariableValidation {
  pattern?: string;
  min?: number;
  max?: number;
  enum?: string[];
  custom?: string;
}

export interface VariableOption {
  label: string;
  value: unknown;
  description?: string;
}

export interface TemplateValidation {
  rule: string;
  message: string;
  severity: 'error' | 'warning' | 'info';
  scope: 'template' | 'section' | 'data' | 'variable';
}

export interface TemplatePreview {
  thumbnail: string;
  screenshots: string[];
  sampleData: Record<string, string | number | boolean | null>;
  description: string;
}

export interface TemplateUsage {
  usageCount: number;
  lastUsed: string;
  popularSections: string[];
  commonCustomizations: Record<string, string | number | boolean | null>;
}

export interface TemplateLifecycle {
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
  deprecatedAt?: string;
  versions: TemplateVersion[];
}

export interface TemplateVersion {
  version: string;
  changes: string[];
  createdAt: string;
  author: string;
  compatibility: string[];
}

// Report Analytics and Insights
export interface ReportAnalytics {
  reportId: string;
  usage: ReportUsageAnalytics;
  performance: ReportPerformanceMetrics;
  engagement: ReportEngagementMetrics;
  feedback: ReportFeedback[];
  optimization: ReportOptimizationSuggestions;
}

export interface ReportUsageAnalytics {
  totalViews: number;
  uniqueViewers: number;
  downloads: number;
  shares: number;
  timeSpent: ReportTimeSpent;
  accessPatterns: AccessPattern[];
  popularSections: SectionPopularity[];
}

export interface ReportTimeSpent {
  average: number;
  median: number;
  distribution: Record<string, number>;
  trends: TimeSpentTrend[];
}

export interface TimeSpentTrend {
  period: string;
  averageTime: number;
  change: number;
}

export interface AccessPattern {
  hour: number;
  day: string;
  accessCount: number;
  userTypes: Record<string, number>;
}

export interface SectionPopularity {
  sectionId: string;
  viewCount: number;
  interactionCount: number;
  feedbackScore: number;
}

export interface ReportPerformanceMetrics {
  generationTime: number;
  fileSize: number;
  renderTime: number;
  errorRate: number;
  successRate: number;
  optimizationScore: number;
}

export interface ReportEngagementMetrics {
  clickThroughRate: number;
  bounceRate: number;
  completionRate: number;
  actionsTaken: ReportAction[];
  insights: EngagementInsight[];
}

export interface ReportAction {
  type: 'click' | 'download' | 'share' | 'bookmark' | 'comment' | 'export';
  count: number;
  uniqueUsers: number;
  conversionRate: number;
}

export interface EngagementInsight {
  type: 'high_engagement' | 'low_engagement' | 'drop_off' | 'popular_content';
  description: string;
  metrics: Record<string, number>;
  recommendations: string[];
}

export interface ReportFeedback {
  id: string;
  userId: string;
  rating: number;
  category: 'content' | 'design' | 'usability' | 'accuracy' | 'timeliness';
  comment: string;
  actionable: boolean;
  resolved: boolean;
  createdAt: string;
}

export interface ReportOptimizationSuggestions {
  performance: PerformanceOptimization[];
  content: ContentOptimization[];
  engagement: EngagementOptimization[];
  technical: TechnicalOptimization[];
}

export interface PerformanceOptimization {
  area: string;
  issue: string;
  impact: 'low' | 'medium' | 'high';
  solution: string;
  effort: 'low' | 'medium' | 'high';
  expectedImprovement: string;
}

export interface ContentOptimization {
  section: string;
  issue: string;
  suggestion: string;
  priority: 'low' | 'medium' | 'high';
  evidence: string[];
}

export interface EngagementOptimization {
  metric: string;
  currentValue: number;
  targetValue: number;
  strategies: EngagementStrategy[];
}

export interface EngagementStrategy {
  name: string;
  description: string;
  implementation: string[];
  expectedImpact: number;
  timeline: string;
}

export interface TechnicalOptimization {
  component: string;
  issue: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  solution: string;
  dependencies: string[];
  timeline: string;
}