/**
 * Decommission Data Migration Types
 * 
 * Types for data migration strategy, validation, tools, and transformation
 * during system decommissioning.
 * 
 * Generated by CC (Claude Code) - Modularized from decommission/index.ts
 */

// Data Migration Strategy Types
export interface DataMigrationStrategy {
  approach: 'extract_archive' | 'migrate_transform' | 'selective_migration' | 'real_time_sync';
  dataHandling: DataHandlingApproach[];
  migrationTools: MigrationTool[];
  validation: DataValidationStrategy;
  rollback: DataRollbackStrategy;
  timeline: DataMigrationTimeline;
}

export interface DataHandlingApproach {
  dataType: string;
  approach: 'migrate' | 'archive' | 'delete' | 'anonymize' | 'transform';
  destination: string;
  transformation: DataTransformation[];
  validation: string[];
  timeline: string;
}

// Data Transformation
export interface DataTransformation {
  type: 'format' | 'structure' | 'content' | 'anonymization';
  description: string;
  rules: TransformationRule[];
  validation: string[];
  reversible: boolean;
}

export interface TransformationRule {
  field: string;
  action: string;
  parameters: Record<string, unknown>;
  condition?: string;
}

// Migration Tools
export interface MigrationTool {
  name: string;
  type: 'etl' | 'replication' | 'custom' | 'manual';
  capabilities: string[];
  limitations: string[];
  configuration: Record<string, unknown>;
  performance: ToolPerformance;
}

export interface ToolPerformance {
  throughput: string;
  concurrency: number;
  reliability: number;
  scalability: string;
}

// Data Validation Strategy
export interface DataValidationStrategy {
  levels: ValidationLevel[];
  methods: ValidationMethod[];
  acceptance: AcceptanceCriteria[];
  reporting: ValidationReporting;
}

export interface ValidationLevel {
  level: 'record' | 'aggregate' | 'business_rule' | 'referential_integrity';
  coverage: number;
  sampling: SamplingStrategy;
  automation: boolean;
}

export interface SamplingStrategy {
  method: 'random' | 'systematic' | 'stratified' | 'complete';
  size: number;
  confidence: number;
}

export interface ValidationMethod {
  name: string;
  type: 'comparison' | 'checksum' | 'business_rule' | 'referential';
  automated: boolean;
  tools: string[];
  reporting: string;
}

export interface AcceptanceCriteria {
  metric: string;
  threshold: number;
  mandatory: boolean;
  measurement: string;
}

export interface ValidationReporting {
  frequency: string;
  recipients: string[];
  format: string;
  escalation: string[];
}

// Data Rollback Strategy
export interface DataRollbackStrategy {
  capability: 'full' | 'partial' | 'none';
  method: string[];
  timeline: string;
  triggers: string[];
  validation: string[];
  limitations: string[];
}

// Migration Timeline
export interface DataMigrationTimeline {
  preparation: string;
  extraction: string;
  transformation: string;
  loading: string;
  validation: string;
  cutover: string;
  total: string;
}

// Data Execution and Monitoring
export interface DataMigrationExecutionPlan {
  phases: DataMigrationPhase[];
  validation: DataValidationPlan;
  monitoring: DataMigrationMonitoring;
  rollback: DataMigrationRollback;
}

export interface DataMigrationPhase {
  id: string;
  name: string;
  type: 'extraction' | 'transformation' | 'loading' | 'validation';
  datasets: string[];
  duration: string;
  resources: string[];
  validation: string[];
  rollbackPoint: boolean;
}

export interface DataValidationPlan {
  phases: DataValidationPhase[];
  criteria: ValidationCriteria[];
  reporting: ValidationReporting;
}

export interface DataValidationPhase {
  phase: string;
  validations: DataValidation[];
  acceptance: AcceptanceCriteria[];
  timeline: string;
}

export interface DataValidation {
  type: 'completeness' | 'accuracy' | 'consistency' | 'integrity' | 'timeliness';
  description: string;
  scope: string[];
  method: string;
  acceptance: number;
  reporting: string;
}

export interface ValidationCriteria {
  criterion: string;
  measurement: string;
  threshold: number;
  mandatory: boolean;
  validation: string;
}

export interface DataMigrationMonitoring {
  metrics: DataMigrationMetric[];
  thresholds: DataMigrationThreshold[];
  alerts: DataMigrationAlert[];
  reporting: DataMigrationReporting;
}

export interface DataMigrationMetric {
  name: string;
  type: 'throughput' | 'quality' | 'performance' | 'error_rate';
  unit: string;
  collection: string;
  aggregation: string;
}

export interface DataMigrationThreshold {
  metric: string;
  warning: number;
  critical: number;
  action: string;
}

export interface DataMigrationAlert {
  condition: string;
  severity: 'info' | 'warning' | 'error' | 'critical';
  recipients: string[];
  actions: string[];
}

export interface DataMigrationReporting {
  frequency: string;
  recipients: string[];
  content: string[];
  format: string;
}

export interface DataMigrationRollback {
  triggers: string[];
  procedures: string[];
  timeline: string;
  validation: string[];
}

// Data Mapping and Planning
export interface DataMappingPlan {
  mappings: DataMapping[];
  transformations: DataTransformation[];
  validations: DataValidation[];
  dependencies: DataDependency[];
  timeline: DataMappingTimeline;
}

export interface DataMapping {
  sourceSystem: string;
  sourceData: string;
  targetSystem: string;
  targetData: string;
  mappingType: 'direct' | 'transformation' | 'aggregation' | 'split';
  transformation?: string;
  validation: string[];
}

export interface DataDependency {
  sourceData: string;
  dependentData: string;
  relationship: 'foreign_key' | 'lookup' | 'derivation' | 'aggregation';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  impact: string;
  resolution: string;
}

export interface DataMappingTimeline {
  analysis: string;
  mapping: string;
  validation: string;
  approval: string;
  total: string;
}

// Status and Monitoring Types
export interface DataMigrationStatus {
  overall: number;
  extraction: number;
  transformation: number;
  loading: number;
  validation: number;
  datasets: DatasetMigrationStatus[];
  issues: DataMigrationIssue[];
  metrics: DataMigrationMetrics;
}

export interface DatasetMigrationStatus {
  dataset: string;
  status: 'not_started' | 'extracting' | 'transforming' | 'loading' | 'validating' | 'completed' | 'failed';
  progress: number;
  recordsProcessed: number;
  recordsTotal: number;
  errors: number;
  lastUpdate: string;
}

export interface DataMigrationIssue {
  id: string;
  dataset: string;
  type: 'data_quality' | 'transformation_error' | 'validation_failure' | 'performance';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  count: number;
  resolution: string;
  status: 'open' | 'investigating' | 'resolved';
}

export interface DataMigrationMetrics {
  throughput: number;
  errorRate: number;
  dataQualityScore: number;
  validationScore: number;
  performanceMetrics: Record<string, number>;
}
