/**
 * Decommission Data Asset Types
 *
 * Type definitions for data assets, retention policies, privacy, and disposal.
 * Generated by CC (Claude Code) - Modularized from decommission/index.ts
 */

/**
 * Data asset to be decommissioned
 */
export interface DataAsset {
  id: string;
  name: string;
  type: 'database' | 'file' | 'stream' | 'api' | 'document';
  classification: 'public' | 'internal' | 'confidential' | 'restricted';
  size: number;
  format: string;
  location: string;
  owner: string;
  retention: DataRetentionPolicy;
  privacy: DataPrivacyRequirement;
  compliance: DataComplianceRequirement[];
  backups: BackupInfo[];
}

/**
 * Data retention policy for data assets
 */
export interface DataRetentionPolicy {
  period: string;
  reason: string;
  disposal: DataDisposalMethod;
  archival: DataArchivalRequirement;
  legalHold: boolean;
}

/**
 * Data disposal method configuration
 */
export interface DataDisposalMethod {
  method: 'delete' | 'anonymize' | 'archive' | 'transfer';
  certification: boolean;
  verification: string[];
  timeline: string;
}

/**
 * Data archival requirements
 */
export interface DataArchivalRequirement {
  required: boolean;
  location: string;
  format: string;
  encryption: boolean;
  accessControl: string[];
  retrieval: string;
}

/**
 * Data privacy requirements
 */
export interface DataPrivacyRequirement {
  pii: boolean;
  gdprApplicable: boolean;
  ccpaApplicable: boolean;
  anonymization: AnonymizationRequirement;
  consent: ConsentRequirement;
}

/**
 * Anonymization requirements
 */
export interface AnonymizationRequirement {
  required: boolean;
  method: 'deletion' | 'masking' | 'generalization' | 'suppression';
  fields: string[];
  validation: string[];
}

/**
 * Consent requirements for data handling
 */
export interface ConsentRequirement {
  required: boolean;
  withdrawalMethod: string;
  notificationRequired: boolean;
  gracePeriod: string;
}

/**
 * Data compliance requirements
 */
export interface DataComplianceRequirement {
  regulation: string;
  requirement: string;
  action: string;
  verification: string;
  deadline: string;
}

/**
 * Backup information for data assets
 */
export interface BackupInfo {
  location: string;
  frequency: string;
  retention: string;
  lastBackup: string;
  verified: boolean;
}
