/**
 * Decommission Risk Assessment Types
 *
 * Type definitions for comprehensive risk assessment.
 * Generated by CC (Claude Code) - Modularized from decommission/index.ts
 */

import type { RiskAssessment } from '../shared';

/**
 * Comprehensive decommission risk assessment
 */
export interface DecommissionRiskAssessment extends RiskAssessment {
  dataRisks: DataRisk[];
  systemRisks: SystemRisk[];
  businessRisks: BusinessRisk[];
  complianceRisks: ComplianceRisk[];
  operationalRisks: OperationalRisk[];
}

/**
 * Data-related risk
 */
export interface DataRisk {
  type: 'data_loss' | 'privacy_breach' | 'retention_violation' | 'corruption';
  description: string;
  likelihood: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  impact: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  affectedData: string[];
  mitigation: string;
  contingency: string;
}

/**
 * System-related risk
 */
export interface SystemRisk {
  type: 'dependency_failure' | 'integration_break' | 'performance_degradation' | 'rollback_failure';
  description: string;
  likelihood: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  impact: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  affectedSystems: string[];
  mitigation: string;
  contingency: string;
}

/**
 * Business-related risk
 */
export interface BusinessRisk {
  type: 'process_disruption' | 'revenue_loss' | 'customer_impact' | 'reputation_damage';
  description: string;
  likelihood: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  impact: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  affectedProcesses: string[];
  mitigation: string;
  contingency: string;
}

/**
 * Compliance-related risk
 */
export interface ComplianceRisk {
  type: 'regulatory_violation' | 'audit_failure' | 'data_breach' | 'retention_violation';
  description: string;
  likelihood: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  impact: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  regulations: string[];
  mitigation: string;
  contingency: string;
}

/**
 * Operational risk
 */
export interface OperationalRisk {
  type: 'resource_shortage' | 'skill_gap' | 'timeline_overrun' | 'budget_overrun';
  description: string;
  likelihood: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  impact: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  mitigation: string;
  contingency: string;
}

/**
 * Risk mitigation strategy
 */
export interface RiskMitigationStrategy {
  riskId: string;
  strategy: string;
  actions: string[];
  timeline: string;
  cost: number;
  effectiveness: number;
  owner: string;
  monitoring: string[];
  reporting: string;
}
