/**
 * Decommission Scope Types
 *
 * Type definitions for decommission scope and system inventory.
 * Generated by CC (Claude Code) - Modularized from decommission/index.ts
 */

import type { StrategyScope } from '../shared';
import type { DataAsset } from './data-assets';
import type { BusinessProcess } from './business-processes';
import type { SystemIntegration, SystemDependency } from './integrations';
import type { ComplianceScope } from './compliance';

/**
 * Scope of decommission activities
 */
export interface DecommissionScope extends StrategyScope {
  systemsToDecommission: SystemInventory[];
  dataAssets: DataAsset[];
  businessProcesses: BusinessProcess[];
  integrations: SystemIntegration[];
  dependencies: SystemDependency[];
  complianceScope: ComplianceScope[];
}

/**
 * System inventory item
 */
export interface SystemInventory {
  id: string;
  name: string;
  type: 'application' | 'database' | 'infrastructure' | 'service';
  criticality: 'low' | 'medium' | 'high' | 'critical';
  owner: string;
  location: string;
  environment: 'development' | 'testing' | 'staging' | 'production';
  status: 'active' | 'deprecated' | 'maintenance' | 'retired';
  dependencies: string[];
  dataStores: string[];
  integrations: string[];
  documentation: string[];
}
