/**
 * Decommission Status and Monitoring Types
 *
 * Types for tracking decommission status, progress monitoring, system status,
 * blockers, and next actions throughout the decommission lifecycle.
 *
 * Generated by CC (Claude Code) - Modularized from decommission/index.ts
 */

import type { StrategyFlowStatus } from '../shared';

// Core Status Types
export interface DecommissionStatusDetail {
  flowId: string;
  status: StrategyFlowStatus;
  progress: DecommissionProgress;
  currentPhase: string;
  phaseDetails: DecommissionPhaseDetail[];
  dataMigration: DataMigrationStatus;
  systemStatus: SystemDecommissionStatus[];
  risks: DecommissionRisk[];
  approvals: DecommissionApprovalStatus[];
  blockers: DecommissionBlocker[];
  nextActions: DecommissionNextAction[];
  lastUpdated: string;
}

// Progress Tracking
export interface DecommissionProgress {
  overall: number;
  planning: number;
  dataMigration: number;
  systemDecommission: number;
  validation: number;
  cleanup: number;
  milestones: DecommissionMilestoneStatus[];
}

export interface DecommissionMilestoneStatus {
  milestoneId: string;
  name: string;
  status: 'upcoming' | 'in_progress' | 'completed' | 'at_risk' | 'missed';
  dueDate: string;
  completion: number;
  blockers: string[];
}

// Phase Status Details
export interface DecommissionPhaseDetail {
  phaseId: string;
  name: string;
  status: 'not_started' | 'in_progress' | 'completed' | 'blocked' | 'at_risk';
  progress: number;
  activities: DecommissionActivityStatus[];
  deliverables: DecommissionDeliverableStatus[];
  issues: DecommissionIssue[];
}

export interface DecommissionActivityStatus {
  activityId: string;
  name: string;
  status: string;
  progress: number;
  assignee: string;
  dueDate: string;
  dependencies: string[];
  blockers: string[];
}

export interface DecommissionDeliverableStatus {
  name: string;
  status: 'not_started' | 'in_progress' | 'under_review' | 'approved' | 'rejected';
  dueDate: string;
  owner: string;
  approver?: string;
  quality: number;
}

export interface DecommissionIssue {
  id: string;
  type: 'blocker' | 'risk' | 'concern' | 'question';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  impact: string;
  owner: string;
  status: 'open' | 'investigating' | 'resolved' | 'escalated';
  createdAt: string;
  resolution?: string;
}

// Data Migration Status
export interface DataMigrationStatus {
  overall: number;
  extraction: number;
  transformation: number;
  loading: number;
  validation: number;
  datasets: DatasetMigrationStatus[];
  issues: DataMigrationIssue[];
  metrics: DataMigrationMetrics;
}

export interface DatasetMigrationStatus {
  dataset: string;
  status: 'not_started' | 'extracting' | 'transforming' | 'loading' | 'validating' | 'completed' | 'failed';
  progress: number;
  recordsProcessed: number;
  recordsTotal: number;
  errors: number;
  lastUpdate: string;
}

export interface DataMigrationIssue {
  id: string;
  dataset: string;
  type: 'data_quality' | 'transformation_error' | 'validation_failure' | 'performance';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  count: number;
  resolution: string;
  status: 'open' | 'investigating' | 'resolved';
}

export interface DataMigrationMetrics {
  throughput: number;
  errorRate: number;
  dataQualityScore: number;
  validationScore: number;
  performanceMetrics: Record<string, number>;
}

// System Decommission Status
export interface SystemDecommissionStatus {
  systemId: string;
  name: string;
  status: 'active' | 'draining' | 'offline' | 'decommissioned' | 'disposed';
  progress: number;
  activities: SystemDecommissionActivity[];
  dependencies: SystemDecommissionDependency[];
  lastUpdate: string;
}

export interface SystemDecommissionActivity {
  activity: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  startedAt?: string;
  completedAt?: string;
  errors: string[];
}

export interface SystemDecommissionDependency {
  system: string;
  status: 'resolved' | 'pending' | 'blocked';
  description: string;
  resolution?: string;
}

// Approval Status
export interface DecommissionApprovalStatus {
  approvalId: string;
  type: string;
  status: 'pending' | 'approved' | 'rejected' | 'conditional' | 'expired';
  approver: string;
  requestedAt: string;
  respondedAt?: string;
  conditions?: string[];
  comments?: string;
}

// Blockers and Next Actions
export interface DecommissionBlocker {
  id: string;
  type: 'dependency' | 'approval' | 'technical' | 'data' | 'compliance';
  description: string;
  impact: 'low' | 'medium' | 'high' | 'critical';
  owner: string;
  estimatedResolution: string;
  alternatives: string[];
  escalation: string[];
}

export interface DecommissionNextAction {
  id: string;
  type: 'task' | 'approval' | 'decision' | 'escalation';
  description: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  dueDate: string;
  assignee: string;
  dependencies: string[];
  blockers: string[];
}

// Analytics and Aggregation Types
export interface DecommissionAggregation {
  dimension: 'status' | 'approach' | 'system_type' | 'complexity' | 'risk_level';
  values: DecommissionAggregationValue[];
  total: number;
}

export interface DecommissionAggregationValue {
  key: string;
  count: number;
  percentage: number;
  avgDuration?: number;
  avgCost?: number;
  successRate?: number;
}

export interface DecommissionTrend {
  metric: 'volume' | 'duration' | 'cost' | 'success_rate' | 'complexity';
  period: 'daily' | 'weekly' | 'monthly' | 'quarterly';
  dataPoints: DecommissionTrendPoint[];
  forecast?: DecommissionTrendPoint[];
}

export interface DecommissionTrendPoint {
  period: string;
  value: number;
  change?: number;
  changePercentage?: number;
  events?: string[];
}

export interface DecommissionPortfolioMetrics {
  totalSystems: number;
  activeDecommissions: number;
  completedDecommissions: number;
  avgDecommissionTime: string;
  costSavings: number;
  riskReduction: number;
  complianceImprovement: number;
  dataDisposed: number;
  systemsRetired: number;
}

// Health and Quality Metrics
export interface DecommissionHealthMetrics {
  overallHealth: 'healthy' | 'at_risk' | 'critical';
  phaseHealth: PhaseHealthMetric[];
  qualityMetrics: DecommissionQualityMetrics;
  performanceMetrics: DecommissionPerformanceMetrics;
  complianceMetrics: DecommissionComplianceMetrics;
}

export interface PhaseHealthMetric {
  phase: string;
  health: 'healthy' | 'at_risk' | 'critical';
  indicators: HealthIndicator[];
  recommendations: string[];
}

export interface HealthIndicator {
  metric: string;
  value: number;
  threshold: number;
  status: 'good' | 'warning' | 'critical';
  trend: 'improving' | 'stable' | 'degrading';
}

export interface DecommissionQualityMetrics {
  dataQualityScore: number;
  processComplianceScore: number;
  documentationCompleteness: number;
  validationCoverage: number;
  defectRate: number;
  reworkRate: number;
}

export interface DecommissionPerformanceMetrics {
  throughputRate: number;
  cycleTime: string;
  leadTime: string;
  velocityTrend: string;
  resourceUtilization: number;
  costEfficiency: number;
}

export interface DecommissionComplianceMetrics {
  overallComplianceScore: number;
  regulatoryCompliance: RegulatoryComplianceScore[];
  auditReadiness: number;
  policyAdherence: number;
  riskMitigationEffectiveness: number;
}

export interface RegulatoryComplianceScore {
  regulation: string;
  score: number;
  requirements: ComplianceRequirementScore[];
  status: 'compliant' | 'at_risk' | 'non_compliant';
}

export interface ComplianceRequirementScore {
  requirement: string;
  score: number;
  evidence: string[];
  gaps: string[];
  actions: string[];
}

// Forward declarations for types from other modules
export interface DecommissionRisk {
  id: string;
  name: string;
  description: string;
  category: string;
  likelihood: string;
  impact: string;
  riskLevel: string;
  status: string;
}
