"""
Agent Communication Models
Data structures for agent-UI communication and interaction.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Any, Optional
from datetime import datetime

class QuestionType(Enum):
    """Types of questions agents can ask users."""
    FIELD_MAPPING = "field_mapping"
    DATA_CLASSIFICATION = "data_classification" 
    BUSINESS_CONTEXT = "business_context"
    QUALITY_VALIDATION = "quality_validation"
    DEPENDENCY_CLARIFICATION = "dependency_clarification"
    DEPENDENCY_VALIDATION = "dependency_validation"
    MIGRATION_PREFERENCE = "migration_preference"
    APPLICATION_BOUNDARY = "application_boundary"

class ConfidenceLevel(Enum):
    """Confidence levels for agent analysis and insights."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNCERTAIN = "uncertain"

class DataClassification(Enum):
    """Classification levels for data quality."""
    GOOD_DATA = "good_data"
    NEEDS_CLARIFICATION = "needs_clarification"
    UNUSABLE = "unusable"

@dataclass
class AgentQuestion:
    """Represents a question from an agent to the user."""
    id: str
    agent_id: str
    agent_name: str
    question_type: QuestionType
    page: str
    title: str
    question: str
    context: Dict[str, Any]
    options: Optional[List[str]] = None
    confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    priority: str = "medium"
    created_at: datetime = field(default_factory=datetime.utcnow)
    answered_at: Optional[datetime] = None
    user_response: Optional[Any] = None
    is_resolved: bool = False

@dataclass
class DataItem:
    """Represents a classified data item."""
    id: str
    data_type: str
    content: Dict[str, Any]
    classification: DataClassification
    agent_analysis: Dict[str, Any]
    confidence: ConfidenceLevel
    page: str
    issues: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None
    updated_by: Optional[str] = None

@dataclass
class AgentInsight:
    """Represents an insight generated by an agent."""
    id: str
    agent_id: str
    agent_name: str
    insight_type: str
    title: str
    description: str
    confidence: ConfidenceLevel
    supporting_data: Dict[str, Any]
    page: str
    actionable: bool = True
    # Client context fields for multi-tenancy
    client_account_id: Optional[str] = None
    engagement_id: Optional[str] = None
    flow_id: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    user_feedback: Optional[Dict[str, Any]] = None
    is_validated: bool = False 