/**
 * Governance Framework Types
 * 
 * Type definitions for governance frameworks, structures, processes,
 * compliance, and organizational oversight within execution planning.
 * 
 * Generated by CC - Claude Code
 */

export interface GovernanceFramework {
  model: 'centralized' | 'decentralized' | 'federated' | 'hybrid';
  structure: GovernanceStructure;
  bodies: GovernanceBody[];
  processes: GovernanceProcess[];
  policies: GovernancePolicy[];
  standards: GovernanceStandard[];
  roles: GovernanceRole[];
  responsibilities: GovernanceResponsibility[];
  authorities: GovernanceAuthority[];
  escalation: GovernanceEscalation[];
  reporting: GovernanceReporting;
  compliance: GovernanceCompliance;
  audit: GovernanceAudit;
  maturity: GovernanceMaturity;
  improvement: GovernanceImprovement;
}

export interface GovernanceStructure {
  hierarchy: GovernanceHierarchy;
  committees: GovernanceCommittee[];
  boards: GovernanceBoard[];
  councils: GovernanceCouncil[];
  offices: GovernanceOffice[];
  roles: GovernanceRole[];
  responsibilities: GovernanceResponsibility[];
  authorities: GovernanceAuthority[];
  relationships: GovernanceRelationship[];
  escalation: GovernanceEscalation[];
  communication: GovernanceCommunication;
}

export interface GovernanceHierarchy {
  levels: GovernanceLevel[];
  structure: HierarchyStructure;
  reporting: ReportingLine[];
  delegation: DelegationRule[];
  escalation: EscalationPath[];
  span: HierarchySpan;
  depth: number;
}

export interface GovernanceLevel {
  level: number;
  name: string;
  description: string;
  purpose: string;
  scope: string[];
  authority: LevelAuthority;
  responsibilities: string[];
  reporting: string;
  escalation: string;
}

export interface LevelAuthority {
  decision: DecisionAuthority[];
  approval: ApprovalAuthority[];
  oversight: OversightAuthority[];
  escalation: EscalationAuthority[];
}

export interface DecisionAuthority {
  category: string;
  scope: string[];
  limits: AuthorityLimit[];
  delegation: boolean;
  approval: string;
}

export interface ApprovalAuthority {
  type: string;
  scope: string[];
  limits: AuthorityLimit[];
  process: string;
  escalation: string;
}

export interface OversightAuthority {
  domain: string;
  scope: string[];
  frequency: string;
  reporting: string;
  escalation: string;
}

export interface EscalationAuthority {
  triggers: string[];
  scope: string[];
  process: string;
  timeline: string;
}

export interface AuthorityLimit {
  type: 'financial' | 'temporal' | 'scope' | 'resource' | 'risk';
  value: number;
  unit: string;
  conditions: string[];
  exceptions: string[];
}

export interface HierarchyStructure {
  type: 'matrix' | 'functional' | 'divisional' | 'network' | 'hybrid';
  principles: string[];
  design: StructureDesign;
  flexibility: StructureFlexibility;
  evolution: StructureEvolution;
}

export interface StructureDesign {
  criteria: string[];
  constraints: string[];
  optimization: string[];
  trade_offs: string[];
}

export interface StructureFlexibility {
  adaptability: string;
  reconfiguration: string;
  scaling: string;
  responsiveness: string;
}

export interface StructureEvolution {
  triggers: string[];
  process: string;
  criteria: string[];
  timeline: string;
}

export interface ReportingLine {
  from: string;
  to: string;
  type: 'direct' | 'dotted' | 'functional' | 'matrix';
  frequency: string;
  format: ReportingFormat;
  content: ReportingContent[];
  escalation: string;
}

export interface ReportingFormat {
  medium: 'written' | 'verbal' | 'dashboard' | 'presentation' | 'meeting';
  template: string;
  structure: string[];
  standards: string[];
}

export interface ReportingContent {
  category: string;
  elements: string[];
  metrics: string[];
  frequency: string;
  detail: 'summary' | 'detailed' | 'exception';
}

export interface DelegationRule {
  authority: string;
  from: string;
  to: string;
  scope: string[];
  conditions: DelegationCondition[];
  limits: AuthorityLimit[];
  accountability: string;
  monitoring: string;
}

export interface DelegationCondition {
  condition: string;
  requirement: string;
  validation: string;
  monitoring: string;
}

export interface EscalationPath {
  id: string;
  trigger: EscalationTrigger;
  levels: EscalationLevel[];
  timeline: EscalationTimeline;
  process: EscalationProcess;
  resolution: EscalationResolution;
  communication: EscalationCommunication;
}

export interface EscalationTrigger {
  type: 'automatic' | 'manual' | 'threshold' | 'time_based';
  conditions: TriggerCondition[];
  indicators: TriggerIndicator[];
  rules: TriggerRule[];
}

export interface TriggerCondition {
  condition: string;
  threshold: number;
  measurement: string;
  frequency: string;
}

export interface TriggerIndicator {
  indicator: string;
  measurement: string;
  threshold: number;
  trend: boolean;
}

export interface TriggerRule {
  rule: string;
  logic: string;
  conditions: string[];
  actions: string[];
}

export interface EscalationLevel {
  level: number;
  role: string;
  authority: string[];
  responsibilities: string[];
  timeline: string;
  actions: LevelAction[];
  escalation: string;
}

export interface LevelAction {
  action: string;
  authority: string;
  timeline: string;
  resources: string[];
  communication: string;
}

export interface EscalationTimeline {
  initial: string;
  levels: LevelTimeline[];
  maximum: string;
  extensions: string[];
}

export interface LevelTimeline {
  level: number;
  duration: string;
  conditions: string[];
  extensions: string[];
}

export interface EscalationProcess {
  initiation: ProcessStep[];
  assessment: ProcessStep[];
  decision: ProcessStep[];
  communication: ProcessStep[];
  resolution: ProcessStep[];
  follow_up: ProcessStep[];
}

export interface ProcessStep {
  step: string;
  description: string;
  inputs: string[];
  activities: string[];
  outputs: string[];
  roles: string[];
  timeline: string;
  criteria: string[];
}

export interface EscalationResolution {
  options: ResolutionOption[];
  criteria: ResolutionCriteria[];
  process: string;
  authority: string;
  communication: string;
  follow_up: string;
}

export interface ResolutionOption {
  option: string;
  description: string;
  conditions: string[];
  authority: string;
  timeline: string;
  resources: string[];
}

export interface ResolutionCriteria {
  criteria: string;
  measurement: string;
  threshold: number;
  validation: string;
}

export interface EscalationCommunication {
  stakeholders: string[];
  channels: string[];
  frequency: string;
  content: string[];
  feedback: string;
}

export interface HierarchySpan {
  control: number;
  management: number;
  coordination: number;
  communication: number;
}

export interface GovernanceCommittee {
  id: string;
  name: string;
  purpose: string;
  charter: CommitteeCharter;
  membership: CommitteeMembership;
  meetings: CommitteeMeeting[];
  decisions: CommitteeDecision[];
  reporting: CommitteeReporting;
  effectiveness: CommitteeEffectiveness;
  evolution: CommitteeEvolution;
}

export interface CommitteeCharter {
  purpose: string;
  scope: string[];
  authority: CommitteeAuthority;
  responsibilities: string[];
  objectives: string[];
  success: string[];
  constraints: string[];
  review: string;
}

export interface CommitteeAuthority {
  decision: string[];
  approval: string[];
  oversight: string[];
  advisory: string[];
  escalation: string[];
}

export interface CommitteeMembership {
  composition: MembershipComposition;
  roles: MembershipRole[];
  selection: MembershipSelection;
  tenure: MembershipTenure;
  rotation: MembershipRotation;
}

export interface MembershipComposition {
  size: number;
  structure: string;
  representation: string[];
  diversity: string[];
  balance: string[];
}

export interface MembershipRole {
  role: string;
  responsibilities: string[];
  authority: string[];
  commitment: string;
  qualifications: string[];
}

export interface MembershipSelection {
  process: string;
  criteria: string[];
  approval: string;
  timeline: string;
  communication: string;
}

export interface MembershipTenure {
  duration: string;
  renewal: string;
  evaluation: string;
  succession: string;
}

export interface MembershipRotation {
  policy: string;
  frequency: string;
  overlap: string;
  knowledge: string;
}

export interface CommitteeMeeting {
  frequency: string;
  duration: string;
  agenda: MeetingAgenda;
  process: MeetingProcess;
  participation: MeetingParticipation;
  documentation: MeetingDocumentation;
  follow_up: MeetingFollowUp;
}

export interface MeetingAgenda {
  structure: string[];
  preparation: string;
  materials: string[];
  timing: string;
  flexibility: string;
}

export interface MeetingProcess {
  facilitation: string;
  decision: string;
  discussion: string;
  consensus: string;
  voting: string;
}

export interface MeetingParticipation {
  quorum: string;
  attendance: string;
  engagement: string;
  contribution: string;
  behavior: string;
}

export interface MeetingDocumentation {
  minutes: string;
  decisions: string;
  actions: string;
  distribution: string;
  retention: string;
}

export interface MeetingFollowUp {
  actions: string;
  tracking: string;
  reporting: string;
  escalation: string;
  closure: string;
}

export interface CommitteeDecision {
  id: string;
  type: string;
  description: string;
  rationale: string;
  process: DecisionProcess;
  stakeholders: string[];
  implementation: DecisionImplementation;
  monitoring: DecisionMonitoring;
  review: DecisionReview;
}

export interface DecisionProcess {
  method: 'consensus' | 'majority' | 'unanimous' | 'chair' | 'delegated';
  criteria: string[];
  information: string[];
  consultation: string[];
  deliberation: string;
  documentation: string;
}

export interface DecisionImplementation {
  plan: string;
  responsibilities: string[];
  timeline: string;
  resources: string[];
  communication: string;
  monitoring: string;
}

export interface DecisionMonitoring {
  metrics: string[];
  frequency: string;
  reporting: string;
  review: string;
  adjustment: string;
}

export interface DecisionReview {
  frequency: string;
  criteria: string[];
  process: string;
  stakeholders: string[];
  outcomes: string[];
}

export interface CommitteeReporting {
  frequency: string;
  recipients: string[];
  format: string;
  content: string[];
  escalation: string[];
  feedback: string;
}

export interface CommitteeEffectiveness {
  measurement: EffectivenessMeasurement;
  evaluation: EffectivenessEvaluation;
  improvement: EffectivenessImprovement;
  benchmarking: EffectivenessBenchmarking;
}

export interface EffectivenessMeasurement {
  metrics: EffectivenessMetric[];
  methods: string[];
  frequency: string;
  reporting: string;
}

export interface EffectivenessMetric {
  metric: string;
  description: string;
  calculation: string;
  target: number;
  frequency: string;
}

export interface EffectivenessEvaluation {
  process: string;
  criteria: string[];
  stakeholders: string[];
  frequency: string;
  methods: string[];
}

export interface EffectivenessImprovement {
  process: string;
  triggers: string[];
  actions: string[];
  implementation: string;
  monitoring: string;
}

export interface EffectivenessBenchmarking {
  standards: string[];
  peers: string[];
  practices: string[];
  assessment: string;
  adoption: string;
}

export interface CommitteeEvolution {
  review: string;
  adaptation: string;
  restructuring: string;
  dissolution: string;
  succession: string;
}

export interface GovernanceBoard {
  id: string;
  name: string;
  purpose: string;
  charter: BoardCharter;
  composition: BoardComposition;
  meetings: BoardMeeting[];
  decisions: BoardDecision[];
  oversight: BoardOversight;
  reporting: BoardReporting;
  performance: BoardPerformance;
}

export interface BoardCharter {
  mission: string;
  vision: string;
  values: string[];
  scope: string[];
  authority: BoardAuthority;
  responsibilities: string[];
  structure: string;
  review: string;
}

export interface BoardAuthority {
  strategic: string[];
  operational: string[];
  financial: string[];
  risk: string[];
  compliance: string[];
}

export interface BoardComposition {
  size: number;
  structure: string;
  independence: string;
  diversity: string[];
  skills: string[];
  experience: string[];
}

export interface BoardMeeting {
  frequency: string;
  duration: string;
  schedule: string;
  agenda: string;
  materials: string;
  process: string;
}

export interface BoardDecision {
  authority: string[];
  process: string;
  delegation: string;
  documentation: string;
  communication: string;
}

export interface BoardOversight {
  areas: string[];
  mechanisms: string[];
  frequency: string;
  reporting: string;
  escalation: string;
}

export interface BoardReporting {
  internal: InternalReporting;
  external: ExternalReporting;
  stakeholder: StakeholderReporting;
  regulatory: RegulatoryReporting;
}

export interface InternalReporting {
  frequency: string;
  content: string[];
  recipients: string[];
  format: string;
}

export interface ExternalReporting {
  frequency: string;
  content: string[];
  recipients: string[];
  compliance: string[];
}

export interface StakeholderReporting {
  stakeholders: string[];
  frequency: string;
  methods: string[];
  content: string[];
}

export interface RegulatoryReporting {
  requirements: string[];
  frequency: string;
  format: string[];
  compliance: string;
}

export interface BoardPerformance {
  evaluation: PerformanceEvaluation;
  development: PerformanceDevelopment;
  succession: PerformanceSuccession;
}

export interface PerformanceEvaluation {
  frequency: string;
  methods: string[];
  criteria: string[];
  feedback: string;
  improvement: string;
}

export interface PerformanceDevelopment {
  programs: string[];
  resources: string[];
  support: string[];
  assessment: string;
}

export interface PerformanceSuccession {
  planning: string;
  identification: string;
  development: string;
  transition: string;
}

export interface GovernanceCouncil {
  id: string;
  name: string;
  purpose: string;
  charter: CouncilCharter;
  membership: CouncilMembership;
  coordination: CouncilCoordination;
  standards: CouncilStandard[];
  guidance: CouncilGuidance[];
  collaboration: CouncilCollaboration;
}

export interface CouncilCharter {
  mission: string;
  scope: string[];
  objectives: string[];
  authority: string[];
  coordination: string;
  standards: string;
}

export interface CouncilMembership {
  representation: string[];
  selection: string;
  tenure: string;
  rotation: string;
  participation: string;
}

export interface CouncilCoordination {
  mechanisms: string[];
  frequency: string;
  forums: string[];
  communication: string;
  alignment: string;
}

export interface CouncilStandard {
  id: string;
  name: string;
  description: string;
  scope: string[];
  requirements: string[];
  compliance: string;
}

export interface CouncilGuidance {
  id: string;
  topic: string;
  description: string;
  principles: string[];
  practices: string[];
  examples: string[];
}

export interface CouncilCollaboration {
  forums: string[];
  networks: string[];
  communities: string[];
  knowledge: string;
  innovation: string;
}

export interface GovernanceOffice {
  id: string;
  name: string;
  type: 'pmo' | 'coe' | 'shared_service' | 'support' | 'coordination';
  purpose: string;
  services: OfficeService[];
  capabilities: OfficeCapability[];
  resources: OfficeResource[];
  performance: OfficePerformance;
  evolution: OfficeEvolution;
}

export interface OfficeService {
  service: string;
  description: string;
  scope: string[];
  delivery: ServiceDelivery;
  quality: ServiceQuality;
  performance: ServicePerformance;
}

export interface ServiceDelivery {
  model: string;
  channels: string[];
  processes: string[];
  standards: string[];
  automation: string;
}

export interface ServiceQuality {
  framework: string;
  standards: string[];
  metrics: string[];
  monitoring: string;
  improvement: string;
}

export interface ServicePerformance {
  metrics: string[];
  targets: string[];
  monitoring: string;
  reporting: string;
  optimization: string;
}

export interface OfficeCapability {
  capability: string;
  description: string;
  maturity: CapabilityMaturity;
  development: CapabilityDevelopment;
  utilization: CapabilityUtilization;
}

export interface CapabilityMaturity {
  current: 'initial' | 'developing' | 'defined' | 'managed' | 'optimizing';
  target: 'initial' | 'developing' | 'defined' | 'managed' | 'optimizing';
  gap: string[];
  roadmap: string;
}

export interface CapabilityDevelopment {
  approach: string;
  investments: string[];
  timeline: string;
  resources: string[];
  partnerships: string[];
}

export interface CapabilityUtilization {
  demand: string;
  capacity: string;
  allocation: string;
  optimization: string;
  scaling: string;
}

export interface OfficeResource {
  type: 'human' | 'technology' | 'financial' | 'physical';
  description: string;
  allocation: ResourceAllocation;
  utilization: ResourceUtilization;
  optimization: ResourceOptimization;
}

export interface ResourceAllocation {
  current: string;
  planned: string;
  demand: string;
  gaps: string[];
  conflicts: string[];
}

export interface ResourceUtilization {
  rate: number;
  trends: string[];
  efficiency: string;
  capacity: string;
  bottlenecks: string[];
}

export interface ResourceOptimization {
  opportunities: string[];
  initiatives: string[];
  benefits: string[];
  implementation: string;
  monitoring: string;
}

export interface OfficePerformance {
  framework: PerformanceFramework;
  measurement: PerformanceMeasurement;
  reporting: PerformanceReporting;
  improvement: PerformanceImprovement;
}

export interface PerformanceFramework {
  model: string;
  dimensions: string[];
  metrics: string[];
  targets: string[];
  benchmarks: string[];
}

export interface PerformanceMeasurement {
  methods: string[];
  frequency: string;
  automation: string;
  validation: string;
  analysis: string;
}

export interface PerformanceReporting {
  dashboards: string[];
  reports: string[];
  frequency: string;
  audience: string[];
  escalation: string;
}

export interface PerformanceImprovement {
  process: string;
  triggers: string[];
  methods: string[];
  implementation: string;
  monitoring: string;
}

export interface OfficeEvolution {
  strategy: string;
  roadmap: string;
  transformation: string;
  innovation: string;
  sustainability: string;
}

export interface GovernanceRole {
  role: string;
  level: string;
  scope: string[];
  responsibilities: string[];
  authorities: string[];
  accountabilities: string[];
  competencies: string[];
  reporting: string;
  performance: RolePerformance;
  development: RoleDevelopment;
}

export interface RolePerformance {
  expectations: string[];
  metrics: string[];
  evaluation: string;
  feedback: string;
  recognition: string;
}

export interface RoleDevelopment {
  requirements: string[];
  training: string[];
  mentoring: string;
  career: string;
  succession: string;
}

export interface GovernanceResponsibility {
  responsibility: string;
  description: string;
  scope: string;
  owner: string;
  authority: string;
  measurement: string;
  escalation: string;
  delegation: ResponsibilityDelegation;
}

export interface ResponsibilityDelegation {
  allowed: boolean;
  conditions: string[];
  process: string;
  accountability: string;
  monitoring: string;
}

export interface GovernanceAuthority {
  authority: string;
  scope: string[];
  limits: AuthorityLimit[];
  delegation: AuthorityDelegation[];
  approval: AuthorityApproval[];
  reporting: AuthorityReporting;
  review: AuthorityReview;
}

export interface AuthorityDelegation {
  to: string;
  scope: string[];
  conditions: string[];
  accountability: string;
  monitoring: string;
  review: string;
}

export interface AuthorityApproval {
  type: string;
  process: string;
  criteria: string[];
  documentation: string;
  review: string;
}

export interface AuthorityReporting {
  frequency: string;
  content: string[];
  recipients: string[];
  escalation: string;
}

export interface AuthorityReview {
  frequency: string;
  criteria: string[];
  process: string;
  adjustment: string;
}

export interface GovernanceRelationship {
  from: string;
  to: string;
  type: 'reporting' | 'coordination' | 'collaboration' | 'escalation' | 'consultation';
  frequency: string;
  format: string;
  content: string[];
  governance: RelationshipGovernance;
}

export interface RelationshipGovernance {
  charter: string;
  protocols: string[];
  escalation: string;
  review: string;
  evolution: string;
}

export interface GovernanceEscalation {
  level: number;
  trigger: EscalationTrigger;
  path: EscalationPath;
  timeline: EscalationTimeline;
  process: EscalationProcess;
  resolution: EscalationResolution;
}

export interface GovernanceCommunication {
  strategy: CommunicationStrategy;
  channels: CommunicationChannel[];
  protocols: CommunicationProtocol[];
  stakeholders: CommunicationStakeholder[];
  feedback: CommunicationFeedback;
}

export interface CommunicationStrategy {
  objectives: string[];
  principles: string[];
  approach: string;
  measurement: string;
}

export interface CommunicationChannel {
  channel: string;
  purpose: string;
  audience: string[];
  frequency: string;
  format: string;
}

export interface CommunicationProtocol {
  protocol: string;
  purpose: string;
  rules: string[];
  procedures: string[];
  escalation: string;
}

export interface CommunicationStakeholder {
  stakeholder: string;
  interest: string;
  influence: string;
  preferences: string[];
  requirements: string[];
}

export interface CommunicationFeedback {
  mechanisms: string[];
  processing: string;
  response: string;
  improvement: string;
}

export interface GovernanceBody {
  id: string;
  name: string;
  type: 'committee' | 'board' | 'council' | 'office' | 'forum' | 'working_group';
  purpose: string;
  charter: BodyCharter;
  membership: BodyMembership;
  authority: BodyAuthority;
  responsibilities: BodyResponsibility[];
  processes: BodyProcess[];
  performance: BodyPerformance;
}

export interface BodyCharter {
  mission: string;
  scope: string[];
  authority: string[];
  objectives: string[];
  success: string[];
  review: string;
}

export interface BodyMembership {
  composition: string;
  selection: string;
  tenure: string;
  roles: string[];
  development: string;
}

export interface BodyAuthority {
  decision: string[];
  approval: string[];
  oversight: string[];
  advisory: string[];
  escalation: string[];
}

export interface BodyResponsibility {
  responsibility: string;
  description: string;
  authority: string;
  measurement: string;
  reporting: string;
}

export interface BodyProcess {
  process: string;
  purpose: string;
  steps: string[];
  roles: string[];
  governance: string;
}

export interface BodyPerformance {
  metrics: string[];
  evaluation: string;
  improvement: string;
  reporting: string;
}

export interface GovernanceProcess {
  id: string;
  name: string;
  description: string;
  purpose: string;
  scope: string;
  inputs: ProcessInput[];
  activities: ProcessActivity[];
  outputs: ProcessOutput[];
  roles: ProcessRole[];
  controls: ProcessControl[];
  metrics: ProcessMetric[];
  governance: ProcessGovernance;
}

export interface ProcessInput {
  input: string;
  description: string;
  source: string;
  format: string;
  quality: string;
  timing: string;
}

export interface ProcessActivity {
  activity: string;
  description: string;
  type: string;
  sequence: number;
  inputs: string[];
  outputs: string[];
  roles: string[];
  controls: string[];
  duration: string;
}

export interface ProcessOutput {
  output: string;
  description: string;
  format: string;
  quality: string;
  recipients: string[];
  timing: string;
}

export interface ProcessRole {
  role: string;
  responsibilities: string[];
  authority: string[];
  competencies: string[];
  training: string[];
}

export interface ProcessControl {
  control: string;
  type: 'preventive' | 'detective' | 'corrective';
  description: string;
  implementation: string;
  monitoring: string;
  effectiveness: string;
}

export interface ProcessMetric {
  metric: string;
  description: string;
  calculation: string;
  target: number;
  frequency: string;
  owner: string;
}

export interface ProcessGovernance {
  ownership: string;
  oversight: string;
  review: string;
  improvement: string;
  compliance: string;
}

export interface GovernancePolicy {
  id: string;
  name: string;
  description: string;
  scope: string;
  principles: string[];
  rules: PolicyRule[];
  procedures: PolicyProcedure[];
  compliance: PolicyCompliance;
  enforcement: PolicyEnforcement;
  lifecycle: PolicyLifecycle;
}

export interface PolicyRule {
  rule: string;
  description: string;
  applicability: string[];
  exceptions: PolicyException[];
  enforcement: string;
  penalties: string[];
}

export interface PolicyException {
  exception: string;
  conditions: string[];
  approval: string;
  documentation: string;
  review: string;
}

export interface PolicyProcedure {
  procedure: string;
  description: string;
  steps: ProcedureStep[];
  roles: string[];
  controls: string[];
  documentation: string;
}

export interface ProcedureStep {
  step: string;
  description: string;
  inputs: string[];
  activities: string[];
  outputs: string[];
  roles: string[];
  controls: string[];
}

export interface PolicyCompliance {
  requirements: ComplianceRequirement[];
  monitoring: ComplianceMonitoring;
  assessment: ComplianceAssessment;
  reporting: ComplianceReporting;
  violations: ComplianceViolation[];
  remediation: ComplianceRemediation;
}

export interface ComplianceRequirement {
  requirement: string;
  description: string;
  applicability: string[];
  evidence: string[];
  frequency: string;
  owner: string;
}

export interface ComplianceMonitoring {
  approach: string;
  methods: string[];
  frequency: string;
  automation: string;
  reporting: string;
}

export interface ComplianceAssessment {
  approach: string;
  criteria: string[];
  methods: string[];
  frequency: string;
  independence: string;
}

export interface ComplianceReporting {
  frequency: string;
  recipients: string[];
  format: string[];
  escalation: string;
  retention: string;
}

export interface ComplianceViolation {
  id: string;
  type: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  impact: string;
  root_cause: string;
  remediation: string;
  prevention: string;
}

export interface ComplianceRemediation {
  process: string;
  timeline: string;
  resources: string[];
  monitoring: string;
  validation: string;
}

export interface PolicyEnforcement {
  mechanisms: string[];
  roles: string[];
  procedures: string[];
  escalation: string;
  appeals: string;
}

export interface PolicyLifecycle {
  development: string;
  approval: string;
  communication: string;
  implementation: string;
  monitoring: string;
  review: string;
  retirement: string;
}

export interface GovernanceStandard {
  id: string;
  name: string;
  description: string;
  scope: string;
  requirements: StandardRequirement[];
  guidelines: StandardGuideline[];
  compliance: StandardCompliance;
  certification: StandardCertification;
  lifecycle: StandardLifecycle;
}

export interface StandardRequirement {
  requirement: string;
  description: string;
  rationale: string;
  applicability: string[];
  evidence: string[];
  validation: string;
}

export interface StandardGuideline {
  guideline: string;
  description: string;
  recommendations: string[];
  examples: string[];
  tools: string[];
}

export interface StandardCompliance {
  assessment: string;
  frequency: string;
  methods: string[];
  certification: string;
  monitoring: string;
}

export interface StandardCertification {
  process: string;
  criteria: string[];
  validity: string;
  renewal: string;
  maintenance: string;
}

export interface StandardLifecycle {
  development: string;
  review: string;
  update: string;
  retirement: string;
  versioning: string;
}

export interface GovernanceReporting {
  structure: ReportingStructure;
  schedules: ReportingSchedule[];
  formats: ReportingFormat[];
  content: ReportingContent[];
  distribution: ReportingDistribution[];
  escalation: ReportingEscalation;
  quality: ReportingQuality;
}

export interface ReportingStructure {
  hierarchy: string[];
  relationships: string[];
  consolidation: string;
  integration: string;
}

export interface ReportingSchedule {
  type: string;
  frequency: string;
  timing: string;
  recipients: string[];
  dependencies: string[];
}

export interface ReportingDistribution {
  recipients: string[];
  channels: string[];
  format: string;
  timing: string;
  access: string[];
}

export interface ReportingEscalation {
  triggers: string[];
  process: string;
  timeline: string;
  recipients: string[];
}

export interface ReportingQuality {
  standards: string[];
  validation: string;
  accuracy: string;
  timeliness: string;
  completeness: string;
}

export interface GovernanceCompliance {
  requirements: ComplianceRequirement[];
  monitoring: ComplianceMonitoring;
  assessment: ComplianceAssessment;
  reporting: ComplianceReporting;
  violations: ComplianceViolation[];
  remediation: ComplianceRemediation;
}

export interface GovernanceAudit {
  framework: AuditFramework;
  schedule: AuditSchedule;
  scope: AuditScope;
  methodology: AuditMethodology;
  findings: AuditFinding[];
  recommendations: AuditRecommendation[];
  follow_up: AuditFollowUp;
  independence: AuditIndependence;
}

export interface AuditFramework {
  standards: string[];
  approach: string;
  methodology: string;
  quality: string;
  independence: string;
}

export interface AuditSchedule {
  frequency: string;
  timing: string;
  scope: string[];
  resources: string[];
  coordination: string;
}

export interface AuditScope {
  areas: string[];
  processes: string[];
  risks: string[];
  controls: string[];
  exclusions: string[];
}

export interface AuditMethodology {
  approach: string;
  techniques: string[];
  sampling: string;
  testing: string;
  documentation: string;
}

export interface AuditFinding {
  id: string;
  type: 'observation' | 'deficiency' | 'non_compliance' | 'best_practice';
  severity: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  evidence: string[];
  impact: string;
  recommendation: string;
  management_response: string;
}

export interface AuditRecommendation {
  id: string;
  priority: 'low' | 'medium' | 'high' | 'critical';
  description: string;
  rationale: string;
  implementation: RecommendationImplementation;
  monitoring: RecommendationMonitoring;
}

export interface RecommendationImplementation {
  approach: string;
  timeline: string;
  resources: string[];
  responsibilities: string[];
  milestones: string[];
}

export interface RecommendationMonitoring {
  metrics: string[];
  frequency: string;
  reporting: string;
  validation: string;
}

export interface AuditFollowUp {
  process: string;
  frequency: string;
  validation: string;
  reporting: string;
  closure: string;
}

export interface AuditIndependence {
  organizational: string;
  operational: string;
  mental: string;
  safeguards: string[];
  conflicts: string;
}

export interface GovernanceMaturity {
  model: MaturityModel;
  assessment: MaturityAssessment;
  roadmap: MaturityRoadmap;
  improvement: MaturityImprovement;
}

export interface MaturityModel {
  framework: string;
  levels: MaturityLevel[];
  dimensions: MaturityDimension[];
  criteria: MaturityCriteria[];
}

export interface MaturityLevel {
  level: number;
  name: string;
  description: string;
  characteristics: string[];
  capabilities: string[];
}

export interface MaturityDimension {
  dimension: string;
  description: string;
  components: string[];
  assessment: string;
}

export interface MaturityCriteria {
  criteria: string;
  description: string;
  measurement: string;
  evidence: string[];
}

export interface MaturityAssessment {
  current: MaturityProfile;
  target: MaturityProfile;
  gap: MaturityGap[];
  recommendations: string[];
}

export interface MaturityProfile {
  overall: number;
  dimensions: DimensionScore[];
  strengths: string[];
  weaknesses: string[];
}

export interface DimensionScore {
  dimension: string;
  score: number;
  level: string;
  evidence: string[];
}

export interface MaturityGap {
  dimension: string;
  current: number;
  target: number;
  gap: number;
  priority: string;
  effort: string;
}

export interface MaturityRoadmap {
  phases: MaturityPhase[];
  timeline: string;
  investments: string[];
  benefits: string[];
  risks: string[];
}

export interface MaturityPhase {
  phase: string;
  objectives: string[];
  initiatives: string[];
  timeline: string;
  resources: string[];
  milestones: string[];
}

export interface MaturityImprovement {
  strategy: string;
  approach: string;
  initiatives: ImprovementInitiative[];
  monitoring: string;
  governance: string;
}

export interface ImprovementInitiative {
  initiative: string;
  description: string;
  objectives: string[];
  approach: string;
  timeline: string;
  resources: string[];
  benefits: string[];
  risks: string[];
}

export interface GovernanceImprovement {
  strategy: ImprovementStrategy;
  process: ImprovementProcess;
  culture: ImprovementCulture;
  capability: ImprovementCapability;
  innovation: ImprovementInnovation;
}

export interface ImprovementStrategy {
  vision: string;
  objectives: string[];
  principles: string[];
  approach: string;
  timeline: string;
}

export interface ImprovementProcess {
  identification: string;
  prioritization: string;
  planning: string;
  implementation: string;
  monitoring: string;
  closure: string;
}

export interface ImprovementCulture {
  values: string[];
  behaviors: string[];
  incentives: string[];
  communication: string;
  recognition: string;
}

export interface ImprovementCapability {
  skills: string[];
  tools: string[];
  methods: string[];
  development: string;
  knowledge: string;
}

export interface ImprovementInnovation {
  sources: string[];
  evaluation: string;
  experimentation: string;
  scaling: string;
  adoption: string;
}

// Supporting Status Types
export interface GovernanceHealth {
  overall: 'healthy' | 'warning' | 'critical';
  structure: StructureHealth;
  processes: ProcessHealth;
  decisions: DecisionHealth;
  communication: CommunicationHealth;
  compliance: ComplianceHealth;
  effectiveness: EffectivenessHealth;
}

export interface StructureHealth {
  clarity: 'good' | 'fair' | 'poor';
  alignment: 'good' | 'fair' | 'poor';
  efficiency: 'good' | 'fair' | 'poor';
  adaptability: 'good' | 'fair' | 'poor';
  issues: string[];
}

export interface ProcessHealth {
  maturity: 'good' | 'fair' | 'poor';
  efficiency: 'good' | 'fair' | 'poor';
  compliance: 'good' | 'fair' | 'poor';
  automation: 'good' | 'fair' | 'poor';
  issues: string[];
}

export interface DecisionHealth {
  quality: 'good' | 'fair' | 'poor';
  speed: 'good' | 'fair' | 'poor';
  transparency: 'good' | 'fair' | 'poor';
  accountability: 'good' | 'fair' | 'poor';
  issues: string[];
}

export interface CommunicationHealth {
  clarity: 'good' | 'fair' | 'poor';
  frequency: 'good' | 'fair' | 'poor';
  reach: 'good' | 'fair' | 'poor';
  feedback: 'good' | 'fair' | 'poor';
  issues: string[];
}

export interface ComplianceHealth {
  level: 'good' | 'fair' | 'poor';
  monitoring: 'good' | 'fair' | 'poor';
  reporting: 'good' | 'fair' | 'poor';
  remediation: 'good' | 'fair' | 'poor';
  issues: string[];
}

export interface EffectivenessHealth {
  outcomes: 'good' | 'fair' | 'poor';
  efficiency: 'good' | 'fair' | 'poor';
  stakeholder: 'good' | 'fair' | 'poor';
  improvement: 'good' | 'fair' | 'poor';
  issues: string[];
}