"""
Mock data definitions for database seeding.
"""

from app.models.asset import AssetStatus, AssetType, SixRStrategy

# Mock data based on Azure Migrate metadata and common migration scenarios
MOCK_DATA = {
    "client_accounts": [
        {
            "name": "Demo Corporation",
            "slug": "demo-corp",
            "description": "Sample enterprise client for platform demonstration",
            "industry": "Technology",
            "company_size": "Large (1000-5000 employees)",
            "subscription_tier": "enterprise",
            "billing_contact_email": "billing@democorp.com",
        }
    ],
    "users": [
        {
            "email": "demo@democorp.com",
            "password": "password123",  # Will be hashed
            "first_name": "Demo",
            "last_name": "User",
            "is_verified": True,
        }
        # SECURITY: ALL ADMIN DEMO ACCOUNTS REMOVED - no demo accounts with admin privileges
        # Platform admin (chocka@gmail.com) will be set up manually, not via scripts
    ],
    "engagements": [
        {
            "name": "Cloud Migration 2024",
            "slug": "cloud-migration-2024",
            "description": "Migration of on-premises infrastructure to AWS cloud",
            "engagement_type": "migration",
            "status": "active",
            "priority": "high",
            "client_contact_name": "John Smith",
            "client_contact_email": "john.smith@democorp.com",
        }
    ],
    # Tags based on Azure Migrate metadata categories
    "tags": [
        # Technology Tags
        {
            "name": "Windows Server",
            "category": "technology",
            "description": "Windows Server operating system",
        },
        {
            "name": "Linux",
            "category": "technology",
            "description": "Linux operating system",
        },
        {
            "name": "Database Server",
            "category": "technology",
            "description": "Database server workload",
        },
        {
            "name": "Web Server",
            "category": "technology",
            "description": "Web server workload",
        },
        {
            "name": "Application Server",
            "category": "technology",
            "description": "Application server workload",
        },
        {
            "name": "Domain Controller",
            "category": "technology",
            "description": "Active Directory domain controller",
        },
        {
            "name": "File Server",
            "category": "technology",
            "description": "File server workload",
        },
        {
            "name": "Mail Server",
            "category": "technology",
            "description": "Email server workload",
        },
        # Business Function Tags
        {
            "name": "Customer Facing",
            "category": "business",
            "description": "Customer-facing applications",
        },
        {
            "name": "Internal Tools",
            "category": "business",
            "description": "Internal business tools",
        },
        {
            "name": "Backup System",
            "category": "business",
            "description": "Backup and recovery systems",
        },
        {
            "name": "Monitoring",
            "category": "business",
            "description": "Monitoring and observability",
        },
        {
            "name": "Security",
            "category": "business",
            "description": "Security-related systems",
        },
        # Infrastructure Tags
        {
            "name": "Virtual Machine",
            "category": "infrastructure",
            "description": "Virtual machine workload",
        },
        {
            "name": "Physical Server",
            "category": "infrastructure",
            "description": "Physical server hardware",
        },
        {
            "name": "Network Device",
            "category": "infrastructure",
            "description": "Network infrastructure",
        },
        {
            "name": "Storage System",
            "category": "infrastructure",
            "description": "Storage infrastructure",
        },
        # Migration Readiness Tags
        {
            "name": "Cloud Ready",
            "category": "migration",
            "description": "Ready for cloud migration",
        },
        {
            "name": "Legacy System",
            "category": "migration",
            "description": "Legacy system requiring modernization",
        },
        {
            "name": "High Availability",
            "category": "migration",
            "description": "High availability requirements",
        },
        {
            "name": "Compliance Required",
            "category": "migration",
            "description": "Regulatory compliance requirements",
        },
    ],
    # Assets based on typical enterprise infrastructure
    "assets": [
        # Servers
        {
            "name": "DC-WEB-01",
            "hostname": "dc-web-01.democorp.local",
            "asset_type": AssetType.SERVER,
            "description": "Primary web server hosting customer portal",
            "ip_address": "192.168.1.10",
            "fqdn": "dc-web-01.democorp.local",
            "environment": "Production",
            "location": "Data Center 1",
            "datacenter": "DC1-EAST",
            "operating_system": "Windows Server 2019",
            "os_version": "Standard",
            "cpu_cores": 8,
            "memory_gb": 32,
            "storage_gb": 500,
            "business_owner": "IT Operations",
            "department": "Infrastructure",
            "application_name": "Customer Portal",
            "technology_stack": "IIS, ASP.NET, SQL Server",
            "criticality": "High",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REHOST.value,
            "migration_complexity": "Medium",
            "migration_wave": 1,
            "sixr_ready": "Ready",
            "cpu_utilization_percent": 65.5,
            "memory_utilization_percent": 78.2,
            "current_monthly_cost": 1200.0,
            "estimated_cloud_cost": 950.0,
            "discovery_method": "agent_scan",
            "discovery_source": "Azure Migrate",
        },
        {
            "name": "DC-DB-01",
            "hostname": "dc-db-01.democorp.local",
            "asset_type": AssetType.DATABASE,
            "description": "Primary SQL Server database for customer data",
            "ip_address": "192.168.1.20",
            "fqdn": "dc-db-01.democorp.local",
            "environment": "Production",
            "location": "Data Center 1",
            "datacenter": "DC1-EAST",
            "operating_system": "Windows Server 2016",
            "os_version": "Standard",
            "cpu_cores": 16,
            "memory_gb": 64,
            "storage_gb": 2000,
            "business_owner": "Database Team",
            "department": "IT",
            "application_name": "Customer Database",
            "technology_stack": "SQL Server 2016, Always On",
            "criticality": "Critical",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REPLATFORM.value,
            "migration_complexity": "High",
            "migration_wave": 2,
            "sixr_ready": "Needs Analysis",
            "dependencies": ["DC-WEB-01"],
            "cpu_utilization_percent": 45.3,
            "memory_utilization_percent": 82.1,
            "current_monthly_cost": 2500.0,
            "estimated_cloud_cost": 1800.0,
            "discovery_method": "agent_scan",
            "discovery_source": "Azure Migrate",
        },
        {
            "name": "DC-APP-01",
            "hostname": "dc-app-01.democorp.local",
            "asset_type": AssetType.APPLICATION,
            "description": "Internal CRM application server",
            "ip_address": "192.168.1.30",
            "environment": "Production",
            "location": "Data Center 1",
            "operating_system": "Linux Red Hat 8",
            "cpu_cores": 4,
            "memory_gb": 16,
            "storage_gb": 200,
            "business_owner": "Sales Team",
            "department": "Sales",
            "application_name": "CRM System",
            "technology_stack": "Java Spring Boot, PostgreSQL",
            "criticality": "Medium",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REFACTOR.value,
            "migration_complexity": "Medium",
            "migration_wave": 3,
            "sixr_ready": "Ready",
            "cpu_utilization_percent": 35.8,
            "memory_utilization_percent": 68.4,
            "current_monthly_cost": 800.0,
            "estimated_cloud_cost": 650.0,
            "discovery_method": "network_scan",
            "discovery_source": "Custom Discovery Tool",
        },
        # Network Devices
        {
            "name": "CORE-SW-01",
            "hostname": "core-sw-01",
            "asset_type": AssetType.NETWORK,
            "description": "Core network switch for data center connectivity",
            "ip_address": "192.168.1.1",
            "environment": "Production",
            "location": "Data Center 1",
            "operating_system": "Cisco IOS",
            "business_owner": "Network Team",
            "department": "Infrastructure",
            "technology_stack": "Cisco Catalyst 9500",
            "criticality": "Critical",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REHOST.value,
            "migration_complexity": "Low",
            "sixr_ready": "Not Applicable",
            "discovery_method": "snmp_scan",
            "discovery_source": "Network Discovery",
        },
        {
            "name": "FIREWALL-01",
            "hostname": "fw-01",
            "asset_type": AssetType.NETWORK,
            "description": "Perimeter firewall for network security",
            "ip_address": "192.168.1.2",
            "environment": "Production",
            "location": "Data Center 1",
            "operating_system": "Palo Alto PAN-OS",
            "business_owner": "Security Team",
            "department": "Security",
            "technology_stack": "Palo Alto PA-5220",
            "criticality": "Critical",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REPLATFORM.value,
            "migration_complexity": "Medium",
            "migration_wave": 1,
            "sixr_ready": "Needs Analysis",
            "discovery_method": "manual_entry",
            "discovery_source": "Manual Entry",
        },
        # Storage
        {
            "name": "SAN-STORAGE-01",
            "hostname": "san-01",
            "asset_type": AssetType.STORAGE,
            "description": "Primary storage area network for VMs",
            "ip_address": "192.168.1.5",
            "environment": "Production",
            "location": "Data Center 1",
            "operating_system": "Dell EMC PowerStoreOS",
            "business_owner": "Storage Team",
            "department": "Infrastructure",
            "technology_stack": "Dell EMC PowerStore 9200T",
            "criticality": "High",
            "status": AssetStatus.DISCOVERED,
            "six_r_strategy": SixRStrategy.REPLATFORM.value,
            "migration_complexity": "High",
            "migration_wave": 2,
            "sixr_ready": "Needs Analysis",
            "discovery_method": "api_integration",
            "discovery_source": "Dell EMC CloudIQ",
        },
    ],
}
