/**
 * Chargeback Models and Pricing Types
 * 
 * Types for chargeback methodology, pricing models, billing configuration, and payment processing.
 * Covers full chargeback, showback, pricing rates, and billing delivery.
 * 
 * Generated by CC (Claude Code) - Modularized from cost-allocation.ts
 */

import { CostAmount } from '../cost-analysis';

// Chargeback Model Types
export interface ChargebackModel {
  id: string;
  name: string;
  description: string;
  type: 'full_chargeback' | 'showback' | 'hybrid';
  methodology: ChargebackMethodology;
  pricing: ChargebackPricing;
  billing: ChargebackBilling;
  adjustments: ChargebackAdjustment[];
  governance: ChargebackGovernance;
}

export interface ChargebackMethodology {
  approach: 'actual_cost' | 'budgeted_cost' | 'market_rate' | 'negotiated_rate';
  basis: 'usage' | 'allocation' | 'subscription' | 'hybrid';
  granularity: 'service' | 'resource' | 'feature' | 'transaction';
  frequency: 'real_time' | 'daily' | 'weekly' | 'monthly';
}

// Pricing Types
export interface ChargebackPricing {
  model: 'unit_pricing' | 'tiered_pricing' | 'volume_pricing' | 'value_based';
  rates: PricingRate[];
  discounts: PricingDiscount[];
  premiums: PricingPremium[];
  adjustments: PricingAdjustment[];
}

export interface PricingRate {
  service: string;
  unit: string;
  rate: number;
  currency: string;
  effectiveDate: string;
  expirationDate?: string;
}

export interface PricingDiscount {
  type: 'volume' | 'commitment' | 'loyalty' | 'negotiated';
  threshold: number;
  rate: number;
  conditions: string[];
}

export interface PricingPremium {
  type: 'peak_hours' | 'rush_service' | 'priority' | 'sla';
  multiplier: number;
  conditions: string[];
}

export interface PricingAdjustment {
  type: 'inflation' | 'market' | 'cost_plus' | 'regulatory';
  value: number;
  frequency: string;
  automated: boolean;
}

// Billing Configuration Types
export interface ChargebackBilling {
  cycle: 'monthly' | 'quarterly' | 'annually';
  timing: 'advance' | 'arrears';
  aggregation: BillingAggregation;
  format: BillingFormat;
  delivery: BillingDelivery;
  payment: BillingPayment;
}

export interface BillingAggregation {
  level: 'account' | 'project' | 'department' | 'cost_center';
  rollup: boolean;
  consolidation: string[];
  splitting: SplittingRule[];
}

export interface SplittingRule {
  condition: string;
  method: 'proportional' | 'equal' | 'weighted';
  targets: string[];
}

export interface BillingFormat {
  template: string;
  currency: string;
  precision: number;
  language: string;
  customizations: Record<string, string | number | boolean | null>;
}

export interface BillingDelivery {
  method: 'email' | 'portal' | 'api' | 'file_transfer';
  recipients: BillingRecipient[];
  schedule: BillingSchedule;
  notifications: BillingNotification[];
}

export interface BillingRecipient {
  type: 'primary' | 'cc' | 'approver' | 'finance';
  contact: string;
  format: string;
  customizations: Record<string, string | number | boolean | null>;
}

export interface BillingSchedule {
  day: number;
  time: string;
  timezone: string;
  advance_notice: number;
  retry_policy: RetryPolicy;
}

export interface RetryPolicy {
  attempts: number;
  interval: string;
  escalation: string[];
}

export interface BillingNotification {
  event: 'generated' | 'sent' | 'viewed' | 'paid' | 'overdue';
  recipients: string[];
  template: string;
  delay: string;
}

export interface BillingPayment {
  terms: string;
  methods: string[];
  automation: boolean;
  tracking: boolean;
  reconciliation: PaymentReconciliation;
}

export interface PaymentReconciliation {
  automated: boolean;
  tolerance: number;
  frequency: string;
  escalation: string[];
}

// Chargeback Adjustments and Governance
export interface ChargebackAdjustment {
  id: string;
  type: 'credit' | 'debit' | 'refund' | 'write_off';
  reason: string;
  amount: CostAmount;
  target: string;
  period: string;
  approval: AdjustmentApproval;
  documentation: string[];
}

export interface AdjustmentApproval {
  required: boolean;
  approver: string;
  status: 'pending' | 'approved' | 'rejected';
  approvedAt?: string;
  reason?: string;
}

export interface ChargebackGovernance {
  policies: string[];
  approvals: ChargebackApprovalConfig;
  dispute: DisputeProcess;
  audit: ChargebackAuditConfig;
  compliance: ComplianceConfig;
}

export interface ChargebackApprovalConfig {
  thresholds: ApprovalThreshold[];
  workflow: string;
  timeout: string;
  escalation: string[];
}

export interface ApprovalThreshold {
  type: 'amount' | 'percentage' | 'variance';
  value: number;
  approver: string;
  urgency: 'normal' | 'expedited' | 'emergency';
}

export interface DisputeProcess {
  enabled: boolean;
  timeLimit: string;
  workflow: string;
  escalation: string[];
  resolution: DisputeResolution;
}

export interface DisputeResolution {
  methods: string[];
  timeline: string;
  documentation: string[];
  finality: boolean;
}

export interface ChargebackAuditConfig {
  frequency: string;
  scope: string[];
  automated: boolean;
  external: boolean;
  documentation: string[];
}

export interface ComplianceConfig {
  standards: string[];
  requirements: string[];
  certifications: string[];
  reporting: ComplianceReporting;
}

export interface ComplianceReporting {
  frequency: string;
  recipients: string[];
  format: string;
  external: boolean;
}