/**
 * FinOps Flow Management - API Types
 * Request and response interfaces for FinOps flow API operations
 *
 * Generated by CC - Modularized from flow-management.ts
 */

import type { BaseMetadata, AuditableMetadata } from '../../../shared/metadata-types';
import type {
  BaseApiRequest,
  BaseApiResponse,
  MultiTenantContext,
  ListRequest,
  GetRequest,
} from '../../shared';
import type { FinOpsScope, FinOpsObjective, FinOpsConstraint, FinOpsGovernance, FinOpsFlowConfiguration, FinOpsFlowData, FinOpsState, FinOpsStatus, FinOpsStatusDetail, FinOpsFlowSummary } from './flow-core-types';
import type { CostBaseline, CostAnalysis } from './cost-types';
import type { OptimizationOpportunity, ActiveOptimization } from './optimization-types';
import type { BudgetStatus } from './budget-types';
import type { CostForecast, FinOpsAction, FinOpsAlert, FinOpsAggregation, FinOpsTrend, FinOpsBenchmark, FinOpsPortfolioMetrics } from './supporting-types';

// FinOps Flow Management APIs
export interface InitializeFinOpsFlowRequest extends BaseApiRequest {
  flowName: string;
  flowDescription?: string;
  context: MultiTenantContext;
  finOpsScope: FinOpsScope;
  objectives: FinOpsObjective[];
  constraints: FinOpsConstraint[];
  governanceFramework: FinOpsGovernance;
  parentFlowId?: string;
  configuration?: FinOpsFlowConfiguration;
  metadata?: BaseMetadata;
}

export interface InitializeFinOpsFlowResponse extends BaseApiResponse<FinOpsFlowData> {
  data: FinOpsFlowData;
  flowId: string;
  initialState: FinOpsState;
  recommendedActions: FinOpsAction[];
  costBaseline: CostBaseline;
  optimizationOpportunities: OptimizationOpportunity[];
}

export interface GetFinOpsFlowStatusRequest extends GetRequest {
  flowId: string;
  includeDetails?: boolean;
  includeCostAnalysis?: boolean;
  includeOptimizations?: boolean;
  includeBudgetStatus?: boolean;
  includeForecasts?: boolean;
  includeAlerts?: boolean;
}

export interface GetFinOpsFlowStatusResponse extends BaseApiResponse<FinOpsStatusDetail> {
  data: FinOpsStatusDetail;
  costAnalysis: CostAnalysis;
  optimizations: ActiveOptimization[];
  budgetStatus: BudgetStatus;
  forecasts: CostForecast[];
  alerts: FinOpsAlert[];
}

export interface ListFinOpsFlowsRequest extends ListRequest {
  finOpsTypes?: string[];
  status?: FinOpsStatus[];
  costCategories?: string[];
  optimizationTypes?: string[];
  clientAccountIds?: string[];
  engagementIds?: string[];
  dateRange?: {
    start: string;
    end: string;
    field: 'created' | 'updated' | 'cost_period_start' | 'cost_period_end';
  };
  includeArchived?: boolean;
  includeMetrics?: boolean;
}

export interface ListFinOpsFlowsResponse {
  data: FinOpsFlowSummary[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
  aggregations?: FinOpsAggregation[];
  trends?: FinOpsTrend[];
  benchmarks?: FinOpsBenchmark[];
  portfolioMetrics?: FinOpsPortfolioMetrics;
}
