/**
 * FinOps Budget Types
 *
 * Type definitions for budget management, consumption tracking, forecasting, and alerts.
 * Covers all budget-related data structures for FinOps flows.
 *
 * Generated by CC - Modularized from flow-management.ts
 */

export interface BudgetStatus {
  budget: BudgetDetails;
  consumption: ConsumptionMetrics;
  forecast: BudgetForecast;
  alerts: BudgetAlert[];
  recommendations: BudgetRecommendation[];
}

export interface BudgetDetails {
  total: number;
  allocated: number;
  remaining: number;
  period: string;
  currency: string;
}

export interface ConsumptionMetrics {
  current: number;
  percentage: number;
  runRate: number;
  trend: string;
  byCategory: Record<string, number>;
}

export interface BudgetForecast {
  endOfPeriod: number;
  overUnder: number;
  confidence: number;
  scenarios: ForecastScenario[];
}

export interface ForecastScenario {
  name: string;
  probability: number;
  amount: number;
  variance: number;
}

export interface BudgetAlert {
  id: string;
  type: 'threshold' | 'anomaly' | 'forecast';
  severity: 'info' | 'warning' | 'critical';
  message: string;
  threshold?: number;
  actual?: number;
}

export interface BudgetRecommendation {
  action: string;
  impact: number;
  effort: string;
  priority: number;
}
