/**
 * Quality Governance Types
 * 
 * Type definitions for quality governance structures, oversight, decision making,
 * accountability, and communication within quality management systems.
 * 
 * Generated by CC - Claude Code
 */

export interface QualityGovernance {
  structure: QualityGovernanceStructure;
  oversight: QualityOversight;
  decision: QualityDecisionMaking;
  accountability: QualityAccountability;
  communication: QualityCommunication;
}

export interface QualityGovernanceStructure {
  model: string;
  bodies: string[];
  roles: string[];
  relationships: string[];
  authority: string[];
}

export interface QualityOversight {
  committees: string[];
  reviews: string[];
  audits: string[];
  monitoring: string;
  escalation: string;
}

export interface QualityDecisionMaking {
  authority: string[];
  process: string;
  criteria: string[];
  documentation: string;
  communication: string;
}

export interface QualityAccountability {
  roles: string[];
  responsibilities: string[];
  measurement: string;
  consequences: string;
  recognition: string;
}

export interface QualityCommunication {
  strategy: string;
  channels: string[];
  frequency: string;
  stakeholders: string[];
  feedback: string;
}