/**
 * Quality Metrics Types
 * 
 * Type definitions for quality metrics, calculations, targets, collection,
 * analysis, reporting, and governance of measurement systems.
 * 
 * Generated by CC - Claude Code
 */

export interface QualityMetric {
  id: string;
  name: string;
  description: string;
  category: 'process' | 'product' | 'service' | 'outcome';
  type: 'leading' | 'lagging' | 'concurrent';
  calculation: MetricCalculation;
  targets: MetricTarget[];
  collection: MetricCollection;
  analysis: MetricAnalysis;
  reporting: MetricReporting;
  governance: MetricGovernance;
}

export interface MetricCalculation {
  formula: string;
  inputs: string[];
  frequency: string;
  automation: string;
  validation: string;
}

export interface MetricTarget {
  target_type: 'minimum' | 'maximum' | 'range' | 'threshold';
  value: number;
  period: string;
  rationale: string;
  review: string;
}

export interface MetricCollection {
  sources: DataSource[];
  methods: string[];
  frequency: string;
  automation: string;
  quality: string;
}

export interface DataSource {
  source: string;
  type: 'system' | 'manual' | 'survey' | 'observation';
  reliability: string;
  availability: string;
  integration: string;
}

export interface MetricAnalysis {
  methods: string[];
  frequency: string;
  trending: boolean;
  benchmarking: string;
  insights: string;
}

export interface MetricReporting {
  dashboards: string[];
  reports: string[];
  frequency: string;
  audience: string[];
  format: string[];
}

export interface MetricGovernance {
  owner: string;
  steward: string;
  review: string;
  approval: string;
  lifecycle: string;
}