/**
 * Health Status and Monitoring Types
 * 
 * Types for health monitoring, status tracking, and health forecasting
 * in execution planning systems.
 * 
 * Generated by CC - Claude Code
 */

// Common Status and Health Types
export interface HealthStatus {
  overall: 'healthy' | 'warning' | 'critical';
  score: number;
  indicators: HealthIndicator[];
  issues: HealthIssue[];
  trends: HealthTrend[];
  forecast: HealthForecast;
}

export interface HealthIndicator {
  indicator: string;
  value: number;
  threshold: number;
  status: 'green' | 'amber' | 'red';
  trend: 'improving' | 'stable' | 'declining';
  weight: number;
}

export interface HealthIssue {
  issue: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  impact: string;
  resolution: string;
  timeline: string;
  owner: string;
}

export interface HealthTrend {
  period: string;
  direction: 'improving' | 'stable' | 'declining';
  confidence: number;
  drivers: string[];
  forecast: string;
}

export interface HealthForecast {
  outlook: 'positive' | 'stable' | 'concerning' | 'critical';
  confidence: number;
  scenarios: HealthScenario[];
  recommendations: string[];
  monitoring: string[];
}

export interface HealthScenario {
  scenario: string;
  probability: number;
  impact: string;
  indicators: string[];
  actions: string[];
  timeline: string;
}