/**
 * API endpoint constants
 * Note: The actual API configuration is in src/config/api.ts
 * This file provides a simplified constant interface for common endpoints
 */

import { API_CONFIG } from '../config/api';

// Re-export the endpoints from API_CONFIG for backward compatibility
export const API_ENDPOINTS = {
  // Discovery endpoints
  DISCOVERY: {
    ANALYZE: API_CONFIG.ENDPOINTS.DISCOVERY.AGENT_ANALYSIS,
    ASSETS: API_CONFIG.ENDPOINTS.DISCOVERY.ASSETS,
    APPLICATIONS: API_CONFIG.ENDPOINTS.DISCOVERY.APPLICATIONS,
    FEEDBACK: API_CONFIG.ENDPOINTS.DISCOVERY.FEEDBACK,
    METRICS: API_CONFIG.ENDPOINTS.DISCOVERY.DISCOVERY_METRICS
  },
  
  // Collection endpoints
  COLLECTION: {
    STORE_IMPORT: API_CONFIG.ENDPOINTS.DISCOVERY.STORE_IMPORT,
    LATEST_IMPORT: API_CONFIG.ENDPOINTS.DISCOVERY.LATEST_IMPORT,
    LIST_IMPORTS: API_CONFIG.ENDPOINTS.DISCOVERY.LIST_IMPORTS,
    FIELD_MAPPINGS: API_CONFIG.ENDPOINTS.DISCOVERY.SIMPLE_FIELD_MAPPINGS,
    CRITICAL_ATTRIBUTES: API_CONFIG.ENDPOINTS.DISCOVERY.CRITICAL_ATTRIBUTES_STATUS
  },
  
  // Monitoring endpoints
  MONITORING: {
    STATUS: API_CONFIG.ENDPOINTS.MONITORING.STATUS,
    HEALTH: API_CONFIG.ENDPOINTS.MONITORING.HEALTH,
    METRICS: API_CONFIG.ENDPOINTS.MONITORING.METRICS,
    AGENTS: API_CONFIG.ENDPOINTS.MONITORING.AGENTS
  },
  
  // Admin endpoints
  ADMIN: {
    CLIENTS: API_CONFIG.ENDPOINTS.ADMIN.CLIENTS,
    ENGAGEMENTS: API_CONFIG.ENDPOINTS.ADMIN.ENGAGEMENTS,
    USERS: API_CONFIG.ENDPOINTS.ADMIN.USERS,
    USER_PROFILES: API_CONFIG.ENDPOINTS.ADMIN.USER_PROFILES
  },
  
  // Agent learning endpoints
  AGENT_LEARNING: {
    STATS: API_CONFIG.ENDPOINTS.AGENT_LEARNING.LEARNING_STATISTICS,
    FIELD_MAPPING: API_CONFIG.ENDPOINTS.AGENT_LEARNING.FIELD_MAPPING_LEARN,
    SUGGEST: API_CONFIG.ENDPOINTS.AGENT_LEARNING.FIELD_MAPPING_SUGGEST
  },
  
  // Health check
  HEALTH: API_CONFIG.ENDPOINTS.HEALTH
} as const;

// Common API paths
export const API_PATHS = {
  API_V1: '/api/v1',
  API_V2: '/api/v2',
  DISCOVERY: '/discovery',
  MONITORING: '/monitoring',
  ADMIN: '/admin',
  AGENT_LEARNING: '/agent-learning'
} as const;

// API method constants
export const API_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE'
} as const;