name: Implementation Task
description: Create a task aligned with the CrewAI consolidation plan (MFO-first, async DB, multi-tenant, repo hygiene)
title: "[Task]: <short description>"
labels: ["type:task", "backlog"]
projects: ["CryptoYogiLLC/3"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please ensure you develop in Docker containers, adhere to multi-tenant scoping, and avoid hard-coded logic. Link to the relevant section of the audit.

  - type: input
    id: audit_link
    attributes:
      label: Related Audit Section
      description: Link to the exact section in docs/planning/code-analysis/crewai-architecture-and-code-sprawl-audit.md
      placeholder: docs/planning/code-analysis/crewai-architecture-and-code-sprawl-audit.md#...
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Phase
      description: Choose the phase from the Implementation Task Tracker
      options:
        - Phase 1 — Controller Unification and Guards
        - Phase 2 — Repository and DB Session Consolidation
        - Phase 3 — Agent Memory Re-Enablement (Phased)
        - Phase 4 — Repo Hygiene and CI Policy
        - Phase 5 — Tests, Observability, and Cleanup
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-paragraph description of the goal and scope
      placeholder: What outcome are we delivering?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet list of verifiable outcomes
      placeholder: "- [ ] Criteria 1\n- [ ] Criteria 2"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Implementation Steps
      description: Ordered steps the agent should follow
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Size
      options:
        - S (0.5–1 day)
        - M (1–3 days)
        - L (3–5 days)
    validations:
      required: true

  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Link to any blocking issues or PRs
      placeholder: "Depends on #123, #456"

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: Unit/integration/e2e coverage; Docker-only execution
      placeholder: How will this be validated in CI and containers?

  - type: textarea
    id: rollout
    attributes:
      label: Rollout/Rollback Plan
      description: Flags, metrics, and rollback steps
      placeholder: Feature flags, telemetry, and reversion strategy
