/**
 * ROI and Financial Analysis Types
 *
 * Types for return on investment analysis, benefit tracking,
 * financial metrics, and cash flow analysis.
 *
 * Generated by CC - Claude Code
 */

// ROI Analysis Core Types
export interface ROIAnalysis {
  investment: InvestmentAnalysis;
  benefits: BenefitAnalysis;
  returns: ReturnAnalysis;
  metrics: ROIMetrics;
  cashflow: ROICashFlow;
  sensitivity: ROISensitivity;
  scenario: ROIScenario[];
  recommendation: ROIRecommendation;
}

export interface InvestmentAnalysis {
  totalInvestment: number;
  breakdown: InvestmentBreakdown[];
  timing: InvestmentTiming;
  funding: InvestmentFunding;
  risk: InvestmentRisk;
}

export interface BenefitAnalysis {
  totalBenefits: number;
  categories: BenefitCategory[];
  tangible: TangibleBenefit[];
  intangible: IntangibleBenefit[];
  realization: BenefitRealization;
}

export interface ReturnAnalysis {
  totalReturns: number;
  netReturns: number;
  periods: ReturnPeriod[];
  discounting: DiscountingMethod;
  risk: ReturnRisk;
}

export interface ROIMetrics {
  roi: number;
  irr: number;
  npv: number;
  paybackPeriod: number;
  breakEvenPoint: number;
  profitabilityIndex: number;
}

export interface ROICashFlow {
  periods: ROIPeriod[];
  discounting: ROIDiscounting;
  sensitivity: CashFlowSensitivity;
  scenario: CashFlowScenario[];
}

export interface ROISensitivity {
  variables: ROIVariable[];
  analysis: ROIVariableAnalysis[];
  thresholds: ROIThreshold[];
  recommendations: ROISensitivityRecommendation[];
}

export interface ROIScenario {
  scenario: string;
  assumptions: ROIAssumption[];
  metrics: ROIScenarioMetrics;
  probability: number;
  recommendation: string;
}

export interface ROIRecommendation {
  decision: 'proceed' | 'defer' | 'modify' | 'reject';
  rationale: string;
  conditions: string[];
  alternatives: ROIAlternative[];
  sensitivity: string[];
}

// Investment Analysis Supporting Types
export interface InvestmentBreakdown {
  category: string;
  amount: number;
  percentage: number;
  timing: string;
}

export interface InvestmentTiming {
  phases: InvestmentPhase[];
  milestones: InvestmentMilestone[];
  cashflow: InvestmentCashFlow[];
}

export interface InvestmentFunding {
  sources: FundingSource[];
  structure: FundingStructure;
  schedule: FundingScheduleDetail[];
  risks: FundingRisk[];
}

export interface InvestmentRisk {
  risks: InvestmentRiskFactor[];
  mitigation: RiskMitigation[];
  contingency: RiskContingency;
}

export interface InvestmentPhase {
  phase: string;
  amount: number;
  timing: string;
  dependencies: string[];
}

export interface InvestmentMilestone {
  milestone: string;
  amount: number;
  date: string;
  criteria: string[];
}

export interface InvestmentCashFlow {
  period: string;
  amount: number;
  cumulative: number;
  source: string;
}

export interface FundingSource {
  source: string;
  amount: number;
  cost: number;
  terms: string[];
}

export interface FundingStructure {
  debt: number;
  equity: number;
  internal: number;
  external: number;
}

export interface FundingScheduleDetail {
  milestone: string;
  amount: number;
  date: string;
  source: string;
}

export interface FundingRisk {
  risk: string;
  probability: number;
  impact: number;
  mitigation: string;
}

export interface InvestmentRiskFactor {
  risk: string;
  category: string;
  probability: number;
  impact: number;
}

export interface RiskMitigation {
  risk: string;
  strategy: string;
  cost: number;
  effectiveness: number;
}

export interface RiskContingency {
  amount: number;
  triggers: string[];
  approval: string;
}

// Benefit Analysis Supporting Types
export interface BenefitCategory {
  category: string;
  amount: number;
  percentage: number;
  timeline: string;
  confidence: number;
}

export interface TangibleBenefit {
  benefit: string;
  amount: number;
  measurement: string;
  realization: string;
  confidence: number;
}

export interface IntangibleBenefit {
  benefit: string;
  description: string;
  quantification: string;
  impact: string;
  measurement: string;
}

export interface BenefitRealization {
  timeline: RealizationTimeline;
  milestones: RealizationMilestone[];
  tracking: RealizationTracking;
  risks: RealizationRisk[];
}

export interface RealizationTimeline {
  phases: RealizationPhase[];
  duration: number;
  dependencies: string[];
}

export interface RealizationMilestone {
  milestone: string;
  benefit: number;
  date: string;
  criteria: string[];
}

export interface RealizationTracking {
  frequency: string;
  metrics: string[];
  reporting: string;
  escalation: string[];
}

export interface RealizationRisk {
  risk: string;
  probability: number;
  impact: number;
  mitigation: string;
}

export interface RealizationPhase {
  phase: string;
  benefit: number;
  duration: number;
  activities: string[];
}

// Return Analysis Supporting Types
export interface ReturnPeriod {
  period: string;
  returns: number;
  cumulative: number;
  discounted: number;
}

export interface DiscountingMethod {
  method: 'npv' | 'irr' | 'payback' | 'profitability_index';
  rate: number;
  compounding: string;
  adjustments: DiscountAdjustment[];
}

export interface ReturnRisk {
  volatility: number;
  downside: number;
  probability: ReturnProbability[];
  sensitivity: ReturnSensitivity[];
}

export interface DiscountAdjustment {
  type: string;
  adjustment: number;
  rationale: string;
}

export interface ReturnProbability {
  scenario: string;
  probability: number;
  return: number;
}

export interface ReturnSensitivity {
  variable: string;
  impact: number;
  threshold: number;
}

// ROI Cash Flow Supporting Types
export interface ROIPeriod {
  period: string;
  investment: number;
  benefits: number;
  net: number;
  cumulative: number;
  discounted: number;
}

export interface ROIDiscounting {
  rate: number;
  method: string;
  adjustments: ROIAdjustment[];
  sensitivity: DiscountSensitivity[];
}

export interface CashFlowSensitivity {
  variables: CashFlowVariable[];
  scenarios: CashFlowScenario[];
  analysis: CashFlowAnalysis;
}

export interface CashFlowScenario {
  scenario: string;
  cashflow: CashFlowPeriod[];
  metrics: CashFlowMetrics;
  probability: number;
}

export interface ROIAdjustment {
  type: string;
  adjustment: number;
  rationale: string;
}

export interface DiscountSensitivity {
  rate: number;
  impact: number;
  threshold: number;
}

export interface CashFlowVariable {
  variable: string;
  impact: number;
  elasticity: number;
}

export interface CashFlowPeriod {
  period: string;
  inflow: number;
  outflow: number;
  net: number;
}

export interface CashFlowMetrics {
  totalInflow: number;
  totalOutflow: number;
  netCashFlow: number;
  roi: number;
}

export interface CashFlowAnalysis {
  volatility: number;
  correlation: CashFlowCorrelation[];
  trends: CashFlowTrend[];
}

export interface CashFlowCorrelation {
  variable: string;
  correlation: number;
}

export interface CashFlowTrend {
  metric: string;
  trend: string;
  rate: number;
}

// ROI Sensitivity Supporting Types
export interface ROIVariable {
  variable: string;
  impact: number;
  elasticity: number;
  threshold: number;
  sensitivity: number;
}

export interface ROIVariableAnalysis {
  variable: string;
  baseCase: number;
  sensitivityRange: SensitivityRange[];
  breakeven: number;
  recommendation: string;
}

export interface ROIThreshold {
  metric: string;
  threshold: number;
  condition: string;
  action: string;
}

export interface ROISensitivityRecommendation {
  variable: string;
  recommendation: string;
  rationale: string;
  monitoring: string;
}

export interface SensitivityRange {
  low: number;
  high: number;
  impact: number;
}

// ROI Scenario Supporting Types
export interface ROIAssumption {
  assumption: string;
  impact: string;
  confidence: number;
  validation: string;
}

export interface ROIScenarioMetrics {
  roi: number;
  npv: number;
  irr: number;
  payback: number;
  profitabilityIndex: number;
}

export interface ROIAlternative {
  alternative: string;
  investment: number;
  benefits: number;
  metrics: ROIAlternativeMetrics;
  recommendation: string;
}

export interface ROIAlternativeMetrics {
  roi: number;
  npv: number;
  irr: number;
  payback: number;
}
