"""
Question templates for Application assets.
"""

APPLICATION_QUESTIONS = [
    {
        "question_text": "What is the application name?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 10,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the application version?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 9,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the programming language?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 8,
        "is_required": True,
        "answer_options": [
            "Java",
            "Python",
            "Node.js",
            ".NET",
            "PHP",
            "Ruby",
            "Go",
            "Other",
        ],
    },
    {
        "question_text": "What framework does the application use?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 7,
        "is_required": False,
        "answer_options": [
            "Spring Boot",
            "Django",
            "Flask",
            "Express",
            "ASP.NET",
            "Rails",
            "Other",
        ],
    },
    {
        "question_text": "What database does the application use?",
        "question_type": "dropdown",
        "section": "Dependencies",
        "weight": 8,
        "is_required": True,
        "answer_options": [
            "PostgreSQL",
            "MySQL",
            "Oracle",
            "SQL Server",
            "MongoDB",
            "Redis",
            "Cassandra",
            "None",
        ],
    },
    {
        "question_text": "What is the deployment model?",
        "question_type": "dropdown",
        "section": "Deployment",
        "weight": 7,
        "is_required": True,
        "answer_options": ["On-Premise", "Cloud", "Hybrid", "SaaS"],
    },
    {
        "question_text": "What authentication method is used?",
        "question_type": "multi_select",
        "section": "Security",
        "weight": 6,
        "is_required": False,
        "answer_options": ["LDAP", "OAuth2", "SAML", "API Keys", "Basic Auth", "None"],
    },
    {
        "question_text": "Does the application require internet access?",
        "question_type": "dropdown",
        "section": "Network",
        "weight": 5,
        "is_required": True,
        "answer_options": ["Yes", "No"],
    },
    {
        "question_text": "What is the application criticality?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 9,
        "is_required": True,
        "answer_options": ["Critical", "High", "Medium", "Low"],
    },
    {
        "question_text": "What is the estimated downtime tolerance?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 8,
        "is_required": False,
        "answer_options": ["0 hours", "1-4 hours", "4-8 hours", "1-2 days", "> 2 days"],
    },
]
