"""
Question templates for Database assets.
"""

DATABASE_QUESTIONS = [
    {
        "question_text": "What is the database name?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 10,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What database engine is used?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 9,
        "is_required": True,
        "answer_options": [
            "PostgreSQL",
            "MySQL",
            "Oracle",
            "SQL Server",
            "MongoDB",
            "Redis",
            "Cassandra",
            "DynamoDB",
            "Other",
        ],
    },
    {
        "question_text": "What is the database version?",
        "question_type": "text",
        "section": "Technical",
        "weight": 8,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the database size (GB)?",
        "question_type": "text",
        "section": "Resources",
        "weight": 8,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "Is high availability configured?",
        "question_type": "dropdown",
        "section": "Availability",
        "weight": 7,
        "is_required": True,
        "answer_options": ["Yes - Active/Active", "Yes - Active/Passive", "No"],
    },
    {
        "question_text": "What replication strategy is used?",
        "question_type": "dropdown",
        "section": "Availability",
        "weight": 6,
        "is_required": False,
        "answer_options": ["Synchronous", "Asynchronous", "Snapshot", "None"],
    },
    {
        "question_text": "What backup strategy is used?",
        "question_type": "dropdown",
        "section": "Data Protection",
        "weight": 9,
        "is_required": True,
        "answer_options": [
            "Full Daily",
            "Full Weekly + Incremental",
            "Continuous",
            "Snapshot",
            "None",
        ],
    },
    {
        "question_text": "What is the backup retention period?",
        "question_type": "dropdown",
        "section": "Data Protection",
        "weight": 7,
        "is_required": False,
        "answer_options": ["7 days", "30 days", "90 days", "1 year", "> 1 year"],
    },
    {
        "question_text": "What is the database criticality?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 10,
        "is_required": True,
        "answer_options": ["Critical", "High", "Medium", "Low"],
    },
    {
        "question_text": "What is the RTO (Recovery Time Objective)?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 8,
        "is_required": False,
        "answer_options": [
            "< 1 hour",
            "1-4 hours",
            "4-8 hours",
            "1-2 days",
            "> 2 days",
        ],
    },
]
