"""
Question templates for Network assets.
"""

NETWORK_QUESTIONS = [
    {
        "question_text": "What is the network device name?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 10,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the device type?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 9,
        "is_required": True,
        "answer_options": [
            "Router",
            "Switch",
            "Firewall",
            "Load Balancer",
            "VPN Gateway",
            "Other",
        ],
    },
    {
        "question_text": "What is the device vendor?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 8,
        "is_required": True,
        "answer_options": [
            "Cisco",
            "Juniper",
            "Palo Alto",
            "Fortinet",
            "F5",
            "Arista",
            "Other",
        ],
    },
    {
        "question_text": "What is the device model?",
        "question_type": "text",
        "section": "Technical",
        "weight": 7,
        "is_required": False,
        "answer_options": None,
    },
    {
        "question_text": "Is the device redundant?",
        "question_type": "dropdown",
        "section": "Availability",
        "weight": 8,
        "is_required": True,
        "answer_options": ["Yes - Active/Active", "Yes - Active/Standby", "No"],
    },
    {
        "question_text": "What protocols are used?",
        "question_type": "multi_select",
        "section": "Technical",
        "weight": 6,
        "is_required": False,
        "answer_options": ["OSPF", "BGP", "EIGRP", "VRRP", "HSRP", "LACP", "Other"],
    },
    {
        "question_text": "What is the device criticality?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 9,
        "is_required": True,
        "answer_options": ["Critical", "High", "Medium", "Low"],
    },
    {
        "question_text": "What is the firmware version?",
        "question_type": "text",
        "section": "Technical",
        "weight": 6,
        "is_required": False,
        "answer_options": None,
    },
    {
        "question_text": "Is configuration backed up?",
        "question_type": "dropdown",
        "section": "Operations",
        "weight": 7,
        "is_required": True,
        "answer_options": ["Yes - Automated", "Yes - Manual", "No"],
    },
    {
        "question_text": "What management protocol is used?",
        "question_type": "dropdown",
        "section": "Operations",
        "weight": 5,
        "is_required": False,
        "answer_options": ["SNMP", "NETCONF", "SSH", "Telnet", "API"],
    },
]
