"""
Question templates for Server assets.
"""

SERVER_QUESTIONS = [
    {
        "question_text": "What is the server hostname?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 10,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the operating system?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 9,
        "is_required": True,
        "answer_options": [
            "Windows Server 2019",
            "Windows Server 2022",
            "RHEL 8",
            "RHEL 9",
            "Ubuntu 20.04",
            "Ubuntu 22.04",
            "CentOS 7",
            "Other",
        ],
    },
    {
        "question_text": "How many CPU cores?",
        "question_type": "text",
        "section": "Resources",
        "weight": 8,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "How much RAM (GB)?",
        "question_type": "text",
        "section": "Resources",
        "weight": 8,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the server role?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 7,
        "is_required": True,
        "answer_options": [
            "Web Server",
            "App Server",
            "Database Server",
            "File Server",
            "Domain Controller",
            "Other",
        ],
    },
    {
        "question_text": "Is the server virtualized?",
        "question_type": "dropdown",
        "section": "Infrastructure",
        "weight": 6,
        "is_required": True,
        "answer_options": [
            "Yes - VMware",
            "Yes - Hyper-V",
            "Yes - KVM",
            "No - Physical",
            "Cloud VM",
        ],
    },
    {
        "question_text": "What backup solution is used?",
        "question_type": "dropdown",
        "section": "Data Protection",
        "weight": 7,
        "is_required": False,
        "answer_options": [
            "Veeam",
            "CommVault",
            "Veritas",
            "Windows Backup",
            "Custom Script",
            "None",
        ],
    },
    {
        "question_text": "What monitoring tools are installed?",
        "question_type": "multi_select",
        "section": "Operations",
        "weight": 5,
        "is_required": False,
        "answer_options": [
            "Nagios",
            "Zabbix",
            "SCOM",
            "Datadog",
            "New Relic",
            "Prometheus",
            "None",
        ],
    },
    {
        "question_text": "What is the server criticality?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 9,
        "is_required": True,
        "answer_options": ["Critical", "High", "Medium", "Low"],
    },
    {
        "question_text": "What is the patching schedule?",
        "question_type": "dropdown",
        "section": "Operations",
        "weight": 6,
        "is_required": False,
        "answer_options": ["Monthly", "Quarterly", "Annual", "Ad-hoc", "None"],
    },
]
