"""
Question templates for Storage assets.
"""

STORAGE_QUESTIONS = [
    {
        "question_text": "What is the storage array name?",
        "question_type": "text",
        "section": "Basic Info",
        "weight": 10,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the storage type?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 9,
        "is_required": True,
        "answer_options": [
            "SAN",
            "NAS",
            "DAS",
            "Object Storage",
            "Cloud Storage",
            "Other",
        ],
    },
    {
        "question_text": "What is the storage vendor?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 8,
        "is_required": True,
        "answer_options": [
            "NetApp",
            "EMC",
            "HPE",
            "Dell",
            "Pure Storage",
            "IBM",
            "Other",
        ],
    },
    {
        "question_text": "What is the total capacity (TB)?",
        "question_type": "text",
        "section": "Resources",
        "weight": 8,
        "is_required": True,
        "answer_options": None,
    },
    {
        "question_text": "What is the used capacity (TB)?",
        "question_type": "text",
        "section": "Resources",
        "weight": 7,
        "is_required": False,
        "answer_options": None,
    },
    {
        "question_text": "What RAID level is used?",
        "question_type": "dropdown",
        "section": "Technical",
        "weight": 7,
        "is_required": False,
        "answer_options": [
            "RAID 0",
            "RAID 1",
            "RAID 5",
            "RAID 6",
            "RAID 10",
            "No RAID",
        ],
    },
    {
        "question_text": "Is replication configured?",
        "question_type": "dropdown",
        "section": "Data Protection",
        "weight": 8,
        "is_required": True,
        "answer_options": ["Yes - Synchronous", "Yes - Asynchronous", "No"],
    },
    {
        "question_text": "What snapshot retention policy is used?",
        "question_type": "dropdown",
        "section": "Data Protection",
        "weight": 6,
        "is_required": False,
        "answer_options": ["7 days", "30 days", "90 days", "Custom", "None"],
    },
    {
        "question_text": "What is the storage criticality?",
        "question_type": "dropdown",
        "section": "Business",
        "weight": 9,
        "is_required": True,
        "answer_options": ["Critical", "High", "Medium", "Low"],
    },
    {
        "question_text": "What protocol is used for access?",
        "question_type": "multi_select",
        "section": "Technical",
        "weight": 6,
        "is_required": False,
        "answer_options": ["iSCSI", "FC", "NFS", "SMB/CIFS", "S3", "Other"],
    },
]
