/**
 * Admin Component Types - Modularized Version
 * 
 * This file serves as a central export point for all admin component types.
 * Individual type definitions have been moved to specialized modules for better organization.
 */

// Re-export all types from modular files to maintain backward compatibility
export type * from './admin/user-management';
export type * from './admin/engagement-management';
export type * from './admin/system-settings';
export type * from './admin/analytics-dashboard';
export type * from './admin/session-comparison';
export type * from './admin/supporting-types';

// Legacy re-exports for backward compatibility
// These ensure that existing imports continue to work
export type {
  // User Management Types
  UserListProps,
  UserDetailsModalProps,
  UserApprovalProps,
  UserStatsProps,
  User,
  UserAction,
  UserBulkAction,
  UserTableColumn,
  UserFilter,
  UserSortConfig,
  UserDetailsTab,
  UserApprovalData,
  ApprovalFormField,
  RejectionReason,
  UserStats,
  UserStatsChart,
  UserStatCard,
  TimeRange,
  CustomMetric,
  AuditLog,
  Permission,
  Role,
  UserSession,
  UserActivity,
  UserPreferences,
  NotificationPreferences,
  DisplayPreferences,
  UserStatus
} from './admin/user-management';

export type {
  // Engagement Management Types
  EngagementListProps,
  EngagementCreationProps,
  EngagementFiltersProps,
  Engagement,
  EngagementListPaginationConfig,
  EngagementAction,
  EngagementBulkAction,
  EngagementTableColumn,
  EngagementFilter,
  EngagementSortConfig,
  CreateEngagementRequest,
  EngagementTemplate,
  EngagementCreationStep,
  EngagementValidationConfig,
  Client,
  Team,
  TeamMember,
  EngagementPhase,
  CreateEngagementPhase,
  EngagementPhaseTemplate,
  Deliverable,
  CreateDeliverable,
  DeliverableTemplate,
  Milestone,
  CreateMilestone,
  MilestoneTemplate,
  SavedFilter,
  EngagementField,
  StepValidationRule,
  Risk,
  Issue,
  Artifact,
  MilestoneCriteria,
  CreateMilestoneCriteria,
  MilestoneCriteriaTemplate,
  DocumentTemplate,
  FieldOption,
  FieldDependency,
  ValidationRule,
  FilterOption,
  ExportFormat,
  ExportOptions,
  EngagementStatus,
  EngagementType,
  PhaseStatus,
  DeliverableType,
  DeliverableStatus,
  MilestoneStatus,
  CompanySize,
  ClientStatus,
  RiskSeverity,
  RiskStatus,
  IssuePriority,
  IssueStatus
} from './admin/engagement-management';

export type {
  // System Settings Types
  SystemSettingsProps,
  SecuritySettingsProps,
  SystemSettings,
  GeneralSettings,
  SecuritySettings,
  PasswordPolicy,
  SessionSettings,
  MfaSettings,
  AccessControlSettings,
  EncryptionSettings,
  RateLimitSettings,
  CorsSettings,
  NotificationSettings,
  EmailNotificationSettings,
  ApiSettings,
  StorageSettings,
  PerformanceSettings,
  FeatureSettings,
  BrandingSettings,
  MaintenanceSettings,
  BackupSettings,
  SettingsSection,
  SettingsField,
  SettingsValidationConfig,
  SettingsValidationRule,
  SettingsAuditLog,
  SecurityPolicy,
  SecurityRule,
  SecurityAuditLog,
  SettingsFieldType,
  SettingsAction,
  SecurityPolicyType,
  SecurityCondition,
  SecurityAction,
  MfaMethod,
  BackupFrequency,
  BackupStorage
} from './admin/system-settings';

export type {
  // Analytics Dashboard Types
  AnalyticsDashboardProps,
  MetricsOverviewProps,
  DashboardWidget,
  DashboardLayout,
  WidgetLayout,
  WidgetPosition,
  WidgetSize,
  WidgetConfiguration,
  DataSource,
  VisualizationConfig,
  ChartConfig,
  TableConfig,
  MetricConfig,
  DashboardFilter,
  DashboardTemplate,
  Metric,
  MetricFilter,
  MetricTrend,
  TrendDataPoint,
  MetricTarget,
  MetricAlert,
  LayoutBreakpoint,
  LayoutSettings,
  WidgetFilter,
  AggregationConfig,
  FormattingConfig,
  InteractionConfig,
  RefreshConfig,
  WidgetType,
  DataSourceType,
  VisualizationType,
  ChartType,
  FilterType,
  TimeRangePreset,
  ChangeType,
  TrendDirection,
  TargetType,
  TargetStatus,
  AlertType,
  AlertSeverity
} from './admin/analytics-dashboard';

export type {
  // Session Comparison Types
  SessionComparisonProps,
  UserSession,
  SessionUser,
  DeviceInfo,
  OperatingSystem,
  LocationInfo,
  AuthenticationInfo,
  SessionActivity,
  SessionMetrics,
  PerformanceMetrics,
  SessionSecurity,
  SecurityAnomaly,
  SecurityViolation,
  SecurityAlert,
  SessionPermission,
  AccessPattern,
  ThreatIndicator,
  NetworkInfo,
  EncryptionInfo,
  ProxyInfo,
  CdnInfo,
  BrowserInfo,
  BrowserPlugin,
  BrowserExtension,
  Viewport,
  ScreenInfo,
  SessionFlags,
  SessionComparisonColumn,
  SessionFilter,
  SessionComparison,
  ComparisonDifference,
  ComparisonSimilarity,
  ComparisonValue,
  ComparisonMetrics,
  ComparisonSummary,
  ComparisonRecommendation,
  RecommendedAction,
  DeviceType,
  AuthMethod,
  ActivityType,
  ActivityStatus,
  RiskLevel,
  AnomalyType,
  ViolationType,
  ViolationResponse,
  ThreatType,
  ConnectionType,
  ProxyType
} from './admin/session-comparison';

export type {
  // Supporting Types
  FormField,
  TableColumn,
  PaginationConfig,
  ExportConfig,
  ImportConfig,
  FilterConfig,
  SearchConfig,
  SortConfig,
  GroupConfig,
  Environment,
  HealthStatus,
  DependencyType,
  DependencyStatus,
  FieldType,
  ValidationType,
  DependencyOperation,
  ConditionalOperator,
  FilterOperator,
  SortDirection,
  ExportType,
  ImportType,
  SystemInfo,
  SystemConfiguration,
  SystemHealth,
  SystemMetrics,
  SystemDependency
} from './admin/supporting-types';