/**
 * Security Settings Types
 *
 * Type definitions for security settings, policies, authentication,
 * and access control configurations.
 *
 * Generated by CC modularization
 */

export interface SecuritySettings {
  passwordPolicy: PasswordPolicy;
  sessionSettings: SessionSettings;
  mfaSettings: MfaSettings;
  accessControl: AccessControlSettings;
  encryption: EncryptionSettings;
  rateLimiting: RateLimitSettings;
  ipWhitelist: string[];
  ipBlacklist: string[];
  corsSettings: CorsSettings;
}

export interface PasswordPolicy {
  minLength: number;
  requireUppercase: boolean;
  requireLowercase: boolean;
  requireNumbers: boolean;
  requireSpecialChars: boolean;
  maxAge: number;
  preventReuse: number;
  lockoutThreshold: number;
  lockoutDuration: number;
}

export interface SessionSettings {
  timeout: number;
  extendOnActivity: boolean;
  maxConcurrentSessions: number;
  allowMultipleDevices: boolean;
  forceLogoutOnPasswordChange: boolean;
  rememberMeDuration: number;
}

export interface MfaSettings {
  enabled: boolean;
  required: boolean;
  methods: MfaMethod[];
  backupCodes: boolean;
  gracePeriod: number;
  trustedDevices: boolean;
  trustedDeviceDuration: number;
}

export interface AccessControlSettings {
  rbacEnabled: boolean;
  inheritPermissions: boolean;
  denyByDefault: boolean;
  auditAccessAttempts: boolean;
  ipBasedRestrictions: boolean;
  timeBasedRestrictions: boolean;
  deviceBasedRestrictions: boolean;
}

export interface EncryptionSettings {
  algorithm: string;
  keySize: number;
  rotationInterval: number;
  encryptAtRest: boolean;
  encryptInTransit: boolean;
  hashingAlgorithm: string;
  saltRounds: number;
}

export interface RateLimitSettings {
  enabled: boolean;
  requestsPerMinute: number;
  requestsPerHour: number;
  requestsPerDay: number;
  blockDuration: number;
  exemptIps: string[];
  exemptUsers: string[];
}

export interface CorsSettings {
  enabled: boolean;
  allowedOrigins: string[];
  allowedMethods: string[];
  allowedHeaders: string[];
  allowCredentials: boolean;
  maxAge: number;
}

export interface SecurityPolicy {
  id: string;
  name: string;
  description?: string;
  type: SecurityPolicyType;
  rules: SecurityRule[];
  enabled: boolean;
  priority: number;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface SecurityRule {
  id: string;
  condition: SecurityCondition;
  action: SecurityAction;
  parameters?: Record<string, unknown>;
  enabled: boolean;
}

export interface SecurityAuditLog {
  id: string;
  userId?: string;
  userName?: string;
  action: SecurityAction;
  resource: string;
  result: 'success' | 'failure' | 'denied';
  reason?: string;
  timestamp: string;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, string | number | boolean | null>;
}

// MFA Method interface
export interface MfaMethod {
  type: string;
  enabled: boolean;
  configuration?: Record<string, string | number | boolean | null>;
}

// Enum and union types for security
export type SecurityPolicyType =
  | 'authentication'
  | 'authorization'
  | 'data_protection'
  | 'network_security'
  | 'compliance';

export type SecurityCondition =
  | 'ip_address'
  | 'user_role'
  | 'time_range'
  | 'device_type'
  | 'location'
  | 'custom';

export type SecurityAction =
  | 'allow'
  | 'deny'
  | 'require_mfa'
  | 'log'
  | 'alert'
  | 'block'
  | 'redirect';

export type MfaMethodType =
  | 'totp'
  | 'sms'
  | 'email'
  | 'hardware_token'
  | 'biometric';
