/**
 * FinOps Resource and Approval Management Types
 * 
 * Resource requirements, availability, constraints, and approval workflows
 * for FinOps execution management.
 * 
 * Generated by CC (Claude Code) - Modularized from execution-types.ts
 */

import type { CostAmount } from '../cost-analysis';
import type { ConfigurationValue, TypedConstraint } from '../../../shared/config-types';

// Resource and Approval Management
export interface ResourceRequirement {
  type: 'compute' | 'storage' | 'network' | 'human' | 'license';
  name: string;
  quantity: number;
  unit: string;
  duration: string;
  cost?: CostAmount;
  availability: ResourceAvailability;
  constraints: ResourceConstraint[];
}

export interface ResourceAvailability {
  startDate: string;
  endDate: string;
  schedule?: string;
  exclusions?: string[];
}

export interface ResourceConstraint extends Omit<TypedConstraint, 'type' | 'impact'> {
  type: 'capacity' | 'performance' | 'location' | 'compliance' | 'cost';
  mandatory: boolean;
}

// Approval System
export interface ApprovalRequirement {
  id: string;
  type: 'plan' | 'execution' | 'change' | 'budget' | 'compliance';
  name: string;
  description: string;
  approvers: Approver[];
  criteria: ApprovalCriteria[];
  workflow: ApprovalWorkflow;
  timeout: string;
  escalation: ApprovalEscalation;
}

export interface Approver {
  id: string;
  type: 'user' | 'role' | 'group';
  required: boolean;
  order: number;
  delegation?: ApprovalDelegation;
}

export interface ApprovalDelegation {
  enabled: boolean;
  delegates: string[];
  conditions: string[];
  duration: string;
}

export interface ApprovalCriteria {
  name: string;
  description: string;
  type: 'automatic' | 'manual';
  condition?: string;
  weight: number;
}

export interface ApprovalWorkflow {
  type: 'sequential' | 'parallel' | 'majority' | 'unanimous';
  steps: ApprovalStep[];
  routing: WorkflowRouting[];
  conditions: WorkflowCondition[];
}

export interface ApprovalStep {
  id: string;
  name: string;
  approvers: string[];
  required: number;
  timeout: string;
  conditions: string[];
}

export interface WorkflowRouting {
  condition: string;
  destination: string;
  action: 'route' | 'skip' | 'escalate';
}

export interface WorkflowCondition {
  field: string;
  operator: string;
  value: unknown;
  action: string;
}

export interface ApprovalEscalation {
  enabled: boolean;
  levels: EscalationLevel[];
  timeout: string;
  finalAction: 'approve' | 'reject' | 'escalate_external';
}

export interface EscalationLevel {
  level: number;
  escalateTo: string[];
  timeout: string;
  conditions: string[];
  actions: string[];
}
