"""
Cache Key Patterns - Modular Implementation

This module provides the unified CacheKeys class by combining all domain-specific
cache key patterns into a single interface, maintaining backward compatibility.

The modular structure organizes cache keys by functional domains:
- User Context: user authentication, preferences, accessible resources
- Field Mapping: import field mappings, statistics, AI suggestions
- Flow State: flow data, metadata, agent results, phase data
- Client Management: engagements, users, flows, settings
- Data Import: metadata, validation, schema detection
- Asset Inventory: assets, dependencies, SIXR recommendations
- Admin/Analytics: user management, approvals, metrics, statistics
- Agent Execution: analysis results, learning patterns, execution state
- Security: encrypted configurations, tool configs, memory, flow state

Generated by CC (Claude Code)
"""

from .user_keys import UserCacheKeys

# REMOVED: Field mapping cache keys - field mapping functionality was removed
# from .field_mapping_keys import FieldMappingCacheKeys
from .flow_keys import FlowCacheKeys
from .client_keys import ClientCacheKeys
from .import_keys import ImportCacheKeys
from .asset_keys import AssetCacheKeys
from .admin_keys import AdminCacheKeys
from .agent_keys import AgentCacheKeys
from .security_keys import SecurityCacheKeys


class CacheKeys(
    UserCacheKeys,
    # FieldMappingCacheKeys,  # REMOVED
    FlowCacheKeys,
    ClientCacheKeys,
    ImportCacheKeys,
    AssetCacheKeys,
    AdminCacheKeys,
    AgentCacheKeys,
    SecurityCacheKeys,
):
    """
    Unified cache key generation class combining all domain-specific patterns.

    This class inherits from all domain-specific cache key classes, providing
    a single interface for all cache key generation methods while maintaining
    the modular organization for maintainability.

    Design Principles:
    - All keys include CACHE_VERSION for schema evolution
    - Multi-tenant isolation via client_account_id where applicable
    - Hierarchical structure for cascade invalidation
    - Consistent naming patterns for monitoring
    - Memory-efficient key lengths
    - Security-sensitive keys marked for encryption requirements

    Usage:
        # All cache key methods are available directly on CacheKeys
        key = CacheKeys.user_context("user123")
        key = CacheKeys.flow_metadata("flow123", "client456", "eng789")
        key = CacheKeys.agent_configuration("agent123", "discovery", "client456")
    """

    pass


# Export the unified class for backward compatibility
__all__ = ["CacheKeys"]
