/**
 * FinOps Resource Allocation Optimization Types
 * 
 * Type definitions focused on resource allocation optimization,
 * strategy planning, and optimization execution.
 * 
 * Generated by CC (Claude Code) - Modularized from resource-optimization.ts
 */

import {
  BaseApiRequest,
  BaseApiResponse,
  MultiTenantContext
} from '../../shared';
import { CostAmount } from '../cost-analysis';
import {
  OptimizationStrategy,
  OptimizationConstraint,
  OptimizationTarget,
  ResourceConfiguration,
  RiskAssessment,
  ExecutionPlan,
  ResourceState,
  ChangeImpact
} from '../shared';
import type { ConfigurationValue, TypedConstraint } from '../../../shared/config-types';

// Resource Allocation Optimization APIs
export interface OptimizeResourceAllocationRequest extends BaseApiRequest {
  analysisId: string;
  optimizationStrategy: ResourceOptimizationStrategy;
  constraints: ResourceConstraint[];
  objectives: ResourceObjective[];
  simulateOnly?: boolean;
  context: MultiTenantContext;
}

export interface OptimizeResourceAllocationResponse extends BaseApiResponse<ResourceOptimization> {
  data: ResourceOptimization;
  optimizationId: string;
  currentAllocation: ResourceAllocation;
  optimizedAllocation: ResourceAllocation;
  projectedSavings: CostAmount;
  implementationPlan: ResourceImplementationPlan;
}

// Optimization Strategy Types
export interface ResourceOptimizationStrategy {
  objective: 'cost' | 'performance' | 'balanced' | 'sustainability';
  approach: 'conservative' | 'moderate' | 'aggressive';
  constraints: OptimizationConstraint[];
  priorities: OptimizationPriority[];
  timeframe: string;
}

export interface OptimizationPriority {
  dimension: string;
  weight: number;
  direction: 'minimize' | 'maximize';
}

export interface ResourceConstraint extends Omit<TypedConstraint, 'type' | 'impact'> {
  type: 'capacity' | 'performance' | 'location' | 'compliance' | 'budget';
  flexibility: 'none' | 'low' | 'medium' | 'high';
}

export interface ResourceObjective {
  type: 'cost_reduction' | 'performance_improvement' | 'capacity_optimization';
  target: number;
  unit: string;
  timeframe: string;
  priority: number;
}

// Optimization Result Types
export interface ResourceOptimization {
  id: string;
  strategy: ResourceOptimizationStrategy;
  currentState: ResourceState;
  optimizedState: ResourceState;
  changes: ResourceChange[];
  impact: OptimizationImpact;
  implementation: ResourceImplementationPlan;
  validation: OptimizationValidation;
}

export interface ResourceChange {
  resourceId: string;
  type: 'resize' | 'terminate' | 'migrate' | 'reconfigure';
  from: ResourceConfiguration;
  to: ResourceConfiguration;
  impact: ChangeImpact;
  complexity: 'low' | 'medium' | 'high';
  risk: 'low' | 'medium' | 'high';
}

export interface OptimizationImpact {
  costSavings: CostAmount;
  performanceChange: Record<string, number>;
  capacityChange: Record<string, number>;
  utilizationImprovement: Record<string, number>;
  riskAssessment: RiskAssessment;
}

// Resource Allocation Types
export interface ResourceAllocation {
  resources: AllocationDetail[];
  totalCost: CostAmount;
  efficiency: number;
  utilization: Record<string, number>;
  constraints: ConstraintStatus[];
}

export interface AllocationDetail {
  resourceId: string;
  allocation: ResourceConfiguration;
  cost: CostAmount;
  utilization: Record<string, number>;
  efficiency: number;
}

export interface ConstraintStatus {
  constraint: string;
  status: 'satisfied' | 'violated' | 'at_risk';
  value: ConfigurationValue;
  limit: ConfigurationValue;
}

// Implementation Planning Types
export interface ResourceImplementationPlan {
  phases: ImplementationPhase[];
  timeline: string;
  dependencies: Dependency[];
  validationChecks: ValidationCheck[];
  rollbackPlan: RollbackPlan;
}

export interface ImplementationPhase {
  id: string;
  name: string;
  description: string;
  tasks: ImplementationTask[];
  duration: string;
  prerequisites: string[];
  deliverables: string[];
}

export interface ImplementationTask {
  id: string;
  name: string;
  type: 'automated' | 'manual' | 'approval';
  description: string;
  assignee: string;
  duration: string;
  dependencies: string[];
  validation: string[];
}

export interface Dependency {
  id: string;
  type: 'resource' | 'approval' | 'external';
  description: string;
  status: 'pending' | 'available' | 'blocked';
}

export interface ValidationCheck {
  id: string;
  name: string;
  type: 'pre' | 'post' | 'continuous';
  criteria: string[];
  automated: boolean;
  frequency?: string;
}

export interface RollbackPlan {
  triggers: string[];
  procedures: RollbackProcedure[];
  timeline: string;
  dataBackup: string[];
}

export interface RollbackProcedure {
  step: number;
  description: string;
  automated: boolean;
  validation: string;
}

// Validation Types
export interface OptimizationValidation {
  status: 'passed' | 'failed' | 'partial';
  checks: ValidationResult[];
  score: number;
  issues: string[];
}

export interface ValidationResult {
  check: string;
  status: 'passed' | 'failed' | 'warning';
  details: string;
  timestamp: string;
}