/**
 * FinOps Resource Discovery and Inventory Types
 * 
 * Type definitions for resource discovery, inventory management, and utilization tracking.
 * Covers resource types, metrics, thresholds, and analysis scope configuration.
 * 
 * Generated by CC (Claude Code) - Modularized from resource-optimization.ts
 */

// Resource Discovery and Inventory Types
export interface ResourceType {
  type: 'compute' | 'storage' | 'network' | 'database' | 'container' | 'serverless';
  subType?: string;
  provider: string;
  region?: string;
  family?: string;
}

export interface UtilizationMetric {
  name: string;
  type: 'cpu' | 'memory' | 'disk' | 'network' | 'iops' | 'bandwidth' | 'custom';
  aggregation: 'avg' | 'max' | 'min' | 'p95' | 'p99';
  unit: string;
  target?: number;
}

export interface UtilizationThreshold {
  metric: string;
  underutilized: number;
  overutilized: number;
  optimal: {
    min: number;
    max: number;
  };
  critical?: number;
}

export interface ResourceAnalysisScope {
  resourceTypes: ResourceType[];
  accounts: string[];
  regions: string[];
  projects: string[];
  environments: string[];
  tags: Record<string, string>;
}

export interface ResourceUtilization {
  metrics: UtilizationMetricValue[];
  overallScore: number;
  category: 'underutilized' | 'optimal' | 'overutilized' | 'unknown';
  patterns: UtilizationPattern[];
  peaks: UtilizationPeak[];
}

export interface UtilizationMetricValue {
  metric: string;
  current: number;
  average: number;
  peak: number;
  minimum: number;
  trend: 'increasing' | 'decreasing' | 'stable';
  threshold: UtilizationThreshold;
}

export interface UtilizationPattern {
  type: 'daily' | 'weekly' | 'monthly' | 'seasonal' | 'irregular';
  description: string;
  confidence: number;
  predictability: number;
}

export interface UtilizationPeak {
  timestamp: string;
  duration: string;
  metrics: Record<string, number>;
  trigger: string;
  frequency: 'rare' | 'occasional' | 'regular' | 'constant';
}

export interface UtilizationTrend {
  resourceId: string;
  metric: string;
  direction: 'increasing' | 'decreasing' | 'stable' | 'cyclical';
  rate: number;
  confidence: number;
  timeframe: string;
  projectedImpact: string;
}

export interface UtilizationAnomaly {
  resourceId: string;
  metric: string;
  timestamp: string;
  type: 'spike' | 'drop' | 'pattern_change' | 'outlier';
  severity: 'low' | 'medium' | 'high';
  deviation: number;
  possibleCauses: string[];
  impact: string;
}

export interface UnderutilizedResource {
  resourceId: string;
  name: string;
  type: ResourceType;
  cost: import('../cost-analysis').CostAmount;
  utilizationScore: number;
  wastedCapacity: Record<string, number>;
  potentialSavings: import('../cost-analysis').CostAmount;
  rightsizingOptions: RightsizingOption[];
  shutdownCandidate: boolean;
}

export interface OverutilizedResource {
  resourceId: string;
  name: string;
  type: ResourceType;
  cost: import('../cost-analysis').CostAmount;
  utilizationScore: number;
  constrainedMetrics: string[];
  performanceImpact: string;
  scalingOptions: ScalingOption[];
  urgency: 'low' | 'medium' | 'high' | 'critical';
}

export interface RightsizingOption {
  targetSize: string;
  estimatedSavings: import('../cost-analysis').CostAmount;
  performanceImpact: string;
  risk: 'low' | 'medium' | 'high';
  effort: 'low' | 'medium' | 'high';
}

export interface ScalingOption {
  type: 'vertical' | 'horizontal';
  recommendation: string;
  estimatedCost: import('../cost-analysis').CostAmount;
  performanceGain: string;
  complexity: 'low' | 'medium' | 'high';
}

export interface ResourceConfiguration {
  instanceType?: string;
  size?: string;
  cpu?: number;
  memory?: number;
  storage?: StorageConfiguration[];
  network?: NetworkConfiguration;
  tags: Record<string, string>;
  customProperties: Record<string, string | number | boolean | null>;
}

export interface StorageConfiguration {
  type: string;
  size: number;
  iops?: number;
  throughput?: number;
  encryption?: boolean;
}

export interface NetworkConfiguration {
  bandwidth: number;
  type: string;
  redundancy: boolean;
  encryption?: boolean;
}

export interface ResourceEfficiency {
  overall: number;
  byType: Record<string, number>;
  byRegion: Record<string, number>;
  byProject: Record<string, number>;
  trend: 'improving' | 'degrading' | 'stable';
}