"""enhance_asset_inventory_with_workflow_tracking

Revision ID: 00fc146d4abe
Revises: 43d83e459875
Create Date: 2025-05-31 17:42:13.159695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00fc146d4abe'
down_revision = '43d83e459875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_page'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_feedback_summaries_feedback_type'), table_name='feedback_summaries')
    op.drop_index(op.f('ix_feedback_summaries_id'), table_name='feedback_summaries')
    op.drop_index(op.f('ix_feedback_summaries_page'), table_name='feedback_summaries')
    op.drop_table('feedback_summaries')
    op.add_column('asset_dependencies', sa.Column('dependency_strength', sa.String(length=50), nullable=True))
    op.add_column('asset_dependencies', sa.Column('port_number', sa.Integer(), nullable=True))
    op.add_column('asset_dependencies', sa.Column('protocol', sa.String(length=50), nullable=True))
    op.add_column('asset_dependencies', sa.Column('client_account_id', sa.UUID(), nullable=True))
    op.add_column('asset_dependencies', sa.Column('engagement_id', sa.UUID(), nullable=True))
    op.add_column('asset_dependencies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('asset_dependencies', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('asset_dependencies', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('asset_dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_index(op.f('ix_asset_dependencies_id'), table_name='asset_dependencies')
    op.create_foreign_key(None, 'asset_dependencies', 'engagements', ['engagement_id'], ['id'])
    op.create_foreign_key(None, 'asset_dependencies', 'client_accounts', ['client_account_id'], ['id'])
    op.add_column('assets', sa.Column('client_account_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('engagement_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('asset_name', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('intelligent_asset_type', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('hardware_type', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('business_owner', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('technical_owner', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('application_id', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('application_version', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('programming_language', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('framework', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('database_type', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('cloud_readiness_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('modernization_complexity', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('tech_debt_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('server_dependencies', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('application_dependencies', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('database_dependencies', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('network_dependencies', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('estimated_monthly_cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('license_cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('support_cost', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('security_classification', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('compliance_frameworks', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('vulnerability_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('sixr_ready', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('estimated_migration_effort', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('recommended_6r_strategy', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('strategy_confidence', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('strategy_rationale', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('discovery_status', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('mapping_status', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('cleanup_status', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('assessment_readiness', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('completeness_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('missing_critical_fields', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('data_quality_issues', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('ai_analysis_result', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('last_ai_analysis', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('source_system', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('source_file', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('import_batch_id', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('custom_attributes', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.alter_column('assets', 'asset_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('assets', 'migration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assets', 'operating_system',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('assets', 'os_version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('assets', 'business_criticality',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('assets', 'compliance_requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('assets', 'migration_priority',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('assets', 'migration_complexity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_assets_application_id'), 'assets', ['application_id'], unique=False)
    op.create_index(op.f('ix_assets_assessment_readiness'), 'assets', ['assessment_readiness'], unique=False)
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_index(op.f('ix_assets_asset_name'), 'assets', ['asset_name'], unique=False)
    op.create_index(op.f('ix_assets_business_criticality'), 'assets', ['business_criticality'], unique=False)
    op.create_index(op.f('ix_assets_cleanup_status'), 'assets', ['cleanup_status'], unique=False)
    op.create_index(op.f('ix_assets_department'), 'assets', ['department'], unique=False)
    op.create_index(op.f('ix_assets_discovery_status'), 'assets', ['discovery_status'], unique=False)
    op.create_index(op.f('ix_assets_environment'), 'assets', ['environment'], unique=False)
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_import_batch_id'), 'assets', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_assets_intelligent_asset_type'), 'assets', ['intelligent_asset_type'], unique=False)
    op.create_index(op.f('ix_assets_mapping_status'), 'assets', ['mapping_status'], unique=False)
    op.create_foreign_key(None, 'assets', 'client_accounts', ['client_account_id'], ['id'])
    op.create_foreign_key(None, 'assets', 'engagements', ['engagement_id'], ['id'])
    op.add_column('import_field_mappings', sa.Column('transformation_logic', sa.JSON(), nullable=True))
    op.drop_column('import_field_mappings', 'transformation_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_field_mappings', sa.Column('transformation_rule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('import_field_mappings', 'transformation_logic')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_mapping_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_intelligent_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_import_batch_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_index(op.f('ix_assets_environment'), table_name='assets')
    op.drop_index(op.f('ix_assets_discovery_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_department'), table_name='assets')
    op.drop_index(op.f('ix_assets_cleanup_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_business_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_assessment_readiness'), table_name='assets')
    op.drop_index(op.f('ix_assets_application_id'), table_name='assets')
    op.alter_column('assets', 'migration_complexity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('assets', 'migration_priority',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assets', 'compliance_requirements',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('assets', 'business_criticality',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('assets', 'os_version',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('assets', 'operating_system',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('assets', 'migration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assets', 'asset_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('assets', 'updated_by')
    op.drop_column('assets', 'created_by')
    op.drop_column('assets', 'custom_attributes')
    op.drop_column('assets', 'import_batch_id')
    op.drop_column('assets', 'source_file')
    op.drop_column('assets', 'source_system')
    op.drop_column('assets', 'last_ai_analysis')
    op.drop_column('assets', 'ai_confidence_score')
    op.drop_column('assets', 'ai_analysis_result')
    op.drop_column('assets', 'data_quality_issues')
    op.drop_column('assets', 'missing_critical_fields')
    op.drop_column('assets', 'quality_score')
    op.drop_column('assets', 'completeness_score')
    op.drop_column('assets', 'assessment_readiness')
    op.drop_column('assets', 'cleanup_status')
    op.drop_column('assets', 'mapping_status')
    op.drop_column('assets', 'discovery_status')
    op.drop_column('assets', 'strategy_rationale')
    op.drop_column('assets', 'strategy_confidence')
    op.drop_column('assets', 'recommended_6r_strategy')
    op.drop_column('assets', 'estimated_migration_effort')
    op.drop_column('assets', 'sixr_ready')
    op.drop_column('assets', 'vulnerability_score')
    op.drop_column('assets', 'compliance_frameworks')
    op.drop_column('assets', 'security_classification')
    op.drop_column('assets', 'support_cost')
    op.drop_column('assets', 'license_cost')
    op.drop_column('assets', 'estimated_monthly_cost')
    op.drop_column('assets', 'network_dependencies')
    op.drop_column('assets', 'database_dependencies')
    op.drop_column('assets', 'application_dependencies')
    op.drop_column('assets', 'server_dependencies')
    op.drop_column('assets', 'tech_debt_score')
    op.drop_column('assets', 'modernization_complexity')
    op.drop_column('assets', 'cloud_readiness_score')
    op.drop_column('assets', 'database_type')
    op.drop_column('assets', 'framework')
    op.drop_column('assets', 'programming_language')
    op.drop_column('assets', 'application_version')
    op.drop_column('assets', 'application_id')
    op.drop_column('assets', 'department')
    op.drop_column('assets', 'technical_owner')
    op.drop_column('assets', 'business_owner')
    op.drop_column('assets', 'hardware_type')
    op.drop_column('assets', 'intelligent_asset_type')
    op.drop_column('assets', 'asset_name')
    op.drop_column('assets', 'engagement_id')
    op.drop_column('assets', 'client_account_id')
    op.drop_constraint(None, 'asset_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'asset_dependencies', type_='foreignkey')
    op.create_index(op.f('ix_asset_dependencies_id'), 'asset_dependencies', ['id'], unique=False)
    op.alter_column('asset_dependencies', 'dependency_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('asset_dependencies', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('asset_dependencies', 'created_by')
    op.drop_column('asset_dependencies', 'created_at')
    op.drop_column('asset_dependencies', 'engagement_id')
    op.drop_column('asset_dependencies', 'client_account_id')
    op.drop_column('asset_dependencies', 'protocol')
    op.drop_column('asset_dependencies', 'port_number')
    op.drop_column('asset_dependencies', 'dependency_strength')
    op.create_table('feedback_summaries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('time_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('total_feedback', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status_counts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rating_distribution', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category_counts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('feedback_trend', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rating_trend', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('client_account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('engagement_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_calculated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('calculation_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('feedback_summaries_client_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('feedback_summaries_engagement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_summaries_pkey'))
    )
    op.create_index(op.f('ix_feedback_summaries_page'), 'feedback_summaries', ['page'], unique=False)
    op.create_index(op.f('ix_feedback_summaries_id'), 'feedback_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_summaries_feedback_type'), 'feedback_summaries', ['feedback_type'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('page', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('breadcrumb', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('original_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_corrections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('asset_type_override', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_timestamp', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('client_account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('engagement_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('learning_patterns_extracted', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('feedback_client_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('feedback_engagement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_index(op.f('ix_feedback_page'), 'feedback', ['page'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    # ### end Alembic commands ### 