"""add_missing_seed_data_for_roles_and_profiles

Revision ID: 508e8589c9d0
Revises: 2c58fa60c0a4
Create Date: 2025-06-09 00:17:29.326635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, text
from sqlalchemy import String, Boolean, DateTime, JSON

# revision identifiers, used by Alembic.
revision = '508e8589c9d0'
down_revision = '2c58fa60c0a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint('_user_client_account_uc', 'user_account_associations', ['user_id', 'client_account_id'])
    # ### end Alembic commands ###

    # Manually added data seeding
    conn = op.get_bind()
    admin_user_result = conn.execute(text("SELECT id FROM users WHERE email = 'admin@democorp.com'")).scalar_one_or_none()
    
    if admin_user_result:
        admin_user_id = str(admin_user_result)
        op.execute(f"""
            INSERT INTO user_roles (id, user_id, role_type, role_name, description, permissions, assigned_by)
            VALUES
                (gen_random_uuid(), '{admin_user_id}', 'platform_admin', 'Platform Administrator', 'Full access to all platform features', '{{"system": ["all"]}}'::jsonb, '{admin_user_id}')
            ON CONFLICT (id) DO NOTHING;
        """)

    demo_user_result = conn.execute(text("SELECT id FROM users WHERE email = 'demo@democorp.com'")).scalar_one_or_none()
    if demo_user_result:
        demo_user_id = str(demo_user_result)
        op.execute(f"""
            INSERT INTO user_roles (id, user_id, role_type, role_name, description, permissions, assigned_by)
            VALUES
                (gen_random_uuid(), '{demo_user_id}', 'analyst', 'Analyst', 'Access to assigned engagements and features', '{{"engagements": ["read"]}}'::jsonb, '{admin_user_id}')
            ON CONFLICT (id) DO NOTHING;
        """)

    op.execute("""
        -- Insert User Profiles for mock users, linking to existing users
        -- Note: This assumes the mock users from init_db.py exist.
        INSERT INTO user_profiles (user_id, registration_reason, organization, role_description, status)
        SELECT id, 'Default admin user profile', 'DemoCorp', 'Administrator', 'active'
        FROM users WHERE email = 'admin@democorp.com'
        ON CONFLICT (user_id) DO NOTHING;
    """)

    op.execute("""
        INSERT INTO user_profiles (user_id, registration_reason, organization, role_description, status)
        SELECT id, 'Default demo user profile', 'DemoCorp', 'Analyst', 'active'
        FROM users WHERE email = 'demo@democorp.com'
        ON CONFLICT (user_id) DO NOTHING;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_client_account_uc', 'user_account_associations', type_='unique')
    op.alter_column('client_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###

    # Manual data removal - this is optional but good practice
    op.execute("DELETE FROM user_roles WHERE user_id IN (SELECT id FROM users WHERE email IN ('admin@democorp.com', 'demo@democorp.com'))")
    op.execute("DELETE FROM user_profiles WHERE user_id IN (SELECT id FROM users WHERE email IN ('admin@democorp.com', 'demo@democorp.com'))") 