"""Add workflow_states table for persistent discovery flow

Revision ID: a4c212b400af
Revises: 3622d9577edc
Create Date: 2025-06-14 20:29:40.624502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4c212b400af'
down_revision = '3622d9577edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_states_client_account_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_engagement_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_session_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_status'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_workflow_type'), table_name='workflow_states')
    op.drop_table('workflow_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('engagement_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('current_phase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], name=op.f('workflow_states_client_account_id_fkey')),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('workflow_states_engagement_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['data_import_sessions.id'], name=op.f('workflow_states_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_states_pkey'))
    )
    op.create_index(op.f('ix_workflow_states_workflow_type'), 'workflow_states', ['workflow_type'], unique=False)
    op.create_index(op.f('ix_workflow_states_status'), 'workflow_states', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_states_session_id'), 'workflow_states', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_engagement_id'), 'workflow_states', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_client_account_id'), 'workflow_states', ['client_account_id'], unique=False)
    # ### end Alembic commands ### 