"""Add data import tables for Discovery phase persistence

Revision ID: f802528ca6c1
Revises: e5988c596062
Create Date: 2025-05-30 23:51:56.234127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f802528ca6c1'
down_revision = 'e5988c596062'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 