/**
 * Migration Strategy Planning Types
 * 
 * Type definitions for migration strategy development, analysis, and comparison.
 * Covers strategy creation, alternatives evaluation, feasibility assessment,
 * and strategy comparison functionality.
 * 
 * Generated by CC - Claude Code
 * 
 * @deprecated This file has been modularized. Import from ./strategy/ instead.
 */

// Re-export all types from the modular structure
export type * from './strategy';