/**
 * Risk Quantification and Modeling Types
 * 
 * Type definitions for risk quantification, statistical modeling,
 * and mathematical analysis of risk scenarios and outcomes.
 * 
 * Generated by CC - Claude Code
 */

// Quantification and Simulation Types
export interface RiskQuantification {
  method: 'monte_carlo' | 'sensitivity' | 'scenario' | 'decision_tree' | 'real_options';
  model: QuantificationModel;
  parameters: QuantificationParameter[];
  distributions: ProbabilityDistribution[];
  correlations: RiskCorrelation[];
  results: QuantificationResult[];
  sensitivity: SensitivityAnalysis;
  confidence: ConfidenceInterval[];
}

export interface RiskSimulation {
  type: 'monte_carlo' | 'discrete_event' | 'agent_based' | 'system_dynamics';
  iterations: number;
  scenarios: SimulationScenario[];
  parameters: SimulationParameter[];
  results: SimulationResult[];
  statistics: SimulationStatistics;
  confidence: number;
  validation: SimulationValidation;
}

export interface MitigationEffectiveness {
  overallEffectiveness: number;
  byRisk: RiskEffectiveness[];
  byCategory: CategoryEffectiveness[];
  byStrategy: StrategyEffectiveness[];
  costEffectiveness: CostEffectiveness[];
  trends: EffectivenessTrend[];
  benchmarks: EffectivenessBenchmark[];
}

// Model Structure Types
export interface QuantificationModel {
  type: 'probabilistic' | 'deterministic' | 'fuzzy' | 'bayesian';
  structure: ModelStructure;
  parameters: ModelParameter[];
  relationships: ModelRelationship[];
  validation: ModelValidation;
}

export interface QuantificationParameter {
  parameter: string;
  type: 'input' | 'output' | 'intermediate';
  distribution: string;
  value: number;
  uncertainty: number;
}

export interface RiskCorrelation {
  risk1: string;
  risk2: string;
  correlation: number;
  type: 'positive' | 'negative' | 'neutral';
  confidence: number;
}

export interface QuantificationResult {
  metric: string;
  value: number;
  distribution: string;
  confidence: ConfidenceInterval;
  sensitivity: number;
}

export interface SensitivityAnalysis {
  variables: SensitivityVariable[];
  results: SensitivityResult[];
  ranking: SensitivityRanking[];
  tornado: TornadoChart;
}

export interface ConfidenceInterval {
  level: number;
  lower: number;
  upper: number;
  mean: number;
  median: number;
}

// Simulation Types
export interface SimulationScenario {
  scenario: string;
  probability: number;
  variables: ScenarioVariable[];
  outcomes: string[];
}

export interface SimulationParameter {
  parameter: string;
  distribution: string;
  bounds: ParameterBounds;
  correlation: string[];
}

export interface SimulationResult {
  metric: string;
  statistics: ResultStatistics;
  distribution: ResultDistribution;
  percentiles: Percentile[];
}

export interface SimulationStatistics {
  mean: number;
  median: number;
  mode: number;
  standardDeviation: number;
  variance: number;
  skewness: number;
  kurtosis: number;
}

export interface SimulationValidation {
  method: 'back_testing' | 'cross_validation' | 'expert_review';
  results: ValidationResult[];
  confidence: number;
  limitations: string[];
}

// Distribution Types
export interface ProbabilityDistribution {
  variable: string;
  distribution: 'normal' | 'lognormal' | 'uniform' | 'triangular' | 'beta' | 'gamma' | 'discrete';
  parameters: DistributionParameter[];
  bounds: DistributionBounds;
  correlation: DistributionCorrelation[];
  validation: DistributionValidation;
}

export interface DistributionParameter {
  parameter: string;
  value: number;
  description: string;
}

export interface DistributionBounds {
  minimum: number;
  maximum: number;
  truncation: boolean;
}

export interface DistributionCorrelation {
  variable: string;
  correlation: number;
  type: string;
}

export interface DistributionValidation {
  test: string;
  result: boolean;
  p_value: number;
  confidence: number;
}

// Effectiveness Types
export interface RiskEffectiveness {
  riskId: string;
  baseline: number;
  current: number;
  target: number;
  effectiveness: number;
  trend: 'improving' | 'stable' | 'deteriorating';
}

export interface CategoryEffectiveness {
  category: string;
  effectiveness: number;
  riskCount: number;
  trend: string;
}

export interface StrategyEffectiveness {
  strategy: string;
  effectiveness: number;
  cost: number;
  benefit: number;
  roi: number;
}

export interface CostEffectiveness {
  intervention: string;
  cost: number;
  benefit: number;
  ratio: number;
  ranking: number;
}

export interface EffectivenessTrend {
  metric: string;
  trend: 'improving' | 'stable' | 'deteriorating';
  rate: number;
  confidence: number;
}

export interface EffectivenessBenchmark {
  metric: string;
  internal: number;
  external: number;
  industry: number;
  best_practice: number;
}

// Model Detail Types
export interface ModelStructure {
  type: string;
  components: string[];
  relationships: string[];
  hierarchy: string[];
}

export interface ModelParameter {
  parameter: string;
  type: string;
  value: any;
  uncertainty: number;
}

export interface ModelRelationship {
  from: string;
  to: string;
  type: string;
  strength: number;
}

export interface ModelValidation {
  method: string[];
  criteria: string[];
  results: ValidationResult[];
  confidence: number;
}

export interface ValidationResult {
  test: string;
  result: boolean;
  confidence: number;
  limitations: string[];
}

// Sensitivity Analysis Types
export interface SensitivityVariable {
  variable: string;
  impact: number;
  ranking: number;
  elasticity: number;
}

export interface SensitivityResult {
  variable: string;
  impact: number;
  range: SensitivityRange;
  confidence: number;
}

export interface SensitivityRanking {
  rank: number;
  variable: string;
  impact: number;
  percentage: number;
}

export interface TornadoChart {
  variables: TornadoVariable[];
  baseline: number;
  range: TornadoRange;
}

export interface TornadoVariable {
  variable: string;
  low_impact: number;
  high_impact: number;
  range: number;
}

export interface TornadoRange {
  minimum: number;
  maximum: number;
  baseline: number;
}

export interface SensitivityRange {
  low: number;
  high: number;
  impact: number;
}

// Statistical Types
export interface ParameterBounds {
  minimum: number;
  maximum: number;
  default: number;
}

export interface ResultDistribution {
  distribution: string;
  parameters: DistributionParameter[];
  percentiles: Percentile[];
  statistics: DistributionStatistics;
}

export interface Percentile {
  percentile: number;
  value: number;
}

export interface DistributionStatistics {
  mean: number;
  median: number;
  mode: number;
  variance: number;
  standardDeviation: number;
  skewness: number;
  kurtosis: number;
}

export interface ResultStatistics {
  mean: number;
  median: number;
  mode: number;
  standardDeviation: number;
  variance: number;
  skewness: number;
  kurtosis: number;
}

export interface ScenarioVariable {
  variable: string;
  value: number;
  range: VariableRange;
  distribution: string;
}

export interface VariableRange {
  minimum: number;
  maximum: number;
  mean: number;
  standardDeviation: number;
}