/**
 * Communication Messages Types
 *
 * Type definitions for communication messages, content, delivery,
 * and lifecycle management within communication planning.
 *
 * Generated by CC - Claude Code
 */

export interface CommunicationMessage {
  message: string;
  type: 'announcement' | 'update' | 'request' | 'feedback' | 'decision' | 'education';
  purpose: string;
  audience: string[];
  priority: 'low' | 'medium' | 'high' | 'urgent';
  content: MessageContent;
  delivery: MessageDelivery;
  feedback: MessageFeedback;
  lifecycle: MessageLifecycle;
}

export interface MessageContent {
  key_points: string[];
  structure: ContentStructure;
  tone: string;
  style: string;
  format: string[];
  multimedia: ContentMultimedia[];
  accessibility: ContentAccessibility;
}

export interface ContentStructure {
  opening: string;
  body: string[];
  closing: string;
  call_to_action: string;
  supporting_materials: string[];
}

export interface ContentMultimedia {
  type: 'image' | 'video' | 'audio' | 'infographic' | 'animation';
  purpose: string;
  format: string;
  accessibility: string;
  approval: string;
}

export interface ContentAccessibility {
  languages: string[];
  formats: string[];
  accommodations: string[];
  compliance: string[];
}

export interface MessageDelivery {
  channels: string[];
  timing: DeliveryTiming;
  sequencing: DeliverySequencing;
  personalization: DeliveryPersonalization;
  tracking: DeliveryTracking;
}

export interface DeliveryTiming {
  schedule: string;
  time_zone: string;
  frequency: string;
  duration: string;
  reminders: string[];
}

export interface DeliverySequencing {
  order: string[];
  dependencies: string[];
  conditions: string[];
  automation: string;
}

export interface DeliveryPersonalization {
  level: 'none' | 'basic' | 'advanced' | 'dynamic';
  criteria: string[];
  content_variants: string[];
  targeting: string;
}

export interface DeliveryTracking {
  metrics: string[];
  methods: string[];
  reporting: string;
  analysis: string;
  optimization: string;
}

export interface MessageFeedback {
  collection: FeedbackCollection;
  processing: FeedbackProcessing;
  response: FeedbackResponse;
  integration: FeedbackIntegration;
}

export interface FeedbackCollection {
  mechanisms: string[];
  channels: string[];
  prompts: string[];
  incentives: string[];
  barriers: string[];
}

export interface FeedbackProcessing {
  analysis: string;
  categorization: string[];
  prioritization: string;
  routing: string;
  escalation: string;
}

export interface FeedbackResponse {
  acknowledgment: string;
  response_time: string;
  format: string[];
  personalization: string;
  follow_up: string;
}

export interface FeedbackIntegration {
  improvement: string;
  planning: string;
  reporting: string;
  knowledge: string;
}

export interface MessageLifecycle {
  development: string;
  approval: string;
  deployment: string;
  monitoring: string;
  optimization: string;
  retirement: string;
}
