"""
AWS-specific data transformation logic.

Generated by CC (Claude Code)
"""

import logging
from typing import Any, Dict

logger = logging.getLogger(__name__)


class AWSTransformer:
    """Transformer for AWS-specific data formats."""

    def transform(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Transform AWS specific data formats."""
        transformed = {}

        for key, value in data.items():
            # Handle AWS tags
            if key == "Tags" and isinstance(value, list):
                transformed["tags"] = {tag["Key"]: tag["Value"] for tag in value}
            # Handle AWS instance state
            elif key == "State" and isinstance(value, dict):
                transformed["status"] = value.get("Name", "unknown")
            else:
                transformed[key] = value

        return transformed
