# Keep the original standard fields as fallback
# NOTE: This list is only used if database schema query fails
STANDARD_TARGET_FIELDS = [
    # Identification fields
    {
        "name": "name",
        "type": "string",
        "required": True,
        "description": "Asset name or identifier",
        "category": "identification",
    },
    {
        "name": "hostname",
        "type": "string",
        "required": True,
        "description": "Asset hostname",
        "category": "identification",
    },
    {
        "name": "fqdn",
        "type": "string",
        "required": False,
        "description": "Fully qualified domain name",
        "category": "identification",
    },
    {
        "name": "asset_name",
        "type": "string",
        "required": False,
        "description": "Friendly asset name",
        "category": "identification",
    },
    # Technical fields
    {
        "name": "asset_type",
        "type": "enum",
        "required": True,
        "description": "Type of asset (server, vm, container, etc.)",
        "category": "technical",
    },
    {
        "name": "operating_system",
        "type": "string",
        "required": True,
        "description": "Operating system name and version",
        "category": "technical",
    },
    {
        "name": "os_version",
        "type": "string",
        "required": False,
        "description": "Detailed OS version",
        "category": "technical",
    },
    {
        "name": "cpu_cores",
        "type": "integer",
        "required": True,
        "description": "Number of CPU cores",
        "category": "technical",
    },
    {
        "name": "memory_gb",
        "type": "number",
        "required": True,
        "description": "Memory in gigabytes",
        "category": "technical",
    },
    {
        "name": "storage_gb",
        "type": "number",
        "required": False,
        "description": "Total storage in gigabytes",
        "category": "technical",
    },
    {
        "name": "architecture",
        "type": "string",
        "required": False,
        "description": "System architecture (x86_64, arm64, etc.)",
        "category": "technical",
    },
    # Network fields
    {
        "name": "ip_address",
        "type": "string",
        "required": True,
        "description": "Primary IP address",
        "category": "network",
    },
    {
        "name": "mac_address",
        "type": "string",
        "required": False,
        "description": "MAC address",
        "category": "network",
    },
    {
        "name": "subnet",
        "type": "string",
        "required": False,
        "description": "Network subnet",
        "category": "network",
    },
    {
        "name": "vlan",
        "type": "string",
        "required": False,
        "description": "VLAN identifier",
        "category": "network",
    },
    {
        "name": "dns_name",
        "type": "string",
        "required": False,
        "description": "DNS name",
        "category": "network",
    },
    # Environment fields
    {
        "name": "environment",
        "type": "enum",
        "required": True,
        "description": "Environment (production, staging, dev, etc.)",
        "category": "environment",
    },
    {
        "name": "datacenter",
        "type": "string",
        "required": False,
        "description": "Datacenter location",
        "category": "environment",
    },
    {
        "name": "region",
        "type": "string",
        "required": False,
        "description": "Geographic region",
        "category": "environment",
    },
    {
        "name": "availability_zone",
        "type": "string",
        "required": False,
        "description": "Availability zone",
        "category": "environment",
    },
    {
        "name": "rack",
        "type": "string",
        "required": False,
        "description": "Rack location",
        "category": "environment",
    },
    # Business fields
    {
        "name": "owner",
        "type": "string",
        "required": True,
        "description": "Technical owner",
        "category": "business",
    },
    {
        "name": "business_owner",
        "type": "string",
        "required": False,
        "description": "Business owner",
        "category": "business",
    },
    {
        "name": "department",
        "type": "string",
        "required": False,
        "description": "Department",
        "category": "business",
    },
    {
        "name": "cost_center",
        "type": "string",
        "required": False,
        "description": "Cost center",
        "category": "business",
    },
    {
        "name": "business_unit",
        "type": "string",
        "required": False,
        "description": "Business unit",
        "category": "business",
    },
    {
        "name": "application",
        "type": "string",
        "required": False,
        "description": "Application name",
        "category": "business",
    },
    {
        "name": "criticality",
        "type": "enum",
        "required": False,
        "description": "Business criticality level",
        "category": "business",
    },
    # Cloud readiness fields
    {
        "name": "virtualization_platform",
        "type": "string",
        "required": False,
        "description": "Current virtualization platform",
        "category": "cloud_readiness",
    },
    {
        "name": "is_virtual",
        "type": "boolean",
        "required": False,
        "description": "Is this a virtual machine",
        "category": "cloud_readiness",
    },
    {
        "name": "migration_readiness",
        "type": "enum",
        "required": False,
        "description": "Migration readiness status",
        "category": "cloud_readiness",
    },
    {
        "name": "target_cloud",
        "type": "string",
        "required": False,
        "description": "Target cloud platform",
        "category": "cloud_readiness",
    },
    # Metadata fields
    {
        "name": "created_date",
        "type": "datetime",
        "required": False,
        "description": "Asset creation date",
        "category": "metadata",
    },
    {
        "name": "last_updated",
        "type": "datetime",
        "required": False,
        "description": "Last update timestamp",
        "category": "metadata",
    },
    {
        "name": "tags",
        "type": "array",
        "required": False,
        "description": "Asset tags",
        "category": "metadata",
    },
    {
        "name": "notes",
        "type": "text",
        "required": False,
        "description": "Additional notes",
        "category": "metadata",
    },
]
