/**
 * Resource Types and Constraints Module
 * 
 * Resource type definitions, constraints, requirements, and
 * detailed specification types for resource planning.
 * 
 * Generated by CC - Claude Code
 */

import type { FlexibilityLevel } from './supporting-types';

// Resource Types and Categories
export interface ResourceType {
  id: string;
  name: string;
  category: 'human' | 'technical' | 'physical' | 'financial';
  subcategory: string;
  description: string;
  unit: string;
  rateType: 'hourly' | 'daily' | 'weekly' | 'monthly' | 'fixed';
  skillsRequired: string[];
  availability: TypeAvailability;
  cost: TypeCost;
  substitutes: string[];
}

export interface SkillRequirement {
  skill: string;
  level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  criticality: 'nice_to_have' | 'important' | 'required' | 'critical';
  quantity: number;
  duration: number;
  certification?: string;
  experience?: number;
  alternatives: string[];
  development: SkillDevelopmentOption[];
}

export interface AvailabilityConstraint {
  id: string;
  type: 'time' | 'location' | 'skill' | 'capacity' | 'contract';
  resourceId?: string;
  resourceType?: string;
  description: string;
  startDate?: string;
  endDate?: string;
  impact: 'low' | 'medium' | 'high' | 'critical';
  workaround?: string;
  cost?: number;
}

export interface BudgetConstraint {
  id: string;
  type: 'total' | 'category' | 'period' | 'resource' | 'vendor';
  category?: string;
  limit: number;
  period?: string;
  currency: string;
  flexibility: 'fixed' | 'flexible' | 'negotiable';
  approval: string;
  escalation: string;
}

export interface RequiredSkill {
  skill: string;
  level: string;
  criticality: string;
  alternatives: string[];
}

export interface AvailabilityRequirement {
  startDate: string;
  endDate: string;
  allocation: number;
  flexibility: FlexibilityLevel;
  constraints: string[];
}

export interface CostRequirement {
  budgetCategory: string;
  maxCost: number;
  preferredCost: number;
  currency: string;
  billable: boolean;
}

export interface LocationRequirement {
  type: 'onsite' | 'remote' | 'hybrid';
  location?: string;
  timezone?: string;
  travelRequired?: boolean;
  flexibility: FlexibilityLevel;
}

export interface TimingRequirement {
  earliestStart: string;
  latestStart: string;
  earliestFinish: string;
  latestFinish: string;
  flexibility: FlexibilityLevel;
}

export interface FlexibilityOptions {
  schedule: FlexibilityLevel;
  location: FlexibilityLevel;
  scope: FlexibilityLevel;
  quality: FlexibilityLevel;
  cost: FlexibilityLevel;
}

export interface AlternativeResource {
  resourceId: string;
  resourceType: string;
  suitability: number;
  cost: number;
  availability: string;
  risks: string[];
}

export interface AllocationConstraint {
  type: string;
  description: string;
  impact: string;
  workaround?: string;
}

export interface TypeAvailability {
  total: number;
  available: number;
  allocated: number;
  utilization: number;
  constraints: string[];
}

export interface TypeCost {
  standard: number;
  minimum: number;
  maximum: number;
  currency: string;
  factors: CostFactor[];
}

export interface CostFactor {
  factor: string;
  impact: number;
  description: string;
}

export interface SkillDevelopmentOption {
  method: string;
  duration: number;
  cost: number;
  success: number;
  provider: string;
}

export interface ResourceConstraint {
  id: string;
  type: string;
  description: string;
  impact: string;
  flexibility: FlexibilityLevel;
  mitigation: string;
}

export interface ResourceAssumption {
  id: string;
  description: string;
  confidence: number;
  impact: string;
  validation: string;
  owner: string;
}

export interface ResourcePolicy {
  id: string;
  name: string;
  description: string;
  type: string;
  rules: PolicyRule[];
  exceptions: PolicyException[];
  compliance: boolean;
}

export interface PolicyRule {
  rule: string;
  description: string;
  mandatory: boolean;
  penalty: string;
}

export interface PolicyException {
  condition: string;
  approval: string;
  documentation: string;
  review: string;
}