"""
Utility functions for System Health Dashboard

This module contains utility functions and singleton management for the
System Health Dashboard.

Generated by CC (Claude Code)
"""

from .dashboard import SystemHealthDashboard

# Global singleton instance
_system_health_dashboard = None


def get_system_health_dashboard() -> SystemHealthDashboard:
    """Get singleton system health dashboard instance"""
    global _system_health_dashboard
    if _system_health_dashboard is None:
        _system_health_dashboard = SystemHealthDashboard()
    return _system_health_dashboard
