/**
 * Workstream Governance Types
 *
 * Type definitions for workstream governance structures and processes.
 *
 * Generated by CC - Claude Code
 */

export interface WorkstreamGovernance {
  structure: string;
  roles: GovernanceRole[];
  processes: GovernanceProcess[];
  reporting: GovernanceReporting;
  escalation: GovernanceEscalation;
  compliance: GovernanceCompliance;
}

export interface GovernanceRole {
  role: string;
  responsibilities: string[];
  authority: string[];
  reporting: string;
  escalation: string;
}

export interface GovernanceProcess {
  process: string;
  purpose: string;
  inputs: string[];
  activities: string[];
  outputs: string[];
  roles: string[];
  frequency: string;
}

export interface GovernanceReporting {
  frequency: string;
  format: string;
  content: string[];
  recipients: string[];
  escalation: string[];
}

export interface GovernanceEscalation {
  triggers: string[];
  process: string;
  timeline: string;
  authority: string;
  resolution: string;
}

export interface GovernanceCompliance {
  requirements: string[];
  monitoring: string;
  assessment: string;
  reporting: string;
  remediation: string;
}
