/**
 * Governance Types Module Index
 * 
 * Centralized exports for all governance-related type definitions,
 * providing a clean interface for importing governance types.
 * 
 * Generated by CC - Claude Code
 */

// Core Governance Framework
export {
  GovernanceFramework,
  GovernanceStructure,
  GovernanceEscalation,
} from './core';

// Re-export core relationship types explicitly to avoid conflicts
export type {
  GovernanceRelationship,
  RelationshipGovernance
} from './core';

// Hierarchy and Structure
export * from './hierarchy';

// Governance Bodies
export * from './committees';
export * from './boards';
export * from './councils';
export * from './offices';
export * from './governance-bodies';

// Roles and Responsibilities - export specific types to avoid duplicates
export {
  GovernanceRole,
  RolePerformance,
  RoleDevelopment,
  GovernanceResponsibility,
  ResponsibilityDelegation,
  GovernanceAuthority,
  AuthorityDelegation,
  AuthorityApproval,
  AuthorityReporting,
  AuthorityReview,
} from './roles-responsibilities';

// Policies and Standards - export specific types to avoid duplicates
export {
  GovernancePolicy,
  PolicyRule,
  PolicyException,
  PolicyProcedure,
  ProcedureStep,
  PolicyCompliance,
  PolicyEnforcement,
  PolicyLifecycle,
} from './policies-standards';

// Processes
export * from './processes';

// Compliance and Audit - export specific types to avoid duplicates
export {
  GovernanceCompliance,
  GovernanceAudit,
  AuditFramework,
  AuditSchedule,
  AuditScope,
  AuditMethodology,
  AuditFinding,
  AuditRecommendation,
  RecommendationImplementation,
  RecommendationMonitoring,
  AuditFollowUp,
  AuditIndependence,
} from './compliance-audit';

// Re-export shared compliance types explicitly
export type {
  ComplianceRequirement,
  ComplianceMonitoring,
  ComplianceAssessment,
  ComplianceReporting,
  ComplianceViolation,
  ComplianceRemediation,
} from './compliance-audit';

// Reporting and Communication - export specific types to avoid duplicates
export {
  GovernanceReporting,
  ReportingStructure,
  ReportingSchedule,
  ReportingDistribution,
  ReportingEscalation,
  ReportingQuality,
  GovernanceCommunication,
  CommunicationStrategy,
  CommunicationChannel,
  CommunicationProtocol,
  CommunicationStakeholder,
  CommunicationFeedback,
} from './reporting';

// Maturity and Improvement
export * from './maturity-improvement';

// Health and Status
export * from './health-status';