/**
 * Governance Office Types
 * 
 * Type definitions for governance offices, services, capabilities,
 * resource management, and office performance measurement.
 * 
 * Generated by CC - Claude Code
 */

export interface GovernanceOffice {
  id: string;
  name: string;
  type: 'pmo' | 'coe' | 'shared_service' | 'support' | 'coordination';
  purpose: string;
  services: OfficeService[];
  capabilities: OfficeCapability[];
  resources: OfficeResource[];
  performance: OfficePerformance;
  evolution: OfficeEvolution;
}

export interface OfficeService {
  service: string;
  description: string;
  scope: string[];
  delivery: ServiceDelivery;
  quality: ServiceQuality;
  performance: ServicePerformance;
}

export interface ServiceDelivery {
  model: string;
  channels: string[];
  processes: string[];
  standards: string[];
  automation: string;
}

export interface ServiceQuality {
  framework: string;
  standards: string[];
  metrics: string[];
  monitoring: string;
  improvement: string;
}

export interface ServicePerformance {
  metrics: string[];
  targets: string[];
  monitoring: string;
  reporting: string;
  optimization: string;
}

export interface OfficeCapability {
  capability: string;
  description: string;
  maturity: CapabilityMaturity;
  development: CapabilityDevelopment;
  utilization: CapabilityUtilization;
}

export interface CapabilityMaturity {
  current: 'initial' | 'developing' | 'defined' | 'managed' | 'optimizing';
  target: 'initial' | 'developing' | 'defined' | 'managed' | 'optimizing';
  gap: string[];
  roadmap: string;
}

export interface CapabilityDevelopment {
  approach: string;
  investments: string[];
  timeline: string;
  resources: string[];
  partnerships: string[];
}

export interface CapabilityUtilization {
  demand: string;
  capacity: string;
  allocation: string;
  optimization: string;
  scaling: string;
}

export interface OfficeResource {
  type: 'human' | 'technology' | 'financial' | 'physical';
  description: string;
  allocation: ResourceAllocation;
  utilization: ResourceUtilization;
  optimization: ResourceOptimization;
}

export interface ResourceAllocation {
  current: string;
  planned: string;
  demand: string;
  gaps: string[];
  conflicts: string[];
}

export interface ResourceUtilization {
  rate: number;
  trends: string[];
  efficiency: string;
  capacity: string;
  bottlenecks: string[];
}

export interface ResourceOptimization {
  opportunities: string[];
  initiatives: string[];
  benefits: string[];
  implementation: string;
  monitoring: string;
}

export interface OfficePerformance {
  framework: PerformanceFramework;
  measurement: PerformanceMeasurement;
  reporting: PerformanceReporting;
  improvement: PerformanceImprovement;
}

export interface PerformanceFramework {
  model: string;
  dimensions: string[];
  metrics: string[];
  targets: string[];
  benchmarks: string[];
}

export interface PerformanceMeasurement {
  methods: string[];
  frequency: string;
  automation: string;
  validation: string;
  analysis: string;
}

export interface PerformanceReporting {
  dashboards: string[];
  reports: string[];
  frequency: string;
  audience: string[];
  escalation: string;
}

export interface PerformanceImprovement {
  process: string;
  triggers: string[];
  methods: string[];
  implementation: string;
  monitoring: string;
}

export interface OfficeEvolution {
  strategy: string;
  roadmap: string;
  transformation: string;
  innovation: string;
  sustainability: string;
}