/**
 * Governance Reporting and Communication Types
 * 
 * Type definitions for reporting structures, communication strategies,
 * stakeholder management, and feedback mechanisms.
 * 
 * Generated by CC - Claude Code
 */

export interface GovernanceReporting {
  structure: ReportingStructure;
  schedules: ReportingSchedule[];
  formats: ReportingFormat[];
  content: ReportingContent[];
  distribution: ReportingDistribution[];
  escalation: ReportingEscalation;
  quality: ReportingQuality;
}

export interface ReportingStructure {
  hierarchy: string[];
  relationships: string[];
  consolidation: string;
  integration: string;
}

export interface ReportingSchedule {
  type: string;
  frequency: string;
  timing: string;
  recipients: string[];
  dependencies: string[];
}

export interface ReportingFormat {
  medium: 'written' | 'verbal' | 'dashboard' | 'presentation' | 'meeting';
  template: string;
  structure: string[];
  standards: string[];
}

export interface ReportingContent {
  category: string;
  elements: string[];
  metrics: string[];
  frequency: string;
  detail: 'summary' | 'detailed' | 'exception';
}

export interface ReportingDistribution {
  recipients: string[];
  channels: string[];
  format: string;
  timing: string;
  access: string[];
}

export interface ReportingEscalation {
  triggers: string[];
  process: string;
  timeline: string;
  recipients: string[];
}

export interface ReportingQuality {
  standards: string[];
  validation: string;
  accuracy: string;
  timeliness: string;
  completeness: string;
}

export interface GovernanceCommunication {
  strategy: CommunicationStrategy;
  channels: CommunicationChannel[];
  protocols: CommunicationProtocol[];
  stakeholders: CommunicationStakeholder[];
  feedback: CommunicationFeedback;
}

export interface CommunicationStrategy {
  objectives: string[];
  principles: string[];
  approach: string;
  measurement: string;
}

export interface CommunicationChannel {
  channel: string;
  purpose: string;
  audience: string[];
  frequency: string;
  format: string;
}

export interface CommunicationProtocol {
  protocol: string;
  purpose: string;
  rules: string[];
  procedures: string[];
  escalation: string;
}

export interface CommunicationStakeholder {
  stakeholder: string;
  interest: string;
  influence: string;
  preferences: string[];
  requirements: string[];
}

export interface CommunicationFeedback {
  mechanisms: string[];
  processing: string;
  response: string;
  improvement: string;
}