/**
 * Governance Roles and Responsibilities Types
 * 
 * Type definitions for governance roles, responsibilities, authorities,
 * delegation rules, and performance management.
 * 
 * Generated by CC - Claude Code
 */

import type { AuthorityLimit } from './hierarchy';

export interface GovernanceRole {
  role: string;
  level: string;
  scope: string[];
  responsibilities: string[];
  authorities: string[];
  accountabilities: string[];
  competencies: string[];
  reporting: string;
  performance: RolePerformance;
  development: RoleDevelopment;
}

export interface RolePerformance {
  expectations: string[];
  metrics: string[];
  evaluation: string;
  feedback: string;
  recognition: string;
}

export interface RoleDevelopment {
  requirements: string[];
  training: string[];
  mentoring: string;
  career: string;
  succession: string;
}

export interface GovernanceResponsibility {
  responsibility: string;
  description: string;
  scope: string;
  owner: string;
  authority: string;
  measurement: string;
  escalation: string;
  delegation: ResponsibilityDelegation;
}

export interface ResponsibilityDelegation {
  allowed: boolean;
  conditions: string[];
  process: string;
  accountability: string;
  monitoring: string;
}

export interface GovernanceAuthority {
  authority: string;
  scope: string[];
  limits: AuthorityLimit[];
  delegation: AuthorityDelegation[];
  approval: AuthorityApproval[];
  reporting: AuthorityReporting;
  review: AuthorityReview;
}

export interface AuthorityDelegation {
  to: string;
  scope: string[];
  conditions: string[];
  accountability: string;
  monitoring: string;
  review: string;
}

export interface AuthorityApproval {
  type: string;
  process: string;
  criteria: string[];
  documentation: string;
  review: string;
}

export interface AuthorityReporting {
  frequency: string;
  content: string[];
  recipients: string[];
  escalation: string;
}

export interface AuthorityReview {
  frequency: string;
  criteria: string[];
  process: string;
  adjustment: string;
}