/**
 * Monitoring Framework Types
 * 
 * Type definitions for monitoring framework architecture,
 * integration, and maturity models.
 * 
 * Generated by CC - Claude Code
 */

export interface MonitoringFramework {
  approach: string;
  methodology: string;
  principles: string[];
  scope: FrameworkScope;
  architecture: FrameworkArchitecture;
  integration: FrameworkIntegration;
  standards: FrameworkStandard[];
  maturity: FrameworkMaturity;
}

export interface FrameworkScope {
  dimensions: string[];
  levels: string[];
  coverage: string[];
  boundaries: string[];
  exclusions: string[];
}

export interface FrameworkArchitecture {
  layers: ArchitectureLayer[];
  components: ArchitectureComponent[];
  interfaces: ArchitectureInterface[];
  data_flow: string[];
  integration_points: string[];
}

export interface ArchitectureLayer {
  layer: string;
  purpose: string;
  components: string[];
  interfaces: string[];
  responsibilities: string[];
}

export interface ArchitectureComponent {
  component: string;
  function: string;
  inputs: string[];
  outputs: string[];
  dependencies: string[];
  configuration: string;
}

export interface ArchitectureInterface {
  interface: string;
  type: 'API' | 'event' | 'batch' | 'streaming' | 'file';
  protocol: string;
  format: string;
  frequency: string;
  security: string;
}

export interface FrameworkIntegration {
  systems: IntegrationSystem[];
  patterns: string[];
  protocols: string[];
  standards: string[];
  security: string[];
}

export interface IntegrationSystem {
  system: string;
  type: 'source' | 'target' | 'intermediary';
  purpose: string;
  interface: string;
  frequency: string;
  criticality: string;
}

export interface FrameworkStandard {
  standard: string;
  domain: string;
  version: string;
  compliance: string;
  implementation: string;
}

export interface FrameworkMaturity {
  current_level: string;
  target_level: string;
  assessment: string;
  roadmap: string[];
  timeline: string;
}