/**
 * Reload button component for checking if agent questionnaire is ready
 * Appears on fallback questionnaires to allow users to check for AI-generated versions
 */

import React, { useState } from "react";
import { RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/components/ui/use-toast";
import { apiCall } from "@/config/api";

interface QuestionnaireData {
  questions: Array<{
    id: string;
    text: string;
    type: string;
    options?: string[];
  }>;
  metadata?: Record<string, unknown>;
}

interface QuestionnaireReloadButtonProps {
  flowId: string;
  onQuestionnaireReady: (questionnaire: QuestionnaireData) => void;
  className?: string;
}

export const QuestionnaireReloadButton: React.FC<
  QuestionnaireReloadButtonProps
> = ({ flowId, onQuestionnaireReady, className = "" }) => {
  const [isChecking, setIsChecking] = useState(false);

  const checkForAgentQuestionnaire = async () => {
    setIsChecking(true);

    try {
      // Check if agent questionnaire is ready
      const response = await apiCall(
        `/collection/flows/${flowId}/questionnaires/status`
      );

      if (response.status === "ready" && response.questionnaire) {
        toast({
          title: "AI Questionnaire Ready!",
          description:
            "Loading your personalized questionnaire generated by AI agents.",
          variant: "default",
        });
        onQuestionnaireReady(response.questionnaire);
      } else {
        toast({
          title: "AI Questionnaire Not Ready",
          description:
            "The AI-generated questionnaire is still being prepared. Please try again in a few moments.",
          variant: "default",
        });
      }
    } catch (error) {
      console.error("Failed to check for agent questionnaire:", error);
      toast({
        title: "Check Failed",
        description: "Unable to check questionnaire status. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsChecking(false);
    }
  };

  return (
    <div className={`bg-blue-50 border border-blue-200 rounded-lg p-4 ${className}`}>
      <div className="flex items-start gap-3">
        <RefreshCw className="h-5 w-5 text-blue-600 mt-0.5" />
        <div className="flex-1">
          <p className="text-sm font-medium text-blue-900">
            Using Template Questionnaire
          </p>
          <p className="text-sm text-blue-700 mt-1">
            You're currently using a comprehensive template questionnaire. Our AI
            agents may still be generating a personalized version tailored to your
            specific needs.
          </p>
          <Button
            onClick={checkForAgentQuestionnaire}
            disabled={isChecking}
            variant="outline"
            size="sm"
            className="mt-3"
          >
            {isChecking ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Checking...
              </>
            ) : (
              <>
                <RefreshCw className="h-4 w-4 mr-2" />
                Check for AI Questionnaire
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
};
