/**
 * FinOps Analytics and Reporting Types
 * 
 * Type definitions for FinOps analytics, reporting, insights, and KPI tracking.
 * Covers financial analytics, trend analysis, forecasting, and executive reporting.
 * 
 * Generated by CC (Claude Code) - Modularized from finops.ts
 */

import {
  BaseApiRequest,
  BaseApiResponse,
  MultiTenantContext
} from '../shared';
import { CostAmount } from './cost-analysis';

// FinOps Analytics and Reporting APIs
export interface GetFinOpsAnalyticsRequest extends BaseApiRequest {
  flowId?: string;
  timeRange?: {
    start: string;
    end: string;
  };
  metrics?: string[];
  dimensions?: string[];
  aggregation?: 'sum' | 'avg' | 'min' | 'max' | 'count';
  currency?: string;
  includeForecasts?: boolean;
  context: MultiTenantContext;
}

export interface GetFinOpsAnalyticsResponse extends BaseApiResponse<FinOpsAnalytics> {
  data: FinOpsAnalytics;
  insights: FinOpsInsight[];
  trends: FinOpsTrend[];
  benchmarks: FinOpsBenchmark[];
  forecasts: FinOpsForecast[];
  kpis: FinOpsKPI[];
}

export interface GenerateFinOpsReportRequest extends BaseApiRequest {
  flowId: string;
  reportType: 'cost_analysis' | 'budget_performance' | 'optimization' | 'governance' | 'executive';
  format: 'pdf' | 'html' | 'docx' | 'xlsx' | 'json';
  timeRange?: {
    start: string;
    end: string;
  };
  sections?: string[];
  currency?: string;
  customizations?: ReportCustomization;
  context: MultiTenantContext;
}

export interface GenerateFinOpsReportResponse extends BaseApiResponse<FinOpsReport> {
  data: FinOpsReport;
  reportId: string;
  downloadUrl: string;
  expiresAt: string;
}

// Supporting Data Types
export interface FinOpsAnalytics {
  id: string;
  flowId: string;
  timeRange: {
    start: string;
    end: string;
  };
  scope: AnalyticsScope;
  summary: AnalyticsSummary;
  metrics: AnalyticsMetric[];
  dimensions: AnalyticsDimension[];
  trends: AnalyticsTrend[];
  forecasts: AnalyticsForecast[];
  comparisons: AnalyticsComparison[];
  insights: AnalyticsInsight[];
  generatedAt: string;
}

export interface AnalyticsScope {
  accounts: string[];
  services: string[];
  regions: string[];
  projects: string[];
  costCenters: string[];
  environments: string[];
  tags: Record<string, string>;
}

export interface AnalyticsSummary {
  totalCost: CostAmount;
  totalBudget: CostAmount;
  totalSavings: CostAmount;
  utilizationRate: number;
  complianceScore: number;
  optimizationOpportunities: number;
  activeAlerts: number;
  kpiStatus: KPIStatus;
}

export interface KPIStatus {
  meeting: number;
  atRisk: number;
  missing: number;
  total: number;
  overallHealth: 'healthy' | 'warning' | 'critical';
}

export interface AnalyticsMetric {
  name: string;
  category: 'cost' | 'budget' | 'utilization' | 'performance' | 'compliance';
  value: number;
  unit: string;
  target?: number;
  threshold?: MetricThreshold;
  trend: MetricTrend;
  significance: 'low' | 'medium' | 'high';
  context: MetricContext;
}

export interface MetricThreshold {
  warning: number;
  critical: number;
  target: number;
}

export interface MetricTrend {
  direction: 'increasing' | 'decreasing' | 'stable';
  rate: number;
  confidence: number;
  timeframe: string;
}

export interface MetricContext {
  baseline: number;
  benchmark: number;
  percentile: number;
  comparison: 'above' | 'below' | 'within_range';
}

export interface AnalyticsDimension {
  name: string;
  type: 'categorical' | 'numerical' | 'temporal';
  values: DimensionValue[];
  aggregations: DimensionAggregation[];
  insights: DimensionInsight[];
}

export interface DimensionValue {
  value: string;
  count: number;
  cost: CostAmount;
  percentage: number;
  trend: 'increasing' | 'decreasing' | 'stable';
}

export interface DimensionAggregation {
  function: 'sum' | 'avg' | 'min' | 'max' | 'count' | 'median';
  result: number;
  unit: string;
}

export interface DimensionInsight {
  type: 'outlier' | 'pattern' | 'correlation' | 'anomaly';
  description: string;
  significance: number;
  actionable: boolean;
}

export interface AnalyticsTrend {
  metric: string;
  timeframe: string;
  direction: 'increasing' | 'decreasing' | 'stable' | 'cyclical';
  magnitude: number;
  acceleration: number;
  seasonality: SeasonalityPattern;
  projections: TrendProjection[];
  drivers: TrendDriver[];
}

export interface SeasonalityPattern {
  detected: boolean;
  pattern: 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';
  strength: number;
  confidence: number;
}

export interface TrendProjection {
  horizon: string;
  value: number;
  confidence: number;
  scenario: 'optimistic' | 'realistic' | 'pessimistic';
}

export interface TrendDriver {
  factor: string;
  contribution: number;
  type: 'internal' | 'external' | 'seasonal' | 'structural';
  controllable: boolean;
}

export interface AnalyticsForecast {
  metric: string;
  method: 'linear' | 'exponential' | 'arima' | 'ml_ensemble';
  horizon: string;
  predictions: ForecastPrediction[];
  accuracy: ForecastAccuracy;
  assumptions: ForecastAssumption[];
  scenarios: ForecastScenario[];
}

export interface ForecastPrediction {
  period: string;
  value: number;
  confidence: ForecastConfidence;
  factors: string[];
}

export interface ForecastConfidence {
  level: number;
  upperBound: number;
  lowerBound: number;
  interval: string;
}

export interface ForecastAccuracy {
  mae: number; // Mean Absolute Error
  mape: number; // Mean Absolute Percentage Error
  rmse: number; // Root Mean Square Error
  r2: number; // R-squared
  historicalAccuracy: number;
}

export interface ForecastAssumption {
  category: 'business' | 'technical' | 'economic' | 'regulatory';
  description: string;
  impact: 'low' | 'medium' | 'high';
  probability: number;
}

export interface ForecastScenario {
  name: string;
  type: 'base' | 'optimistic' | 'pessimistic' | 'stress';
  probability: number;
  assumptions: string[];
  predictions: ForecastPrediction[];
  impact: ScenarioImpact;
}

export interface ScenarioImpact {
  cost: CostAmount;
  budget: CostAmount;
  variance: number;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
}

export interface AnalyticsComparison {
  type: 'period_over_period' | 'budget_vs_actual' | 'forecast_vs_actual' | 'peer_benchmark';
  baseline: ComparisonBaseline;
  target: ComparisonTarget;
  variance: ComparisonVariance;
  insights: ComparisonInsight[];
  significance: 'low' | 'medium' | 'high';
}

export interface ComparisonBaseline {
  period: string;
  metrics: Record<string, number>;
  context: string;
}

export interface ComparisonTarget {
  period: string;
  metrics: Record<string, number>;
  context: string;
}

export interface ComparisonVariance {
  absolute: Record<string, number>;
  percentage: Record<string, number>;
  direction: Record<string, 'positive' | 'negative' | 'neutral'>;
  significance: Record<string, 'low' | 'medium' | 'high'>;
}

export interface ComparisonInsight {
  metric: string;
  type: 'improvement' | 'degradation' | 'anomaly' | 'pattern';
  description: string;
  impact: number;
  recommendations: string[];
}

export interface AnalyticsInsight {
  id: string;
  type: 'cost_optimization' | 'budget_variance' | 'trend_analysis' | 'anomaly_detection' | 'performance_insight';
  category: 'financial' | 'operational' | 'strategic' | 'tactical';
  title: string;
  description: string;
  confidence: number;
  impact: InsightImpact;
  urgency: 'low' | 'medium' | 'high' | 'immediate';
  actionable: boolean;
  recommendations: InsightRecommendation[];
  supporting_data: InsightData[];
}

export interface InsightImpact {
  financial: CostAmount;
  operational: string;
  strategic: string;
  risk: 'low' | 'medium' | 'high';
}

export interface InsightRecommendation {
  action: string;
  priority: 'low' | 'medium' | 'high';
  effort: 'low' | 'medium' | 'high';
  timeline: string;
  expectedImpact: string;
}

export interface InsightData {
  metric: string;
  value: number;
  context: string;
  relevance: number;
}

export interface FinOpsInsight extends AnalyticsInsight {
  flowId: string;
  source: 'automated' | 'manual' | 'ml_generated';
  tags: string[];
  lifecycle: InsightLifecycle;
}

export interface InsightLifecycle {
  status: 'new' | 'reviewed' | 'actionable' | 'implemented' | 'resolved' | 'dismissed';
  createdAt: string;
  reviewedAt?: string;
  implementedAt?: string;
  resolvedAt?: string;
  dismissedAt?: string;
  assignee?: string;
}

export interface FinOpsTrend extends AnalyticsTrend {
  flowId: string;
  category: 'cost' | 'budget' | 'optimization' | 'governance' | 'utilization';
  alertThresholds: TrendAlertThreshold[];
  businessContext: TrendBusinessContext;
}

export interface TrendAlertThreshold {
  type: 'rate_of_change' | 'absolute_value' | 'duration' | 'volatility';
  threshold: number;
  severity: 'info' | 'warning' | 'critical';
  action: string;
}

export interface TrendBusinessContext {
  events: BusinessEvent[];
  correlations: BusinessCorrelation[];
  explanations: string[];
}

export interface BusinessEvent {
  date: string;
  type: 'launch' | 'migration' | 'optimization' | 'incident' | 'seasonal';
  description: string;
  impact: 'positive' | 'negative' | 'neutral';
}

export interface BusinessCorrelation {
  metric: string;
  correlation: number;
  significance: number;
  explanation: string;
}

export interface FinOpsBenchmark {
  id: string;
  name: string;
  type: 'industry' | 'peer' | 'internal' | 'best_practice';
  category: 'cost_efficiency' | 'optimization_maturity' | 'governance_compliance';
  metric: string;
  value: number;
  unit: string;
  percentile: number;
  comparison: BenchmarkComparison;
  context: BenchmarkContext;
  actionability: BenchmarkActionability;
}

export interface BenchmarkComparison {
  current: number;
  benchmark: number;
  variance: number;
  performance: 'leading' | 'average' | 'lagging';
  ranking: number;
  totalParticipants: number;
}

export interface BenchmarkContext {
  industry: string;
  companySize: string;
  geography: string;
  methodology: string;
  dataSource: string;
  lastUpdated: string;
}

export interface BenchmarkActionability {
  improvementPotential: number;
  difficultyLevel: 'low' | 'medium' | 'high';
  timeToImprovement: string;
  requiredInvestment: CostAmount;
  recommendations: string[];
}

export interface FinOpsForecast extends AnalyticsForecast {
  flowId: string;
  category: 'cost' | 'budget' | 'savings' | 'utilization';
  businessDrivers: ForecastBusinessDriver[];
  riskFactors: ForecastRiskFactor[];
  monitoring: ForecastMonitoring;
}

export interface ForecastBusinessDriver {
  name: string;
  type: 'growth' | 'efficiency' | 'market' | 'regulatory';
  impact: number;
  probability: number;
  timeline: string;
}

export interface ForecastRiskFactor {
  name: string;
  type: 'market' | 'technical' | 'operational' | 'regulatory';
  likelihood: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  mitigation: string;
}

export interface ForecastMonitoring {
  triggers: ForecastTrigger[];
  alerts: ForecastAlert[];
  recalibration: ForecastRecalibration;
}

export interface ForecastTrigger {
  condition: string;
  threshold: number;
  action: 'recalculate' | 'alert' | 'escalate';
}

export interface ForecastAlert {
  condition: string;
  severity: 'info' | 'warning' | 'critical';
  recipients: string[];
  message: string;
}

export interface ForecastRecalibration {
  frequency: string;
  triggers: string[];
  automated: boolean;
  approval_required: boolean;
}

export interface FinOpsKPI {
  id: string;
  name: string;
  category: 'cost' | 'budget' | 'optimization' | 'governance' | 'efficiency';
  type: 'absolute' | 'ratio' | 'percentage' | 'index';
  value: number;
  unit: string;
  target: KPITarget;
  status: KPIStatus;
  trend: KPITrend;
  benchmark: KPIBenchmark;
  calculation: KPICalculation;
  reporting: KPIReporting;
}

export interface KPITarget {
  value: number;
  type: 'minimum' | 'maximum' | 'range' | 'exact';
  range?: {
    min: number;
    max: number;
  };
  timeframe: string;
  rationale: string;
}

export interface KPITrend {
  direction: 'improving' | 'declining' | 'stable';
  velocity: number;
  consistency: number;
  seasonality: boolean;
  projection: KPIProjection;
}

export interface KPIProjection {
  nextPeriod: number;
  confidence: number;
  targetAchievement: 'likely' | 'possible' | 'unlikely';
  recommendedActions: string[];
}

export interface KPIBenchmark {
  internal: number;
  industry: number;
  bestPractice: number;
  percentile: number;
  relative_performance: 'leading' | 'average' | 'lagging';
}

export interface KPICalculation {
  formula: string;
  inputs: KPIInput[];
  frequency: string;
  methodology: string;
  limitations: string[];
}

export interface KPIInput {
  name: string;
  source: string;
  freshness: string;
  reliability: number;
}

export interface KPIReporting {
  frequency: 'real_time' | 'daily' | 'weekly' | 'monthly' | 'quarterly';
  recipients: string[];
  format: 'dashboard' | 'report' | 'alert' | 'email';
  escalation: KPIEscalation[];
}

export interface KPIEscalation {
  condition: string;
  threshold: number;
  recipients: string[];
  urgency: 'low' | 'medium' | 'high' | 'critical';
}

export interface FinOpsReport {
  id: string;
  reportId: string;
  flowId: string;
  type: string;
  format: string;
  title: string;
  description: string;
  timeRange: {
    start: string;
    end: string;
  };
  sections: ReportSection[];
  metadata: ReportMetadata;
  distribution: ReportDistribution;
  security: ReportSecurity;
  generatedAt: string;
  expiresAt: string;
}

export interface ReportSection {
  id: string;
  name: string;
  type: 'summary' | 'detailed' | 'chart' | 'table' | 'narrative';
  content: ReportContent;
  visualization: ReportVisualization;
  data: ReportData;
}

export interface ReportContent {
  title: string;
  summary: string;
  insights: string[];
  recommendations: string[];
  appendices: string[];
}

export interface ReportVisualization {
  type: 'chart' | 'table' | 'dashboard' | 'infographic';
  configuration: Record<string, any>;
  interactive: boolean;
  exportable: boolean;
}

export interface ReportData {
  source: string;
  freshness: string;
  filters: Record<string, any>;
  aggregations: Record<string, any>;
  calculations: Record<string, any>;
}

export interface ReportMetadata {
  author: string;
  version: string;
  template: string;
  customizations: string[];
  tags: string[];
  approvals: ReportApproval[];
}

export interface ReportApproval {
  type: 'content' | 'data' | 'distribution';
  approver: string;
  status: 'pending' | 'approved' | 'rejected';
  timestamp: string;
  comments: string;
}

export interface ReportDistribution {
  method: 'download' | 'email' | 'portal' | 'api';
  recipients: ReportRecipient[];
  schedule: ReportSchedule;
  access: ReportAccess;
}

export interface ReportRecipient {
  type: 'user' | 'group' | 'role' | 'external';
  identifier: string;
  format: string[];
  customizations: Record<string, any>;
}

export interface ReportSchedule {
  frequency: 'once' | 'daily' | 'weekly' | 'monthly' | 'quarterly';
  time: string;
  timezone: string;
  enabled: boolean;
}

export interface ReportAccess {
  level: 'public' | 'internal' | 'restricted' | 'confidential';
  permissions: string[];
  expiration: string;
  watermark: boolean;
}

export interface ReportSecurity {
  classification: 'public' | 'internal' | 'confidential' | 'restricted';
  encryption: boolean;
  accessLog: boolean;
  downloadTracking: boolean;
  sharing: ReportSharing;
}

export interface ReportSharing {
  allowed: boolean;
  restrictions: string[];
  tracking: boolean;
  expiration: string;
}

export interface ReportCustomization {
  template: string;
  branding: BrandingCustomization;
  content: ContentCustomization;
  format: FormatCustomization;
  delivery: DeliveryCustomization;
}

export interface BrandingCustomization {
  logo: string;
  colors: Record<string, string>;
  fonts: Record<string, string>;
  watermark: string;
}

export interface ContentCustomization {
  sections: string[];
  metrics: string[];
  filters: Record<string, any>;
  aggregations: Record<string, any>;
}

export interface FormatCustomization {
  layout: string;
  pageSize: string;
  orientation: 'portrait' | 'landscape';
  charts: ChartCustomization[];
}

export interface ChartCustomization {
  type: string;
  configuration: Record<string, any>;
  position: string;
  size: string;
}

export interface DeliveryCustomization {
  method: string[];
  schedule: string;
  recipients: string[];
  notifications: boolean;
}