/**
 * Engagement Filters Component Types
 * 
 * Type definitions for engagement filtering systems, saved filters,
 * and advanced search configurations.
 * 
 * Generated by CC (Claude Code) - Modularized from engagement-management.ts
 */

import { ReactNode } from 'react';
import { BaseComponentProps } from '../../shared';
import { Client, Team, User, EngagementStatus, EngagementType } from './core-types';

// Main Engagement Filters Component
export interface EngagementFiltersProps extends BaseComponentProps {
  filters: EngagementFilter[];
  values: Record<string, any>;
  onFiltersChange: (filters: Record<string, any>) => void;
  onReset?: () => void;
  onSave?: (name: string, filters: Record<string, any>) => void;
  savedFilters?: SavedFilter[];
  onLoadSavedFilter?: (filter: SavedFilter) => void;
  onDeleteSavedFilter?: (filter: SavedFilter) => void;
  clients?: Client[];
  teams?: Team[];
  users?: User[];
  loading?: boolean;
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  showSavedFilters?: boolean;
  showFilterCount?: boolean;
  showClearAll?: boolean;
  showApplyButton?: boolean;
  autoApply?: boolean;
  debounceDelay?: number;
  layout?: 'horizontal' | 'vertical' | 'grid' | 'accordion';
  size?: 'xs' | 'sm' | 'md' | 'lg';
  variant?: 'default' | 'compact' | 'expanded';
  maxColumns?: number;
  groupFilters?: boolean;
  filterGroups?: FilterGroup[];
}

// Filter Definitions
export interface EngagementFilter {
  id: string;
  label: string;
  field: string;
  type: FilterType;
  group?: string;
  options?: FilterOption[];
  multiple?: boolean;
  searchable?: boolean;
  clearable?: boolean;
  placeholder?: string;
  defaultValue?: unknown;
  validation?: FilterValidation;
  dependency?: FilterDependency;
  renderer?: FilterRenderer;
  width?: number | string;
  order?: number;
  required?: boolean;
  helpText?: string;
  icon?: string;
  tooltip?: string;
  formatValue?: (value: unknown) => string;
  parseValue?: (value: string) => any;
}

export type FilterType = 
  | 'text' | 'number' | 'date' | 'dateRange' | 'select' | 'multiSelect' 
  | 'boolean' | 'tag' | 'autocomplete' | 'range' | 'slider' | 'rating'
  | 'color' | 'file' | 'location' | 'custom';

export interface FilterOption {
  label: string;
  value: unknown;
  description?: string;
  icon?: string;
  color?: string;
  disabled?: boolean;
  group?: string;
  count?: number;
  metadata?: Record<string, any>;
}

export interface FilterValidation {
  required?: boolean;
  min?: number;
  max?: number;
  minLength?: number;
  maxLength?: number;
  pattern?: string | RegExp;
  custom?: (value: unknown) => boolean | string;
  message?: string;
}

export interface FilterDependency {
  field: string;
  condition: (value: unknown) => boolean;
  action: 'show' | 'hide' | 'enable' | 'disable' | 'reset' | 'update_options';
  options?: FilterOption[];
}

export type FilterRenderer = (
  filter: EngagementFilter, 
  value: any, 
  onChange: (value: unknown) => void,
  props?: any
) => ReactNode;

// Filter Groups
export interface FilterGroup {
  id: string;
  label: string;
  description?: string;
  filters: string[];
  collapsible?: boolean;
  defaultCollapsed?: boolean;
  icon?: string;
  order?: number;
  layout?: 'horizontal' | 'vertical' | 'grid';
  columns?: number;
}

// Saved Filters
export interface SavedFilter {
  id: string;
  name: string;
  description?: string;
  filters: Record<string, any>;
  sorting?: SortConfig[];
  columns?: string[];
  isDefault?: boolean;
  isGlobal?: boolean;
  isPublic?: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  usageCount?: number;
  tags?: string[];
  category?: string;
  icon?: string;
  color?: string;
  metadata?: Record<string, any>;
}

export interface SortConfig {
  field: string;
  direction: 'asc' | 'desc';
  priority?: number;
}

// Advanced Search
export interface AdvancedSearchProps extends BaseComponentProps {
  onSearch: (query: AdvancedSearchQuery) => void;
  onSave?: (name: string, query: AdvancedSearchQuery) => void;
  savedSearches?: SavedSearch[];
  searchFields: SearchField[];
  operators?: SearchOperator[];
  allowComplexQueries?: boolean;
  showQueryBuilder?: boolean;
  showSavedSearches?: boolean;
  maxConditions?: number;
  size?: 'sm' | 'md' | 'lg';
}

export interface AdvancedSearchQuery {
  conditions: SearchCondition[];
  logicalOperator: 'and' | 'or';
  sorting?: SortConfig[];
  limit?: number;
  offset?: number;
}

export interface SearchCondition {
  field: string;
  operator: string;
  value: unknown;
  logicalOperator?: 'and' | 'or';
  negated?: boolean;
  caseSensitive?: boolean;
}

export interface SearchField {
  id: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multiselect';
  operators: string[];
  options?: FilterOption[];
  format?: string;
  validation?: SearchFieldValidation;
}

export interface SearchFieldValidation {
  required?: boolean;
  pattern?: string;
  min?: number;
  max?: number;
  custom?: (value: unknown) => boolean | string;
}

export interface SearchOperator {
  id: string;
  label: string;
  symbol: string;
  description?: string;
  example?: string;
  types: string[];
  valueRequired: boolean;
  multiValue?: boolean;
}

export interface SavedSearch {
  id: string;
  name: string;
  description?: string;
  query: AdvancedSearchQuery;
  isDefault?: boolean;
  isPublic?: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  usageCount?: number;
  tags?: string[];
}

// Quick Filters
export interface QuickFiltersProps extends BaseComponentProps {
  quickFilters: QuickFilter[];
  activeFilters: string[];
  onFilterToggle: (filterId: string) => void;
  onClearAll?: () => void;
  size?: 'xs' | 'sm' | 'md' | 'lg';
  variant?: 'chips' | 'buttons' | 'toggle';
  showClearAll?: boolean;
  maxVisible?: number;
  allowMultiple?: boolean;
}

export interface QuickFilter {
  id: string;
  label: string;
  description?: string;
  icon?: string;
  color?: string;
  filters: Record<string, any>;
  count?: number;
  shortcut?: string;
  category?: string;
  order?: number;
  isDefault?: boolean;
}

// Filter State Management
export interface FilterState {
  filters: Record<string, any>;
  activeQuickFilters: string[];
  searchQuery: string;
  advancedSearch?: AdvancedSearchQuery;
  savedFilterId?: string;
  isFiltered: boolean;
  filterCount: number;
  appliedFilters: AppliedFilter[];
}

export interface AppliedFilter {
  id: string;
  field: string;
  label: string;
  value: unknown;
  displayValue: string;
  operator?: string;
  removable: boolean;
  type: FilterType;
}

// Filter Analytics
export interface FilterAnalytics {
  mostUsedFilters: FilterUsage[];
  filterCombinations: FilterCombination[];
  avgFiltersPerSearch: number;
  filterEffectiveness: FilterEffectiveness[];
  popularSavedFilters: SavedFilterUsage[];
}

export interface FilterUsage {
  filterId: string;
  label: string;
  usageCount: number;
  usagePercent: number;
  avgResultsReturned: number;
  lastUsed: string;
}

export interface FilterCombination {
  filters: string[];
  usageCount: number;
  usagePercent: number;
  avgResultsReturned: number;
  effectiveness: number;
}

export interface FilterEffectiveness {
  filterId: string;
  label: string;
  avgReductionPercent: number;
  avgResultsWithoutFilter: number;
  avgResultsWithFilter: number;
  effectiveness: 'high' | 'medium' | 'low';
}

export interface SavedFilterUsage {
  filterId: string;
  name: string;
  usageCount: number;
  uniqueUsers: number;
  avgSessionDuration: number;
  lastUsed: string;
}

// Preset Filters for Common Use Cases
export interface PresetFilters {
  myEngagements: QuickFilter;
  activeEngagements: QuickFilter;
  overdueDeliverables: QuickFilter;
  highRiskEngagements: QuickFilter;
  recentlyCompleted: QuickFilter;
  budgetOverruns: QuickFilter;
  upcomingMilestones: QuickFilter;
  teamUtilization: QuickFilter;
}

// Filter Suggestions
export interface FilterSuggestion {
  id: string;
  label: string;
  description: string;
  filters: Record<string, any>;
  reason: 'popular' | 'similar_user' | 'historical' | 'trending';
  confidence: number;
  estimatedResults: number;
  icon?: string;
}

// Filter Performance Metrics
export interface FilterPerformance {
  responseTime: number;
  cacheHitRate: number;
  indexUsage: number;
  memoryUsage: number;
  queryComplexity: number;
  optimizationSuggestions: string[];
}

// Smart Filter Features
export interface SmartFilterConfig {
  enableAutoComplete: boolean;
  enableSuggestions: boolean;
  enableTypoCorrection: boolean;
  enableQueryOptimization: boolean;
  enableResultsCaching: boolean;
  enableFilterRecommendations: boolean;
  maxSuggestions: number;
  suggestionTypes: ('similar' | 'popular' | 'recent' | 'trending')[];
}

// Filter Export/Import
export interface FilterExportOptions {
  includeValues: boolean;
  includeMetadata: boolean;
  format: 'json' | 'csv' | 'xml';
  compression?: 'gzip' | 'zip';
}

export interface FilterImportOptions {
  mergeStrategy: 'replace' | 'merge' | 'append';
  validateSchema: boolean;
  createMissing: boolean;
  updateExisting: boolean;
}

// Filter Customization
export interface FilterCustomization {
  allowCustomFilters: boolean;
  customFilterTypes: CustomFilterType[];
  maxCustomFilters: number;
  customFilterValidation: ValidationRule[];
  customFilterPermissions: FilterPermission[];
}

export interface CustomFilterType {
  id: string;
  name: string;
  description: string;
  component: string;
  configSchema: unknown;
  validation: ValidationRule[];
  examples: unknown[];
}

export interface FilterPermission {
  filterId: string;
  userId?: string;
  roleId?: string;
  permission: 'view' | 'use' | 'edit' | 'delete' | 'share';
  grantedBy: string;
  grantedAt: string;
  expiresAt?: string;
}

export interface ValidationRule {
  type: 'required' | 'format' | 'range' | 'custom';
  message: string;
  parameters?: Record<string, any>;
}

// Filter UI Components
export interface FilterChipProps {
  filter: AppliedFilter;
  onRemove: (filterId: string) => void;
  onEdit?: (filterId: string) => void;
  size?: 'xs' | 'sm' | 'md';
  variant?: 'default' | 'outline' | 'solid';
  showOperator?: boolean;
  editable?: boolean;
}

export interface FilterBarProps extends BaseComponentProps {
  appliedFilters: AppliedFilter[];
  onFilterRemove: (filterId: string) => void;
  onFilterEdit?: (filterId: string) => void;
  onClearAll?: () => void;
  maxVisible?: number;
  showCount?: boolean;
  showClearAll?: boolean;
  size?: 'xs' | 'sm' | 'md' | 'lg';
  layout?: 'horizontal' | 'vertical' | 'wrap';
}

export interface FilterMenuProps extends BaseComponentProps {
  trigger: ReactNode;
  filters: EngagementFilter[];
  values: Record<string, any>;
  onFiltersChange: (filters: Record<string, any>) => void;
  onSave?: (name: string, filters: Record<string, any>) => void;
  savedFilters?: SavedFilter[];
  showSavedFilters?: boolean;
  position?: 'bottom' | 'top' | 'left' | 'right';
  width?: number | string;
  maxHeight?: number | string;
}