/**
 * Core Engagement Types
 *
 * Core engagement entity definitions, phases, deliverables, and milestones
 * for engagement management.
 *
 * Generated by CC (Claude Code) - Modularized from core-types.ts
 */

import type { Client } from './client-management';
import type { User, TeamMember } from './team-management';
import type { Risk, Issue } from './risk-issue-management';
import type { Artifact } from './artifact-management';

// Core Type Definitions
export type EngagementStatus = 'draft' | 'active' | 'on_hold' | 'completed' | 'cancelled';
export type EngagementType = 'discovery' | 'assessment' | 'migration' | 'optimization' | 'support' | 'training';
export type PhaseStatus = 'not_started' | 'in_progress' | 'on_hold' | 'completed' | 'cancelled';
export type DeliverableType = 'document' | 'presentation' | 'code' | 'design' | 'analysis' | 'report';
export type DeliverableStatus = 'not_started' | 'in_progress' | 'review' | 'approved' | 'delivered';
export type MilestoneStatus = 'pending' | 'achieved' | 'missed' | 'cancelled';

// Core Engagement Entity
export interface Engagement {
  id: string;
  name: string;
  description?: string;
  type: EngagementType;
  status: EngagementStatus;
  clientId: string;
  client: Client;
  startDate: string;
  endDate?: string;
  estimatedEndDate?: string;
  budget?: number;
  currency?: string;
  teamLead: User;
  teamMembers: TeamMember[];
  phases: EngagementPhase[];
  deliverables: Deliverable[];
  milestones: Milestone[];
  risks: Risk[];
  issues: Issue[];
  artifacts: Artifact[];
  progress: number;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  tags?: string[];
  metadata?: Record<string, string | number | boolean | null>;
}

// Phase Management Types
export interface EngagementPhase {
  id: string;
  name: string;
  description?: string;
  order: number;
  status: PhaseStatus;
  startDate: string;
  endDate?: string;
  estimatedEndDate: string;
  duration: number; // in days
  budget?: number;
  actualCost?: number;
  progress: number;
  deliverables: Deliverable[];
  milestones: Milestone[];
  dependencies: string[]; // IDs of dependent phases
  prerequisites: string[];
  team: TeamMember[];
  risks: Risk[];
  issues: Issue[];
  artifacts: Artifact[];
  createdAt: string;
  updatedAt: string;
  metadata?: Record<string, string | number | boolean | null>;
}

// Deliverable Management Types
export interface Deliverable {
  id: string;
  name: string;
  description?: string;
  type: DeliverableType;
  status: DeliverableStatus;
  phaseId: string;
  phase: EngagementPhase;
  dueDate: string;
  completedDate?: string;
  owner: User;
  reviewers: User[];
  approvers: User[];
  dependencies: string[];
  template?: string;
  fileUrl?: string;
  version: string;
  size?: number;
  format?: string;
  progress: number;
  qualityScore?: number;
  reviewComments: ReviewComment[];
  createdAt: string;
  updatedAt: string;
  metadata?: Record<string, string | number | boolean | null>;
}

export interface ReviewComment {
  id: string;
  comment: string;
  author: User;
  status: 'pending' | 'addressed' | 'resolved' | 'rejected';
  priority: 'low' | 'medium' | 'high';
  createdAt: string;
  updatedAt: string;
  resolvedAt?: string;
  resolvedBy?: User;
}

// Milestone Management Types
export interface Milestone {
  id: string;
  name: string;
  description?: string;
  type: 'phase_gate' | 'delivery' | 'approval' | 'go_live' | 'review' | 'custom';
  status: MilestoneStatus;
  dueDate: string;
  achievedDate?: string;
  phaseId?: string;
  phase?: EngagementPhase;
  criteria: MilestoneCriteria[];
  dependencies: string[];
  deliverables: string[];
  approvers: User[];
  owner: User;
  progress: number;
  isGate: boolean; // If true, blocks phase progression
  isCritical: boolean;
  weight: number; // Relative importance
  createdAt: string;
  updatedAt: string;
  metadata?: Record<string, string | number | boolean | null>;
}

export interface MilestoneCriteria {
  id: string;
  description: string;
  weight: number;
  isMandatory: boolean;
  status: 'pending' | 'met' | 'failed' | 'waived';
  evidence?: string;
  evaluatedBy?: User;
  evaluatedAt?: string;
  comments?: string;
}
