/**
 * Engagement Management Types - Module Index
 * 
 * Centralized exports for all engagement management type modules.
 * Provides a single entry point for importing engagement-related types.
 * 
 * Generated by CC (Claude Code) - Modularized from engagement-management.ts
 */

// Core Types - Basic entities and enums
export * from './core-types';

// Engagement Listing - Table, filtering, and list views
export * from './engagement-list';

// Engagement Creation - Forms, workflows, and templates
export * from './engagement-creation';

// Engagement Filters - Advanced filtering and search
export * from './engagement-filters';

// Re-export commonly used types for convenience
export type {
  // Core Entities
  Engagement,
  Client,
  Team,
  User,
  EngagementPhase,
  Deliverable,
  Milestone,
  Risk,
  Issue,
  
  // Status and Type Enums
  EngagementStatus,
  EngagementType,
  PhaseStatus,
  DeliverableStatus,
  MilestoneStatus,
  
  // Main Component Props
  EngagementListProps,
  EngagementCreationProps,
  EngagementFiltersProps,
  
  // Key Workflow Types
  CreateEngagementRequest,
  EngagementFilter,
  SavedFilter,
  EngagementTemplate,
  
  // Summary and Metrics
  EngagementSummary,
  EngagementMetrics
} from './core-types';